### ISSUE TITLE
Result is incorrect or no highlighting when search with regular expression.

### ISSUE THREAD

**Issue by GrandZhuo** [jonas/tig#1000]
I use vim a lot, so I am very accustomed to using regular expressions for searching. But I found that sometimes search results are wrong or no highlighting .

For example, I use '/m$' to find lines that end with m, but the search results are completely wrong. If I use '/mm$', it can search for the correct result but without highlighting.

It seems that as long as I use '$' to match line ending, the search results are not highlighted.

The above results are tested in my project, I'm not sure what it looks like in your project

tig version 2.5.0
ncurses version 5.7.20081102
readline version 8.0

**Comment by koutcher** [comment]
The problem with $ is due to search highlighting being done directly on a copy of screen buffer, so all lines are padded with spaces to screen width. There no perfect solution but maybe trimming spaces would be a good compromise.
