### ISSUE TITLE
Next file / next hunk key binding in diff view

### ISSUE THREAD

**Issue by jaroslawr** [jonas/tig#1005]
It would be very nice to have some more default key bindings in the diff view for basic navigation:
- go to previous hunk
- go to next hunk
- go to previous file
- go to next file

**Comment by krobelus** [comment]
There is already a default binding for hunks:
```
bind diff	@	:/^@@			# Jump to next (c)hunk
```

(use `N` to continue the search backwards)

I'm using `<C-f>` and `<C-b>` for next/prev file. Magit uses `<M-n>` and `<M-p>`.
