### ISSUE TITLE
Going back in the history of a file ? ( like emacs package git-timemachine )

### ISSUE THREAD

**Issue by sucrecacao** [jonas/tig#1006]
Hi,
A powerfull emacs package called [git-timemachine](https://gitlab.com/pidu/git-timemachine) allow user to visit the older version of a file, and navigate back and forth between older and newer version of the same file. 
Is it possible to achieve the same with tig ?

**Comment by koutcher** [comment]
The closer you can get is to navigate between the different commits involving a file (open Tig with `tig path/to/file`) and to open the blob view (`f`) from the split diff view. Not so convenient as you have to do it from a diff chunk, but, while it feels natural for a text editor like emacs to be focused on files, Tig is meant to be commit oriented.

**Comment by kaihendry** [comment]
I'm still absolutely puzzled how to navigated between commits as I keep seeing the blob of the first file I viewed. In some reset button I'm missing?

**Comment by koutcher** [comment]
Some Tig revisions maybe. I think you need at least 2.5.2 with 0c2416a.

**Comment by kaihendry** [comment]
```
$ tig --version
tig version 2.5.4
ncursesw version 6.2.20200212
readline version 8.1
```

**Comment by koutcher** [comment]
Then, do you open the blob view from the diff view every time ?
