### ISSUE TITLE
Feature request: remove file (from within status view)

### ISSUE THREAD

**Issue by redstreet** [jonas/tig#1007]
tig is awesome and makes me much more productive!

Is it possible to add file deletion functionality from within the status view? This would help get rid of temporary, inadvertent, and other unwanted files simply by pressing say, 'shift+d' on the file from within status view, with an optional confirm delete. I find myself quitting tig a lot just to delete a file, and restarting tig.

Thank you for this terrific interface to git!

**Comment by koutcher** [comment]
Just add `bind status	D	?rm %(file)` to your .tigrc.

**Comment by redstreet** [comment]
Ah, thank you!
