### ISSUE TITLE
Blame an unstaged deletion

### ISSUE THREAD

**Issue by krobelus** [jonas/tig#1008]
I often want to find the commit that introduced a line which is deleted in the working tree or index.
Mostly for finding the right target for a fixup.

[Fugitive](https://github.com/tpope/vim-fugitive/) has spoiled me in this regard because I can press `o` on a deleted line followed by `:Gblame` to see which commit added the line.

For Tig, I think it would make sense to press `b` on a not-yet-committed line deletion in the diff view to do the same. Currently those lines will not show up in the blame view because `view-blame` does a blame with respect to the working tree. I wrote [this patch](https://github.com/krobelus/tig/commit/blame-from-head) to make the blame start at `HEAD`, which still has the lines that I deleted later. The starting cursor position is usually not too far from it, but can't be accurate in general because line numbers don't match the ones in the work tree.

I'm wondering if this is a reasonable change, or if there is maybe another way to do this.

<s>I think the proper fix would consist of invoking `git blame` once to find out which commit deleted the line at the cursor, and then showing the blame view with that commit and the correct line number.</s>

**Comment by koutcher** [comment]
What about something like this instead ?
```patch
diff --git a/src/stage.c b/src/stage.c
index 565c946..28d4060 100644
--- a/src/stage.c
+++ b/src/stage.c
@@ -444,7 +444,10 @@ stage_request(struct view *view, enum request request, struct line *line)
 				string_ncopy(view->env->file, file, strlen(file));
 		}
 
-		view->env->ref[0] = 0;
+		if (line->type == LINE_DIFF_DEL)
+			string_copy(view->env->ref, "HEAD");
+		else
+			view->env->ref[0] = 0;
 		view->env->goto_lineno = diff_get_lineno(view, line);
 		if (view->env->goto_lineno > 0)
 			view->env->goto_lineno--;
```
