### ISSUE TITLE
Tig command dont show results

### ISSUE THREAD

**Issue by bbertolani** [jonas/tig#1014]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
Running on Terminal + zsh

tig version = tig-2.5.1
cursesw version 6.2.20200212

First time installing on Ubuntu and got this error. I have the same version on Mac with no errors.
I have no clue how to solve this.

![image](https://user-images.githubusercontent.com/32915510/83577535-cfa25600-a50a-11ea-9b71-0897d9cf1f0c.png)

![image](https://user-images.githubusercontent.com/32915510/83577626-16904b80-a50b-11ea-8c25-fd3e3af127fd.png)

**Comment by koutcher** [comment]
From the screenshot it looks like tig was compiled with option NO_BUILTIN_TIGRC and you don't have a full /etc/tigrc or ~/.tigrc. You can find the default tigrc here: https://github.com/jonas/tig/blob/master/tigrc.

**Comment by bbertolani** [comment]
Exactly! was missing the ~/.tigrc
Tks a lot!
