### ISSUE TITLE
field 'id' in reflog-view does not show SHA hash

### ISSUE THREAD

**Issue by listx** [jonas/tig#1025]
Setting

```
set reflog-view = id:width=40
```

in `.tigrc` does not result in the view showing the SHA hash. Instead it still only prints the symbolic refs like `HEAD@{...}`. I would really like to see the SHAs directly as well, because this is how default git-reflog behaves. So ideally I should be able to do

```
set reflog-view = id:width=40 id:yes
```

to see the SHA and then also the `HEAD@{...}` ref.

- Version: 2.5.1
- Platform: Mac

**Comment by koutcher** [comment]
This is a quite old behaviour which even predates the reflog view. The commit id is visible in the title window. Do you have a specific use case in mind for needing the commit id in the list ?

**Comment by listx** [comment]
> The commit id is visible in the title window.

ACK, but I would prefer to show it in-line directly next to the `HEAD@{...}` ref.

> Do you have a specific use case in mind for needing the commit id in the list ?

I have recently customized most views to show the full commit id, because this is what I end up pasting in docs and comments to peers. I would like to have the same uniformity for the reflog-view as well.
