### ISSUE TITLE
How to work with multiple remotes?

### ISSUE THREAD

**Issue by pomozoff** [jonas/tig#1026]
How do you work with multiple remotes in a repo?
I've a lot of custom shortcuts, but I use hardcoded "origin" for a command.
Is there a smart way to run "fetch", "pull" and "push" commands for a some "active" repo and switch between them easily?

**Comment by pomozoff** [comment]
?
Nobody cares?

**Comment by krobelus** [comment]
@pomozoff I usually pull from "origin" and somtimes set `branch.<name>.pushRemote` if pushing to a different remote (or `remote.pushDefault` to make it apply to all branches)

if you want more flexibility you can teach your custom shortcuts to use an "active remote", which you can toggle with other shortcuts:

```sh
bind generic aef !sh -c 'git fetch "$(cat "$(git rev-parse --git-dir)"/active-remote || echo origin)"'
bind generic aeo !sh -c 'echo origin > "$(git rev-parse --git-dir)/active-remote"'
bind generic aem !sh -c 'echo myremote > "$(git rev-parse --git-dir)/active-remote"'
```
