### ISSUE TITLE
shortcut for copy commit sha

### ISSUE THREAD

**Issue by ooopscc** [jonas/tig#1034]
Sometimes it's really convenient if I can copy the commit sha of the current line. I can do rebase -i fast without mouse.

**Comment by krobelus** [comment]
From [`man tigrc`](http://jonas.github.io/tig/doc/tigrc.5.html)

> Configure a binding to copy the current commit ID to the clipboard.
> `bind generic I @sh -c "echo -n %(commit) | xclip -selection c"`

If this were a default binding it should be platform-independent.

**Comment by ooopscc** [comment]
Thanks for quick reply. I should `man` first.
