### ISSUE TITLE
Cannot bind <Ctrl-Up>/<Ctrl-Down>

### ISSUE THREAD

**Issue by mgedmin** [jonas/tig#1046]
I'm trying to use these mappings in my .tigrc

```
# Scroll with mouse wheel in gnome-terminal (it sends Up/Down key events when in alt screen)
bind diff <Up> move-up
bind diff <Down> move-down

# but I want some way to move to next/previous commit
bind diff <Ctrl-Up> previous
bind diff <Ctrl-Down> next
```

The `tigrc` [manual page](http://manpages.ubuntu.com/manpages/groovy/en/man5/tigrc.5.html#bind%20command) led me to expect this to be valid syntax:

> Key values
>
>  Key values should never be quoted. Use either an ASCII or UTF8-encoded character or one of the following symbolic key names. Symbolic key names are case insensitive and starts with "<" and ends with ">". Use `<Hash>` to bind to the # key, since the hash mark is used as a comment character. Use `<LessThan>` to bind to the < key.
>
>     <Enter>, <Space>, <Backspace>, <Tab>, <Escape> or <Esc>, <Left>, <Right>, <Up>, <Down>, <Insert> or <Ins>,
>     <Delete> or <Del>, <Hash>, <LessThan> or <LT>, <Home>, <End>, <PageUp> or <PgUp>, <PageDown> or <PgDown>,
>     <ScrollBack> or <SBack>, <ScrollFwd> or <SFwd>, <ShiftTab> or <BackTab>, <ShiftLeft>, <ShiftRight>,
>     <ShiftDelete> or <ShiftDel>, <ShiftHome>, <ShiftEnd>, <SingleQuote>, <DoubleQuote>, <F1> ... <F19>
>
> To define key mappings with the Ctrl key, use <Ctrl-key>. In addition, key combos consisting of an initial Escape key followed by a normal key value can be bound using <Esc>key.

also there are no errors printed by `tig` on startup.

Still, when I press ctrl-up, I get a "Unknown key, press h for help", and when I press ctrl-down, nothing happens at all.  Also, these bindings don't show up in the help page shown by `h`.

I've tig version 2.4.1 from Ubuntu 20.10 (ncursesw version 6.2.20200212, readline version 8.0).

**Comment by mgedmin** [comment]
Attempts to work around this with

```
bind generic <Esc>[1;5A previous
bind generic <Esc>[1;5B next
```

were not successful either.

**Comment by mckelly2833** [comment]
Hi,
I couldn't get mappings like that to work either.
I used <ScrollFwd> which is Shift-Down and <ScrollBack> (Shift-Up) for this.  Perhaps that works for you ?
It would be awesome if we could map these type of Ctrl sequences.
thx,
-m

**Comment by mgedmin** [comment]
`<Esc>[A`/`B` is for regular Up/Down; I want to map Ctrl-Up/Down which is `<Esc>[1;5A`/`B` (and I tried that, and it didn't work).

(Wow, I didn't know about `set mouse`!)

**Comment by mckelly2833** [comment]
I haven't fully debugged yet, but I *think* the calculation of the length of the binding is not correct, it stops at:
```
        end = strchr(name + 1, '>');
```
So its 3 for the \<Esc\> - but it needs adjusting for the rest of the string ([1;5A)

**Comment by koutcher** [comment]
With Putty, `<Esc>[A`/`B` works for Ctrl-Up/Down but, indeed, it doesn't work with xterm or gnome-terminal. With xterm or gnome-terminal, Tig doesn't receive `<Esc>[1;5A`/`B` either because ncurses transforms Ctrl-Up/Down in an obscure keycode with a value > KEY_MAX. Hence, I believe, the statement in #381 that bindings such as Ctrl-Down are not supported.

**Comment by mckelly2833** [comment]
@koutcher hi.  Thanks.  But can we alter the check for KEY_MAX (or KEY_MAX) for this ?  Or is that just too much of a break from the ncurses model ?

**Comment by mckelly2833** [comment]
Perhaps allow an ncurses key value directly in .tigrc bindings ?  Or extra foo for special values->names ...
Anyway thanks for the info and I will add something to my fork for it.  I already have a few other mods I find useful (in PRs here).
thx so much,
-m

**Comment by mckelly2833** [comment]
We can check 511+ to find the values for names kDN5 and kUP5 and use those as new CtrlDown and CtrlUp keys.
Or perhaps remove these capabilities at startup somehow to get the esc codes to come through ?

**Comment by koutcher** [comment]
Maybe there is some hope with https://github.com/neomutt/neomutt/commit/aa64ad729e722ebaa4cd132d0c6aa36b5e0a2488...

**Comment by mckelly2833** [comment]
Yea, cool, that would be the way to get them all.
I made a ~10 line hack to get the values for kDN5/kUP5 and check for those in display.c and it works well for several different terminals.  But this would get all the sequences that ncurses returns a value for that are not defined.
Should we put together a PR with this ?

**Comment by koutcher** [comment]
Some have been waiting for this since 2015 and it would make the impossible possible, so that doesn't sound like a bad idea.

**Comment by mckelly2833** [comment]
ok, I'll work on something this weekend that adds an extended_key_mappings[] and searches that also.

**Comment by mckelly2833** [comment]
ok, first attempt is here https://github.com/jonas/tig/pull/1048

**Comment by mckelly2833** [comment]
An easier way might be to just add -
```
    int i;
    for (i=KEY_MAX; i<2000; i++)
        keyok(i, false);
```
at the end of init_display().  And then use the explicit mapping:
```
bind generic   <Esc>[1;5B    scroll-line-down
bind generic   <Esc>[1;5A    scroll-line-up
```

**Comment by mgedmin** [comment]
As a user I'd much prefer being able to specify `<Ctrl-Up>` instead of `<Esc>[1;whatwasitagain?`.

**Comment by mckelly2833** [comment]
@mgedmin sure, and I agree.  It's just that sometimes a simple code change is accepted when a larger one is not and I just thought I should mention it.
It sort of makes sense in that there are extended key codes that are there, but not fully supported as-is, and so it breaks the esc-code binding method and the above removes the extended key codes.  We would really just need to make sure the version of curses used has keyok() with a check at configure/compile time.
But we can wait and see what others think of the original PR and if anything grows from that :-)
thx,
-m

**Comment by mckelly2833** [comment]
I've also added PR https://github.com/jonas/tig/pull/1049 for the much more simple way.
thx,
-m

**Comment by koutcher** [comment]
Indeed #1048 looks a bit complex... Let start with #1049 and we can improve it later if needed.
