### ISSUE TITLE
Shift+Space to scroll page up

### ISSUE THREAD

**Issue by igordovgaluk** [jonas/tig#1050]
Spacebar scrolls one page down.
Would be nice to have Shift+Space scroll one page up.

**Comment by mckelly2833** [comment]
I think it depends on what your terminal provides for Shift+Space to be able to map it.
What terminal do you use ?

**Comment by mckelly2833** [comment]
Shift+Space can be difficult, but Ctrl+Space or Alt+Space might work for you with:
```
bind generic   <Ctrl-@>             scroll-page-up
bind generic   <Ctrl-[><Space>      scroll-page-up
```
