### ISSUE TITLE
tig cli: how to pass startup commands?

### ISSUE THREAD

**Issue by d9k** [jonas/tig#1057]
Hello!

How can I pass startup commands to tig via command line (for example `set commit-title-graph = no`)?

**Comment by krobelus** [comment]
On Sat, Dec 19, 2020 at 04:26:48AM -0800, Dmitry wrote:
> Hello!
> 
> How can I pass startup commands to tig via command line (for example `set commit-title-graph = no`)?

You can set TIG_SCRIPT, see "man tig". For example

	TIG_SCRIPT=<(echo :set main-view-commit-title-graph = no) tig
