### ISSUE TITLE
Consider moving away from Travis

### ISSUE THREAD

**Issue by krobelus** [jonas/tig#1061]
Travs has gone [freemium](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). Open source projects can ask for extra build credits but [those are limited](https://news.ycombinator.com/item?id=25338983).

As a result Travis does not run on recent PRs. We could move to GitHub Actions or similar. HTH

**Comment by krobelus** [comment]
I played around a bit with GitHub Actions but ran into [problems because it doesn't allocate a TTY](https://github.com/krobelus/tig/runs/1657107799?check_suite_focus=true)

In the meantime I wrote a [simple build configuration](https://github.com/krobelus/tig-ci-integration-demo/commit/master) for https://builds.sr.ht. This service is in beta and currently free but will eventually be paid. However, it's really nice because the configuration is much simpler compared to GitHub Actions. It's trivial to convert the build manifest to a Dockerfile and reproduce the CI system locally.

Here are two demo PRs that [fail](https://github.com/krobelus/tig-ci-integration-demo/pull/1) and [passes](https://github.com/krobelus/tig-ci-integration-demo/pull/2) the sr.ht CI.

sr.ht does not offer macOS. We currently only test `brew install --HEAD`, that can done on GitHub Actions fairly easily.

**Comment by koutcher** [comment]
What about https://github.com/gfx/example-github-actions-with-tty ?
