### ISSUE TITLE
Refresh other views when tig performs some actions

### ISSUE THREAD

**Issue by hydrargyrum** [jonas/tig#1068]
When tig itself stages files or commits, the commit list is not refreshed.

Steps to reproduce:

- do unstaged changes to files
- open tig with commit log
- there is an "unstaged changes" entry above commits list
- within the same tig instance, open status view ("s" key)
- stage some files in the status view
- quit the status view
- you're now on the commits list
- **the view was unchanged, there is no "staged changes" entry in the commit list**
- go back to status view
- perform a commit from there ("C" key)
- go back to log view
- **the view was unchanged, the new commit doesn't appear**

**Comment by koutcher** [comment]
Sounds like you are using a tig version < tig-2.5.0 where this was fixed. If not, check that `refresh-mode` is not set to `manual` in tigrc.

**Comment by hydrargyrum** [comment]
Indeed I have tig 2.4.1. Sorry.
