### ISSUE TITLE
Is there a way to switch branch with Tig?

### ISSUE THREAD

**Issue by iaeiou** [jonas/tig#1076]
Hello there,

I'm discovering Tig and I really appreciate it, thanks a lot!

One feature seems to be missing: the ability to quickly checkout another branch.

The `refs view` is handy, it would be nice to have an easy way to checkout the selected branch.

A potential bonus to be able to checkout *any* commit under the cursor

I've been reading the whole manual and searched the issues and pull request, I didn't find any hint. Do you have one?

**Comment by iaeiou** [comment]
I found a way using custom commands:

    :bind generic R !git checkout %(branch)

Tig is fantastic!

**Comment by krobelus** [comment]
the default bindings also include `bind refs	C	?git checkout %(branch)`
