### ISSUE TITLE
Make func color configurable

### ISSUE THREAD

**Issue by levsa** [jonas/tig#1077]
I can't seem to find a color setting for git version of `color.diff.func` (the text to the right of `color.diff.hunk` e.g. the text to the right of `tig`'s `diff-chunk`. Is it configurable? Blue on black is not that visible 😞

**Comment by koutcher** [comment]
Try `diff-stat`.

**Comment by levsa** [comment]
Worked, thanks!

**Comment by koutcher** [comment]
That's right, thanks for reporting.
