### ISSUE TITLE
tests: emoji-test fails on Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by nmeum** [jonas/tig#1083]
I am currently trying to get the tig test suite to pass as part of the [Alpine Linux](https://alpinelinux.org) tig package. Alpine uses [musl libc](https://musl.libc.org) instead of glibc. With `tig-2.52` I can only observe a single test failure in the `./test/main/emoji-test` the test case `test/main/emoji-test:emoji-commit-titles-col-300` fails with the following error:

```
      CASE  test/main/emoji-test:emoji-commit-titles-col-300
            | Failed 1 out of 6 test(s)
            | [FAIL] emoji-commit-titles-col-46.screen != expected/emoji-commit-titles-col-46.screen
            | diff --git a/expected/emoji-commit-titles-col-46.screen b/emoji-commit-titles-col-46.screen
            | index f13b34e..1fde581 100644
            | --- a/expected/emoji-commit-titles-col-46.screen
            | +++ b/emoji-commit-titles-col-46.screen
            | @@ -1,4 +1,4 @@
            | -2009-04-06 01:44 +0000 Committer o [master] 🌏
            | +2009-04-06 01:44 +0000 Committer o [master]
            |  2009-03-28 13:22 +0000 Committer o 💄 Polish t
            |  2009-03-20 01:00 +0000 Committer o 📚 Document
            |  2009-03-11 12:38 +0000 Committer o 🎨 Reformat
            |   [OK] emoji-commit-titles-col-46.stderr assertion
            |   [OK] emoji-commit-titles-col-unset.screen assertion
            |   [OK] emoji-commit-titles-col-unset.stderr assertion
            |   [OK] emoji-commit-titles-col-300.screen assertion
            |   [OK] emoji-commit-titles-col-300.stderr assertion
```

All other tests pass successfully. I am not sure why this particular test case fails as `wcslen(L"2009-04-06 01:44 +0000 Committer o [master] 🌏")` returns `45` on both musl- and glibc-based systems. However, I am also not familiar with the tig code base at all. Any ideas what might be causing this? If possible, I would like to get this fixed in order to get the entire tig test suite to pass on Alpine.

**Comment by krobelus** [comment]
This is probably because your `wcwidth(3)` returns a different value for `🌏`. Try this:

```c
#define _XOPEN_SOURCE
#include <wchar.h>
#include <stdio.h>
#include <locale.h>

int main() {
        if (setlocale(LC_CTYPE, "en_US.UTF-8"))
                printf("%d\n", wcwidth(L'🌏')); // Should print 2.
}
```

`wcwidth` is not directly used by Tig, but by ncurses.

**Comment by nmeum** [comment]
That doesn't seem to be the problem. `wcwidth(L'🌏')` also returns 2 on musl.

**Comment by krobelus** [comment]
Right. Seems to be some issue in ncurses (possibly specific to Alpine).
Minimal reproducer:

```c
#include <curses.h>
#include <signal.h>
#include <stdlib.h>
#include <assert.h>
#include <locale.h>

static void finish(int sig);

int
main(int argc, char *argv[])
{
    char *locale = setlocale(LC_ALL, "");
    assert(locale);

    (void) signal(SIGINT, finish);      /* arrange interrupts to terminate */
    (void) initscr();      /* initialize the curses library */
 
    wresize(stdscr, 10, 4);
    werase(stdscr);
    addstr("12🌏1234");
    getch();
    finish(0);               /* we're done */
}

static void finish(int sig)
{
    endwin();
    exit(0);
}
```

Compile with `cc -lcurses`.

This should display

```
12🌏
1234
```

Yet on Alpine (alpine:edge docker image) this renders as

```
12
🌏12
34
```

**Comment by nmeum** [comment]
Interesting. Which version of ncurses are you using on your glibc-based system? Alpine uses `6.2_p20210213`.

**Comment by krobelus** [comment]
`6.2.20200212` - which also works on Alpine. Looks like an ncurses regression. I'll bisect and report there.

**Comment by krobelus** [comment]
The issue was introduced in ncurses 6.2 patch 20210130 in [ncurses/base/lib_addch.c](http://ncurses.scripts.mit.edu/?p=ncurses.git;a=blobdiff;f=ncurses/base/lib_addch.c;h=7c9e407c6aa6495fccde7a5982607089964c65c4;hp=604b13be8cec16bab2f9242b0006ffe988455b06;hb=5d5daf53864fdb666df16c82c3710025cf119e9d;hpb=4546e76f7d630a849ac9e17deda7bee36919f800)

Reported as https://lists.gnu.org/archive/html/bug-ncurses/2021-02/msg00007.html, so this issue can be closed I guess.

**Comment by nmeum** [comment]
Sure. Thanks for looking into it!
