### ISSUE TITLE
%(branch) evaluate for a custom command

### ISSUE THREAD

**Issue by mckellygit** [jonas/tig#1086]
Hi,
I use a custom command wrapper -
```
bind status  Mu   @tmux_popup_wrapper git merge --signoff --ff-only upstream/%(branch)
```
This pops a terminal and runs the cmd provided.
But it does not seem to be evaluating the %(branch) - it is always empty.
I will go looking - but just a question - doesn't the evaluation always happen before running any command ?
thx for awesome tig,
-m

**Comment by koutcher** [comment]
You would have better luck in the refs view I think... From there you could use %(refname) which contains both the remote and the branch name.

**Comment by mckellygit** [comment]
Thanks so much.  I agree refs is better and %(branch) works there.  I will try %(refname).
Closing.
