### ISSUE TITLE
eats all memory and goes into swap

### ISSUE THREAD

**Issue by svpv** [jonas/tig#1087]
Recently I upgraded from tig-2.5.0 to tig-2.5.2. I can no longer view big commits: tig eats up all memory and goes into swap.

Steps to reproduce:
1) Clone e.g. [this repo](http://git.altlinux.org/people/at/packages/0ad.git).
2) In another terminal, run `top` and press `M` to sort by memory usage.
3) In yet another terminal, prepare `killall tig`.
4) Run `tig --all` and position to the second to last commit, the one with `0ad-0.0.24b-alpha-unix-build.tar.xz`.
5) Now press `Enter` to view the commit.
6) You'll only have a few seconds to peek at `top` and execute `killall tig`. After those few seconds, you won't be able to abort tig gracefully, it'll send the whole machine into swap.

The problem is exacerbated by the fact that tig traps signals. So by the time you realize that `C-C` doesn't work, and you want to open another terminal, it's already too late. I think it must be possible to trap signals in such a way that the first arrival resets the handler, so that the second `C-C` is a sure-fire way to kill the program.

I think I was able to bisect the problem to 484aa21a6f9ec6090a78b111eb429f9d922e25b9.

**Comment by koutcher** [comment]
Thanks for reporting. To avoid the loop until we have a fix, the workaround is `set wrap-lines                  = no`. The problem is not with the size of the commit, the offending character is `©` in `0ad/build/premake/premake5/binmodules/luasocket/LICENSE0ad/build/premake/premake5/binmodules/luasocket/LICENSE`. It doesn't show even with 2.5.0 and as, since 2.5.2, wrapping is checking for multibytes characters, it causes the loop.

**Comment by krobelus** [comment]
The file is encoded ISO-8859 and we likely try to read it as UTF-8.
In UTF-8, the `©` would be `c2a9`.

Related: `.gitattributes` supports configuring [encoding](https://www.git-scm.com/docs/gitattributes#_working_tree_encoding), but apparently supports ISO-8859 out of the box.

**Comment by koutcher** [comment]
@krobelus, with the following, LICENSE doesn't loop anymore, but mime.html still does. We have some translation in place when showing the blob view but we don't have any when reading the output of git show in the diff view. Maybe we need some kind of sanitizing...
```patch
diff --git a/src/string.c b/src/string.c
index 2638d92..3e8f7d9 100644
--- a/src/string.c
+++ b/src/string.c
@@ -313,7 +313,7 @@ utf8_length(const char **start, int max_chars, size_t skip, int *width, size_t m
 		unicode = utf8_to_unicode(string, bytes);
 		/* FIXME: Graceful handling of invalid Unicode character. */
 		if (!unicode)
-			break;
+			unicode = '?';
 
 		ucwidth = unicode == '\t' ? tab_size - (*width % tab_size) :
 					    utf8proc_charwidth((utf8proc_int32_t) unicode);
```

**Comment by krobelus** [comment]
The fix looks good.
I haven't been able to reproduce a loop with mime.html.
Maybe it's enough to make utf8_length more robust, so it always makes progress regardless of input.
If other places are affected, a separate sanitization step might make more sense.

**Comment by koutcher** [comment]
I definitely still have the loop with mime.html (make sure you have `set wrap-lines = yes`). I managed to avoid it by checking if the string contains valid UTF-8 and by using the old string_expanded_length() if it doesn't.
