### ISSUE TITLE
Line navigation changed between 2.5.1 and 2.5.2

### ISSUE THREAD

**Issue by balta2ar** [jonas/tig#1090]
In 2.5.1 after I maximized Unstaged (`T` in my settings), I could move up and down one line at a time with Up and Down keys. In 2.5.2 these keys switch next/previous commit instead (my settings staying the same).

**Comment by koutcher** [comment]
This was the original tig behaviour (before 2.4.0) that was restored in 2.5.2. If you use `d` (in the default bindings), you will have the behaviour you expect.

**Comment by balta2ar** [comment]
Awesome, thank you!
