### ISSUE TITLE
Question: tig show commit for current line

### ISSUE THREAD

**Issue by simon-lang** [jonas/tig#1092]
Thanks for this project it is fantastic

Right now I use `:Gblame` to see a blame panel then copy the hash into `:Tig show e93dfa3791` to see the full commit.

Is there a way to do this directly with this tool, or through a vim script?

I really like how `:Tig!` shows entire history for this file - this is sort of similar.

**Comment by koutcher** [comment]
Tig has a blame view that you could use directly: `tig blame <filename>ˋ.
