### ISSUE TITLE
tig diff: lines starting by "--" are not colored correctly 

### ISSUE THREAD

**Issue by firmart** [jonas/tig#1099]
Normally, in tig diff buffer, removed lines and inserted lines are respectively red and green. However, when the removed line starts by "--", the line is colored in blue. 
![Screenshot from 2021-04-08 01-31-45](https://user-images.githubusercontent.com/20540328/113947764-abd72d00-980b-11eb-924a-4ad04041a284.png)

**Comment by koutcher** [comment]
This was fixed in tig-2.5.0 (see a080208).

**Comment by firmart** [comment]
Oops, forgot to check the version and testing the newest one. Thanks!
