### ISSUE TITLE
include/tig/tig.h:93:22: fatal error: curses.h

### ISSUE THREAD

**Issue by caraortizmah** [jonas/tig#1106]
After cloning tig through git and setting in that folder, when I type 'make' it returns some warnings and the following error:
> (...)
> include/tig/tig.h:93:22: fatal error: curses.h No such file or directory
> compilation terminated.
> Makefile:380: recipe for target 'src/tig.o' failed
> make: *** [src/tig.o] Error 1

**Comment by koutcher** [comment]
Maybe you should check [Installation using configure](https://github.com/jonas/tig/blob/master/INSTALL.adoc#installation-using-configure) and [Tools and packages.](https://github.com/jonas/tig/blob/master/INSTALL.adoc#tools-and-packages)
