### ISSUE TITLE
Is it possible to bind Ctrl-Home, aka ^[[1;2H?

### ISSUE THREAD

**Issue by psprint** [jonas/tig#1109]
Hi,
I'm having a problem, as neither of two:
```
bind generic <Esc>[1;5H move-first-line
bind generic <Ctrl-Home> move-first-line
```
are working… Any tips of binding `Ctrl-Home` key combination? `cat -v` shows that it's:

```
# cat -v
^[[1;5H
```

So, basically an escape, a bracket [, then chars: "1;5H" like in the `<Esc>[1;5H`, which doesn't work - while it should, apparently.

Is it possible to bind `<Ctrl-Home>`? It's a very well established termcap entry, I'm using it with Midnight Commander all time…

**Comment by mckellygit** [comment]
Hi,
I have in my .tigrc -
```
bind generic   <Esc>[1;5H   move-first-line
bind generic   <Esc>[1;5F   move-last-line
```
and these work ok for me.
Do you have mappings of other esc sequences in your .tigrc file that work ok ?
What version of tig do you have and what version of curses do you have and did you build tig yourself ?
thx,
-m
