### ISSUE TITLE
How to build static binary for linux?

### ISSUE THREAD

**Issue by Tony2** [jonas/tig#1112]
Hi,

I use tig on some linux servers which run old debian, and the tig version from apt is very dated. Is it possible to build static binary for tig from sources, so that I can just copy it to the servers and start tiging?

**Comment by koutcher** [comment]
Provided that you have installed static libraries, `./configure LDFLAGS=-static; make` will produce a static binary.

**Comment by Tony2** [comment]
I tried that on debian streatch and get some linking errors that I don't know how to fix. Can you please give a hint?

```
       .
       .
       CC  compat/utf8proc.o
      LINK  src/tig
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `_nc_mouse_event':
(.text+0x605): undefined reference to `Gpm_GetEvent'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xca5): undefined reference to `Gpm_Close'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xcef): undefined reference to `Gpm_Open'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `enable_gpm_mouse':
(.text+0xd00): undefined reference to `Gpm_Close'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `_nc_mouse_init':
(.text+0xe5d): undefined reference to `gpm_fd'
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libncurses.a(lib_mouse.o): In function `mouse_activate':
(.text+0x104b): undefined reference to `gpm_fd'
collect2: error: ld returned 1 exit status
Makefile:377: recipe for target 'src/tig' failed
```

**Comment by koutcher** [comment]
Looks like your ncurses library has some additional dependencies. Try `./configure LIBS=-lgpm LDFLAGS=-static`.

**Comment by Tony2** [comment]
Thanks for the hint.

I tried that (and `apt install libgpm-dev` before running configure). Same error. Tried with a few versions of debian and ubuntu, and it seems to work on buster (without `LIBS=-lgpm`).
