### ISSUE TITLE
How to change coloring for selected line?

### ISSUE THREAD

**Issue by avatar-lavventura** [jonas/tig#1114]
I am using [dracula-theme][1] in my terminal. In Tig selected line is unreadable:

example screenshot:

[![enter image description here][2]][2]

Is it possible to change the selected line's background color to improve readability?

  [1]: https://github.com/dracula/iterm
  [2]: https://i.stack.imgur.com/FedII.png

**Comment by avatar-lavventura** [comment]
`color cursor            black   yellow bold` solved my problem.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/18537398/121038250-cf413880-c7b8-11eb-92ce-a4283c46b8fc.png">

**Comment by FightingBoom** [comment]
Practical operation sharing. In the .tigrc file under the user root directory, enter the following configuration:
```shell
color cursor black yellow bold
```
