### ISSUE TITLE
Is it possible to open tig with HEAD entry selected?

### ISSUE THREAD

**Issue by avatar-lavventura** [jonas/tig#1116]
Is it possible to open tig with HEAD entry selected, where it will show the diff on the right-hand side right away?

----------

When I type `tig`, list of commits in order are viewed; 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/18537398/121043985-cef76c00-c7bd-11eb-9ef4-e3dbce25cfee.png">

Than when I do enter I can see the diff on the right hand side window:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/18537398/121044080-e8001d00-c7bd-11eb-9bba-834ea1012203.png">

I just want `tig` to open along with the diff windows right away.

Would it be possible when I run `tig` ; it will also show the diff on the right hand side without I am entering enter?

**Comment by krobelus** [comment]
On Mon, Jun 07, 2021 at 08:28:45AM -0700, Alper Alimoglu wrote:
> Is it possible to open tig with HEAD entry selected, where it will show the diff on the right-hand side right away?
> 
> I just want `tig` to open along with the diff windows right away.
> 
> Would it be possible when I run `tig` ; it will also show the diff on the right hand side without I am entering enter?

You can use something like

	TIG_SCRIPT=<(echo :enter) tig

("man tig" has a similar example)

**Comment by avatar-lavventura** [comment]
@krobelus Thanks this is golden

**Comment by avatar-lavventura** [comment]
@krobelus 
Minor question related to this: Can focus on the diff window? Where I want to apply defualt keybinding for page-down/page-up on the  diff window side.

**Comment by krobelus** [comment]
On Mon, Jun 07, 2021 at 01:52:36PM -0700, Alper Alimoglu wrote:
> @krobelus 
> Minor question related to this: Can focus on the diff window? Where I want to apply defualt keybinding for page-down/page-up on the  diff window side.

You can cycle focus with ":view-next", which is bound to "Tab" by default.
This and other bindings are listed on the help view, which is bound to "h"

**Comment by avatar-lavventura** [comment]
@krobelus Thanks! I am not sure but `TAB` (`Ctrl-i`) does not do anything, even I have `bind generic    <Tab>   view-next` on my configuration :(
