### ISSUE TITLE
How to force to overwrite defualt keybindings

### ISSUE THREAD

**Issue by avatar-lavventura** [jonas/tig#1118]
I am having following warning message:

```
tig warning: ~/.tigrc:17: Key binding for previous and scroll-line-up conflict; keys using Ctrl are case insensitive
tig warning: ~/.tigrc:18: Key binding for next and scroll-line-down conflict; keys using Ctrl are case insensitive
```

due to following lines:

```
bind generic    <C-p>   scroll-line-up
bind generic    <C-n>   scroll-line-down
```

Is it possible to for to overwrite the default keybindings without having the warning message?

Should I suppress the warning messaging doing following:

`TIG_SCRIPT=<(echo :enter) tig 2>/dev/nul`

**Comment by koutcher** [comment]
Considering the warning given by Tig and the fact that the built-in tigrc has C-P and C-N in capital, I would try:
```
bind generic    <C-P>   scroll-line-up
bind generic    <C-N>   scroll-line-down
```

**Comment by avatar-lavventura** [comment]
@koutcher  Does `<C-P>` stands for `cntrl-shift-p`?

**Comment by koutcher** [comment]
@avatar-lavventura, I believe it wouldn't be too hard to try it for yourself... But, no it doesn't, all bindings in the default tigrc are written in capital and you don't need to hold the Shift key to use them. I'm not sure either Tig could support a Ctrl-Shift mapping.
