### ISSUE TITLE
feature: how to support "git --author <name>" in tig 

### ISSUE THREAD

**Issue by xxlnx** [jonas/tig#1120]
the --author is very useful command option in git.
how to support this option in tig application?
eg:
tig --author "Kevin"

**Comment by krobelus** [comment]
> tig --author "Kevin"

that already works

**Comment by koutcher** [comment]
tig --author="Kevin"

**Comment by xxlnx** [comment]
> tig --author="Kevin"
it is working, I missed '=' .
