### ISSUE TITLE
There is tig package available in dnf.

### ISSUE THREAD

**Issue by lngsx** [jonas/tig#1121]
Tig is available in Fedora official repo.
Just report here. I don't know if you guys have a plan to put it to the doc already.

**Comment by jasontibbitts** [comment]
For the record, tig has been a part of Fedora for 14 years now....

**Comment by lngsx** [comment]
For the record, I've spent some time installing nix just to install tig before discovering I can do it solely by dnf....

Not everyone is a pro-Linux user that happens to knows everything before they have to learn.
