### ISSUE TITLE
allow log format date

### ISSUE THREAD

**Issue by delanym** [jonas/tig#1122]
Tig does not accept "--date=short" etc. This would be especially helpful (removes 12 chars) when in split view since the number of horizontal chars is quite limited.

**Comment by koutcher** [comment]
If you change `date:default` to `date:default,format="%Y-%m-%d"` in the `set main-view` line of your `.tigrc`, you'll be able to toggle to the short format with the `D`key. Use `date:custom,format="%Y-%m-%d"` if you want to start with the short format.
