### ISSUE TITLE
Staging single line out of 2-line change results in wrong order

### ISSUE THREAD

**Issue by mbirth** [jonas/tig#1124]
Imagine this hunk:

```diff
 $cmd  = '"D:\\htdocs\\Streaming\\Live_to_VoD\\startBGProcess.cmd" ';
-$cmd .= '"C:\\Program Files (x86)\\XAMPP_7.2.11\\php\\php.exe" -f "D:\\htdocs\\Streaming\\Live_to_VoD\\VoD-Grabber.php"
-$cmd .= ' -- title="' . $downloadName . '" in=' . $startDate . ' out=' . $endDate . ' stream=' . $streamId . ' token='
+$cmd .= '"C:\\xampp\\php\\php.exe" -f "D:\\htdocs\\Streaming\\Live_to_VoD\\VoD-Grabber.php"';
+$cmd .= ' -- title="' . $downloadName . '" in=' . $startDate . ' out=' . $endDate . ' stream=' . $streamId . ' token='
 //$cmd .= ' >NUL 2>NUL';
```

Now I want to only stage the lines with `C:\\....`, so I select them and press 1. What ends up in the "Changes to be committed" list is this, though:

```diff
 $cmd  = '"D:\\htdocs\\Streaming\\Live_to_VoD\\startBGProcess.cmd" ';
-$cmd .= '"C:\\Program Files (x86)\\XAMPP_7.2.11\\php\\php.exe" -f "D:\\htdocs\\Streaming\\Live_to_VoD\\VoD-Grabber.php"
 $cmd .= ' -- title="' . $downloadName . '" in=' . $startDate . ' out=' . $endDate . ' stream=' . $streamId . ' token='
+$cmd .= '"C:\\xampp\\php\\php.exe" -f "D:\\htdocs\\Streaming\\Live_to_VoD\\VoD-Grabber.php"';
 //$cmd .= ' >NUL 2>NUL';
```

Here, the changed line is going to be inserted below the to-be-kept line and thus mixing up the order.

Is that something you can fix in tig or some weird behaviour of git?

**Comment by koutcher** [comment]
I would bet on the second option because there is something strange with your original hunk: the second line is identical so it has no reason to appear both in the - and + sections. Messing with end-of-lines ?

**Comment by mbirth** [comment]
Yeah, probably, but even then, the same issue would occur if there was textual content in that line.
