### ISSUE TITLE
how to use custom diff command in diff view (it currently works but requires pressing a key)

### ISSUE THREAD

**Issue by timotheecour** [jonas/tig#1129]
following https://kparal.wordpress.com/2020/12/16/show-a-side-by-side-git-diff-on-any-commit-in-tig-using-meld/ (and adapting it) I've adding this to `$XDG_CONFIG_HOME/tig/config`:
```
bind main w !git diff %(commit)^!
bind diff w !git diff %(commit)^!
```
which allows me to at least use custom git diff options to view diffs in tig by pressing `w`.

My question is, how do i get that same custom git diff options to apply without having to press a key?

**Comment by pablospe** [comment]
Also interested on this. It would be nice to replace the default view-diff by delta (side-by-side diff):
https://github.com/dandavison/delta

Would that be possible with the `tig/config`?

**Comment by pablospe** [comment]
related PR: https://github.com/jonas/tig/pull/1140

**Comment by pablospe** [comment]
I would close this issue, it is duplicated:
https://github.com/jonas/tig/issues/542
