### ISSUE TITLE
Make grep view display search results from selected commit instead of work tree

### ISSUE THREAD

**Issue by victor-yarema** [jonas/tig#1130]
The `git grep` command allows caller to specify a tree-ish argument. In that case the search is performed against the tree inferred from that argument instead of work tree. For example the command `git grep -e "$Pattern" "$CommitId"` searches for "$Pat" in a tree that is being referenced by commit with id "$CommitId".
From what I see in the code, `tig` doesn't support this when switching to or updating grep view using a prompt in TUI. Here are arguments which are prepared for a `git grep` command:
https://github.com/jonas/tig/blob/529182c4d0081ebe9774cd1cb4d7e298946808af/src/grep.c#L89-L91
In case of TUI prompt only pattern is being added if I'm not mistaking.
It would be nice if user could issue a `git grep` command against the commit which is being selected. Currently I am thinking about commit selection in main view but there can be other places.

**Comment by koutcher** [comment]
Have you tried to put the commit id after the the pattern at the `grep:` prompt ?
