### ISSUE TITLE
"git add" is slow when using tig with large repositories.

### ISSUE THREAD

**Issue by takehaya** [jonas/tig#1141]
hi. 
thanks for cool  "tig".I use it every day.
I recently started using it in a large repository, but only git add is quite slow.
Is there any way to speed this up?

thanks.
*  version
```
$ git --version
git version 2.30.2.windows.1
$ tig -v
tig version 2.5.2
ncursesw version 6.2.20200212
readline version 8.1
```

**Comment by koutcher** [comment]
Is `git add` faster when run outside of Tig ?
