### ISSUE TITLE
[Bug] Tig has no color under xterm-256color

### ISSUE THREAD

**Issue by JokeNeverSoke** [jonas/tig#1150]
When I set `$TERM` to `xterm` tig shows colors, but not when `TERM=xterm-256color`. It used to work in the past. I'm using iTerm.

https://user-images.githubusercontent.com/45055133/134767459-2872fc68-f353-40b8-a53b-63e26dd34b84.mp4

**Comment by johnlockhart** [comment]
@JokeNeverSoke I see this problem, too. iTerm2 just put out a new release 3.5.0beta1 on 2021-09-25, and they mention "Add support for various control sequences that affect colors" in the changelog. It seems likely it's a regression or some new interaction weirdness in iTerm2, rather than tig.

**Comment by joeygibson** [comment]
I have the same problem on _one_ of my Macbook Pros. Both are running iTerm2 3.5.0beta1 and tig 2.5.4. It works on one, but not the other. Both have `TERM=xterm-256color` set. Very strange.

**Comment by johnlockhart** [comment]
I can confirm that rolling back to [iTerm2 3.4.10](https://iterm2.com/downloads.html) restores colors to tig. It's an [iTerm2 problem](https://gitlab.com/gnachman/iterm2/-/issues) with 3.5.0beta1, or possibly something in my environment is causing iTerm2 3.5.0beta1 to not work. I have the problem with other curses apps so I'm pretty sure it's not tig.

**Comment by JokeNeverSoke** [comment]
I've rewinded my iTerm2 version and tig is functional. Never occurred to me that all this time my tig was colorless since I was on the iTerm2 nightly channel (Darkmode YES!).

Closing this issue since the iTerm2 repo has already raised a [relevant issue](https://gitlab.com/gnachman/iterm2/-/issues/9951).
