### ISSUE TITLE
Tig suddenly displaying in greyscale

### ISSUE THREAD

**Issue by booc0mtaco** [jonas/tig#1153]
Hello, 

I recently noticed something odd with my tig setup. Without any changes, everything started displaying in greyscale. This was without any recent changes to my ~/.tigrc, and before and after an upgrade to the latest version.

```
# Main View Settings - relative dates and user names, with visual graph
set main-view =  line-number:no,interval=5 id:no date:default author:full commit-title:yes,graph=v2,overflow=100

# Diff View Setting - show line numbers
set diff-view = line-number:yes,interval=1 text:yes,commit-title-overflow=no

# Blame view - show linenumbers and dates like in the main view
set blame-view = id:yes,color file-name:auto author:email-user date:relative line-number:yes,interval=1 text
set blob-view = line-number:yes,interval=1 text

# Use graphics for the branching display
set line-graphics = utf-8

# use automatic splitting algorithm
set vertical-split = auto

# Mouse setup
set mouse = yes
set mouse-scroll = 3
set mouse-wheel-cursor = yes
```

When i `mv` the config out of the way, it changes settings, but still shows in grey scale. Other terminal outputs (`git log`, `git diff`) continue to show colors, as do other commands. It's just `tig` for some reason...

also
```bash
$ echo $TERM
xterm-256color
````

I have **2.5.4** installed. Any ideas why this may have started happening?

**Comment by gordolio** [comment]
In case more people stumble here. This is likely due to a recent iTerm2 update. It works properly in Terminal.

https://gitlab.com/gnachman/iterm2/-/issues/9951

**Comment by koutcher** [comment]
Fixed a month ago in iTerm2. Assuming everyone has updated by now.
