### ISSUE TITLE
Terminal colors change when foregrounding

### ISSUE THREAD

**Issue by amarshall** [jonas/tig#1156]
1. `reset`
2. Change a terminal color via escape code (this may vary by Terminal) e.g. `printf '\033]4;%d;rgb:%s\033\\' 6 "ff/00/00"` to change the cyan to red (to be obvious) (for more see e.g. [this script](https://github.com/chriskempson/base16-shell/blob/ce8e1e540367ea83cc3e01eec7b2a11783b3f9e1/scripts/base16-solarized-dark.sh))
3. `tig` (I’ve run with `TIGRC_USER=/dev/null`, so default config)
4. Note the colors
5. Background tig <kbd>Ctrl</kbd>+<kbd>z</kbd> (colors are still correct)
6. Foreground tig `fg`
7. Note that the color set in ② (and observed in ④) has been reset to its default as in ①
8. Quit tig, colors are still incorrect as in ⑦

tig version 2.5.4, ncursesw version 6.2.20200212, readline version 6.3. I’ve seen this behavior in Kitty, Alacritty, and foot, so it does not appear to be specific to a given terminal emulator. However, I do not see it occur in tmux.

**Comment by amarshall** [comment]
More information. It seems to be dependent on the terminfo in use. If I use e.g. `TERM=xterm tig` the issue does not occur, whereas with e.g. `TERM=xterm-256color tig` it does. Running strace I have found the culprit escape sequence to be `\33]104\7` which gets interpreted (per alacritty_terminal’s VTE parser) as resetting colors 0 through 255. Given this it probably only occurs when the terminal indicates it supports 256color. This happens shortly after SIGCONT:

```
--- SIGTSTP {si_signo=SIGTSTP, si_code=SI_USER, si_pid=2139226, si_uid=1000} ---
--- stopped by SIGTSTP ---
--- SIGCONT {si_signo=SIGCONT, si_code=SI_USER, si_pid=1676736, si_uid=1000} ---
rt_sigaction(SIGTSTP, {sa_handler=0x7f1864ca60f0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f1864adfc40}, NULL, 8) = 0
ioctl(1, TCFLSH, TCIFLUSH)              = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f1864adfc40}, {sa_handler=0x7f1864ca60f0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f1864adfc40}, 8) = 0
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=73, ws_col=159, ws_xpixel=1908, ws_ypixel=2044}) = 0
ioctl(1, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost -isig -icanon -echo ...}) = 0
write(1, "\33[?1049h\33[1;73r\33[?25l", 21) = 21
write(1, "\33[39;49m\33]104\7\33(B\33[m\33[4l\33[?7h\33[?1000h", 37) = 37
write(1, "\33[H\33[2J\33[30m\33[42m 0 second ago"..., 9676) = 9676
rt_sigaction(SIGTSTP, {sa_handler=0x7f1864ca60f0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART, 
```

I’ve traced this to happening in ncurses’ `handle_SIGTSTP` where it calls `NCURSES_SP_NAME(doupdate) (NCURSES_SP_ARG);`. However, removing that does not help since tig calls `doupdate()` in its `get_input()` loop shortly afterwards, anyway.

I’m uncertain if this is an ncurses or tig issue.

**Comment by koutcher** [comment]
I don't think we can do anything in tig, ncurses is doing all the work when handling SIGSTP. The problem could be also your terminfo definition. Have you tried with TERM=alacritty, terminfo.src seems to have a specific rs1 value for it.

**Comment by amarshall** [comment]
Yea, digging some more I now have an MRE with a simple ncurses program. So I’ll report the issue upstream and close here, though any additional insight is certainly welcome.

> Have you tried with TERM=alacritty

Yea, the `TERM=xterm-256color` was just an example, my original testing with Alacritty, Kitty, etc. is all with their respective proper terminfo.
