### ISSUE TITLE
Hiding refs by pattern (to reduce git-branchless spam)?

### ISSUE THREAD

**Issue by nyanpasu64** [jonas/tig#1160]
Installing git-branchless has resulted in it labeling large numbers of commits with meaningless refs which clutter the tig view. Is it possible to hide certain refs from tig by a regex/glob pattern?

![Screenshot_20211026_180119](https://user-images.githubusercontent.com/913957/138982527-edd72f22-1af9-41cb-8e77-1078afcda4d6.png)

I looked at https://jonas.github.io/tig/doc/tigrc.5.html#_variables, and it seems the closest you can get is `hide:`, but you can't hide branches and unknown refs separately, nor can you hide `refs/stash` and `refs/branchless` separately if you want.

**Comment by koutcher** [comment]
We could also introduce a new reference category `other` to allow the use of `set reference-format = hide:other` to hide these references which aren't heads, tags, branches...
