### ISSUE TITLE
Status line is inaccurate when changing line-graphics

### ISSUE THREAD

**Issue by gareth** [jonas/tig#1163]
When I change line graphics mode by pressing `~`, the status line reports the change:

![image](https://user-images.githubusercontent.com/4975/141461075-f164888f-238f-49f7-99e4-a27d4eadab8b.png)

However, if I actually try to use this configuration command, either directly in the app (via `:set main-view-line-graphics = …`) or via a config line in `.tigrc`, I'm given the error message `Failed to parse view column type: …`:

![image](https://user-images.githubusercontent.com/4975/141461111-2189515a-7e90-4ef3-9c7f-9321b0324fe1.png)

Instead, I'm able to get this working by setting the config key `line-graphics`, but as a very casual user I don't know if I'm intended to be able to do it both ways.

**Comment by koutcher** [comment]
Thanks for reporting the issue. This is a regression of 80b40c2 in 2.5.0.
