### ISSUE TITLE
commit-title=refs doesn't show any refs?

### ISSUE THREAD

**Issue by nedbat** [jonas/tig#1177]
I'm sure I'm just misunderstanding something, but I expected to be able to see tag and branch names in main view with this setting:
```
set main-view = line-number:no,interval=5 id:yes date:default author:abbreviated,maxwidth=20 commit-title:yes,graph,refs,overflow=no
```
This is what I see:
```
61eb339 2022-01-18 13:33 -0500 NBatchelder   ∙ build: use reusable pr-automerge-open-release workflow
6ac87f6 2022-01-18 12:27 -0500 NBatchelder   ∙ temp: debug the auto-merge workflow
0e50f2e 2022-01-17 17:29 +0200 MSokolski     ●─╮ Merge pull request #882 from CUCWD/ztraboo.maple.master/fix-backport-node-mozjpeg
f61adcc 2021-12-02 19:33 -0500 PShiu         │ ∙ Merge pull request #865 from edx/pshiu/add-zlib-to-devstack
152f51c 2021-10-13 16:54 -0400 KMcCormick    ∙─╯ chore: upgrade coursegraph's neo4j image from 3.2 to 3.5 (#824)
082b8e3 2021-10-13 12:53 +0500 erbot         ∙ chore: Updating Python Requirements (#842)
```
My git log looks like this:
```
* 61eb339 2022-01-18 (HEAD -> open-release/maple.master, origin/open-release/maple.master) build: use reusable pr-automerge-open-release workflow Ned Batchelder
* 6ac87f6 2022-01-18 temp: debug the auto-merge workflow Ned Batchelder
*   0e50f2e 2022-01-17 Merge pull request #882 from CUCWD/ztraboo.maple.master/fix-backport-node-mozjpeg Max Sokolski
|\
| * f61adcc 2021-12-02 Merge pull request #865 from edx/pshiu/add-zlib-to-devstack Phillip Shiu
|/
* 152f51c 2021-10-13 (tag: open-release/maple.1, origin/open-release/maple.beta2, origin/open-release/maple.beta1) chore: upgrade coursegraph's neo4j image from 3.2 to 3.5 (#824) Kyle McCormick
* 082b8e3 2021-10-13 chore: Updating Python Requirements (#842) edX requirements bot
```
Is there something else I need to do to get the ref names displayed in the main view?

**Comment by krobelus** [comment]
Works for me (with and without your `main-view`).
Do the references show up when you run the default configuration? Something like

        TIGRC_SYSTEM= TIGRC_USER=/dev/null tig

You might have set a `reference-format` (see `man tigrc`) that excludes tags/branches
The default is

        set reference-format		= [branch] <tag> {remote} ~replace~

To exclude tags we can write `hide:tag`. Maybe you did that?

The `main-view` setting is probably irrelevant.

**Comment by nedbat** [comment]
The environment variables were a good tip.  I had this set:
```
TIG_LS_REMOTE=ls-remote-grep -v release-candidate
```
When I remove that, the refs come back.  TBH, I'm not even sure what "ls-remote-grep" is or was. It seems to fail silently running it, which means no refs are shown.

**Comment by krobelus** [comment]
> It seems to fail silently running it, which means no refs are shown.

we should probably die if `load_refs()` fails. We already die in one place but not in others; I'm not sure why.
