### ISSUE TITLE
How to start `tig refs` with `sort-field=date`

### ISSUE THREAD

**Issue by simon04** [jonas/tig#1179]
I find `tig refs` very helpful to review the latest branches. More so when they are sorted by  `sort-field=date` and `sort-order=descending`. Is there a way to configure `tig refs` to always sort by date descending?

Thank you!

**Comment by krobelus** [comment]
I didn't check the source but I believe the sorting is hardcoded.
Though you can filter refs with TIG_LS_REMOTE, so something like this might work:

        TIG_LS_REMOTE='sh -c "git for-each-ref --format=\"%(objectname) %(refname)\" --sort=-committerdate | head"' tig refs

**Comment by koutcher** [comment]
Unfortunately, it is not yet possible to configure the default sort field/order, see #408.
