### ISSUE TITLE
tig window flickers

### ISSUE THREAD

**Issue by jirislaby** [jonas/tig#1180]
Very often, it happens that the tig window flickers or show half screen old+half screen new content. This happens especially when paging (pg-up, pg-down) through history or patch.
If I run for example this in the linux kernel:
```
tig v5.16-rc1..v5.16
```
I see this:
![start](https://user-images.githubusercontent.com/530775/151509949-61065b6a-7f7a-411a-b1aa-446e6096f91b.png)
Then, if I navigate through it, I see:
https://user-images.githubusercontent.com/530775/151510043-2aab187f-516c-46f4-9b89-1495e4d02a03.mp4

I don't know if this is tig's, curses, compositor (plasma on wayland), or gfx driver (i915 -- KMS) issue. However, I don't see it with any other app (incl. kernel's menuconfig, vim, less -- the latter two seem to use only tinfo, not curses).

**Comment by koutcher** [comment]
Have you tried with a different terminal emulator ?

**Comment by jirislaby** [comment]
@koutcher right, happens only in xterm which I use. In, konsole, does not reproduce.

**Comment by koutcher** [comment]
@jirislaby, the flickering on your video looks a bit like some double-buffer artefact, maybe you can confirm with strace if tig is doing something while it happens. Tig is using some optimisation tricks (see init_display() in src/display.c), you could try to unset `XTERM_VERSION` and try with `TERM_PROGRAM` set either to `gnome-terminal` or `Apple_Terminal` to see if one helps.

**Comment by jirislaby** [comment]
Wow:
```sh
unset XTERM_VERSION
export TERM_PROGRAM=gnome-terminal
tig v5.16-rc1..v5.16
```
The issue is gone, the same as with:
```sh
unset XTERM_VERSION
export TERM_PROGRAM=Apple_Terminal
tig v5.16-rc1..v5.16
```
For confirmation, the issue is back with:
```sh
export XTERM_VERSION='XTerm(370)'
tig v5.16-rc1..v5.16
```

**Comment by jirislaby** [comment]
It's also slightly problematic over ssh. `XTERM_VERSION` is not sent by default. Only these are (`TERM` is documented in ssh's man):
```sh
$ env|grep TERM
COLORTERM=1
TERM=xterm-256color
```
So the detection above doesn't work there too.

**Comment by koutcher** [comment]
I tried to reproduce the original issues with xterm and gnome-terminal on a venerable RHEL 4 and couldn't succeed, so I think it is not unreasonable to believe we can now remove these hacks safely.
