### ISSUE TITLE
tig status not aligned with git status

### ISSUE THREAD

**Issue by obotor** [jonas/tig#1181]
Hi
I have been doing some clean-up locally.
I happen to be on feature/ir-665.
And I am now in a state (after a git pull --rebase origin develop) where tig finds some indexed files and git only sees untracked files (which is supposed to be the real world).
`> $ git status                      [±feature/ir-665 ●]`
`On branch feature/ir-665`
`Untracked files:`
`  (use "git add <file>..." to include in what will be committed)`
`	../docker/local/db.sql`
`	overrides/`
``
`nothing added to commit but untracked files present (use "git add" to track)`
``
From tig's point of view the landscape is quite cluttered...
`Initial commit`
`Changes to be committed:`
`A .env.properties`
`A .circleci/conf/kt.tar.gz`
`A .circleci/conf/setenv.sh`
`A .circleci/config.yml`
`A .gitignore`
`A Dockerfile.ext`
`A README.md`
`A build.gradle`
`...`
`Changes not staged for commit:`
`  (no files)`
`Untracked files:`
`? docker/local/db.sql`
`? modules/overrides/override/src/main/java/com/test/Main.java`

I found the situation quite intriguing especially when considering the table head in tig status reads "Initial commit" which is the comment of said commit, like 2 years ago and some 800 commits ago.

Is there any way to "reset" tig?

Thank you

**Comment by krobelus** [comment]
>`Initial commit`

Something similar happens when running `TIG_LS_REMOTE=true tig status`

Can you check the git commands with `TIG_TRACE=my-trace-file tig status`

It's probably something in your configuration, either a TIG_* environment variable or something else in your configuration.
If yes, this should work

	env -i TERM=$TERM HOME=$(mktemp -d) tig status

**Comment by obotor** [comment]
Hi!
Thank you for your hint.
I found the problem. It amounts to having 2 feature branches with names only differing by case...
Note that I am working under Apple MacOSX (M1).
For better understanding, you will find the traces below.

In feature/ir-665 (not working):
`git rev-parse --git-dir --is-inside-work-tree --show-cdup --show-prefix HEAD --symbolic-full-name HEAD`
`git config --list`
`git show-ref --head --dereference`
`git update-index -q --unmerged --refresh`
`git ls-files -z --cached --exclude-standard`
`git diff-files -z`
`git ls-files -z --others --exclude-standard`

In feature/IR-665 (working):
`git rev-parse --git-dir --is-inside-work-tree --show-cdup --show-prefix HEAD --symbolic-full-name HEAD`
`git config --list`
`git show-ref --head --dereference`
`git rev-list --left-right feature/IR-665...origin/feature/IR-665`
`git update-index -q --unmerged --refresh`
`git diff-index -z --diff-filter=ACDMRTXB -C --cached HEAD --`
`git diff-files -z`
`git ls-files -z --others --exclude-standard`

I infer from these that the feature/ir-665 branch is a ghost and it cannot resolve its stem, hence tig is going back to the root commit...

Thank you.
