### ISSUE TITLE
tig view versus log view

### ISSUE THREAD

**Issue by kaihendry** [jonas/tig#1184]
When I open tig, I see a list of commits, but I've come to notice that it's not the same view as say `git log --abbrev-commit --pretty=oneline`! What's the difference?

I tried playing around with `--first-parent` & `--no-merges` but it's not quite the same. I suspect the git log is different because it's showing some replayed git commits from a merged branch, but tbh I am very confused as to the difference in the git view here.

**Comment by koutcher** [comment]
Did you play with `:toggle commit-order` ?
