### ISSUE TITLE
Emoji unicode characters make the rest of the line disappear

### ISSUE THREAD

**Issue by nidico** [jonas/tig#1186]
Emoji characters in git commit messages make the rest of the corresponding lines disappear.

For example have a look at the commit messages in the https://github.com/tiangolo/fastapi repo:

Display in `tig log`:

![fastapi-tig-log](https://user-images.githubusercontent.com/457147/164945096-a9f98c5f-e8f1-419a-8b27-c65850bc8fd9.png)

Whereas `git log` shows:

![fastapi-git-log](https://user-images.githubusercontent.com/457147/164945097-833b5f2d-68e7-4055-b6ac-47b1f25ce92d.png)

It seems that only the remainder of the line is hidden, as can be seen in the following manifactured example:

`tig log`:

![emoji-unicode-tig-log-broken](https://user-images.githubusercontent.com/457147/164946161-b962a517-db8f-4d18-951b-3d52dca7bf62.png)

`git log`:

![emoji-unicode-git-log](https://user-images.githubusercontent.com/457147/164946162-816561ab-beea-4855-af63-e37934c2a1fe.png)

**Comment by krobelus** [comment]
works for me with ncurses 6.3. What's your version and OS?
I think on some distribution you need ncursesw or similar to handle non-ASCII characters.
Also the output of `locale` might be useful to confirm that you're using a unicode locale.

**Comment by nidico** [comment]
Oops, I was working with an outdated local copy of tig from 6 years ago (2.0.2) which was in the path with a higher priority than the installed tig version from packages (2.5.5). On 2.5.5 everything is fine (using packages from Debian testing btw).

Sorry for the noise! And looking forward for the "new stuff" ;)
