### ISSUE TITLE
Command to show commits that changed a specific word

### ISSUE THREAD

**Issue by weichuliu** [jonas/tig#1188]
I am trying to search the git history that contains a certain word change.

For example

```
git log --full-diff -p -S instance_type
```

This shows me all commits and diffs that the regex `instance_type` has been modified. (from [Stackoverflow](https://stackoverflow.com/questions/1337320/how-to-grep-git-commit-diffs-or-contents-for-a-certain-word))

What will be the corresponding command in `tig` to do the same thing?

**Comment by koutcher** [comment]
`tig -Sinstance_type`. Make sure there is no space between -S and argument.

**Comment by weichuliu** [comment]
Yes! That's what I'm trying to find! Thank you!
