### ISSUE TITLE
Some locales seem to totally confuse tigs drawing algorithm

### ISSUE THREAD

**Issue by Vampire** [jonas/tig#1196]
A log that looks perfectly fine using `LANG=en_US.UTF-8 tig` with all line graphics,
looks totally borked with `LANG=en_DE.UTF-8 tig`.
There are characters where they don't belong until refreshed, some characters are totally misdisplayed, the utf-8 line graphics are totally wrong, the length calculations for properly drawing the lines are wrong:
![grafik](https://user-images.githubusercontent.com/325196/172651994-f6a6651e-87fb-4b65-8f3c-f14add6d4a7e.png)
![grafik](https://user-images.githubusercontent.com/325196/172652211-770bebde-fdd5-42c7-b3b0-3d5299685109.png)
With `LANG=en_US.UTF-8 tig` it looks properly.
![grafik](https://user-images.githubusercontent.com/325196/172652681-0b95e6de-49a1-4026-a54f-fca07833f3c1.png)
![grafik](https://user-images.githubusercontent.com/325196/172652787-3d3d9ddc-69df-4b6f-95dc-ee4e640941dd.png)

**Comment by koutcher** [comment]
You are using KDE I presume. Even though it let you use `en_DE.UTF-8`, the locale is valid only if it was compiled on your system. This can be checked with `locale -a`.

**Comment by Vampire** [comment]
No, I use Git Bash from Git for Windows as I'm forced onto Windows at work.
But you are right, that locale is not in the `locale -a` list.
If that is a pre-requisite, that's obviously the reason, sorry.
