### ISSUE TITLE
Document which regex dialect is used

### ISSUE THREAD

**Issue by Vampire** [jonas/tig#1201]
Please document which regex dialect is used.
For example when searching with `/`.

**Comment by koutcher** [comment]
When using `configure`, PCRE2 is tried first, then PCRE1. When Tig is compiled with PCRE support, `tig -v` shows the PCRE version, so no luck in your case, you're left with POSIX ERE.

**Comment by Vampire** [comment]
Maybe you could contribute this change to Git for Windows? :-)
You know your build best and what to change so that it has PCRE support.
Here is mentioned which file would need to be edited: https://github.com/git-for-windows/git/issues/3889
