### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by Vampire** [jonas/tig#1202]
Please support case insensitive search with `/` and `?`.
I tried with `(?i)asdf`, but it seems you are using a regex dialect that does not support mode modifiers.

**Comment by koutcher** [comment]
`(?i)` is supported if Tig was compiled with PCRE support.

**Comment by Vampire** [comment]
@hydrargyrum I don't want always case-insensitive.
I want by default case-sensitive, but to be able to easily disable it per search.

@koutcher how was it completed?
Did you introduce a way to do it? :-)

**Comment by cweiske** [comment]
A config option would be really nice to permanently enable case insensitivity. Please reopen.

**Comment by hydrargyrum** [comment]
@cweiske to permanently do it, just `set ignore-case = yes`, see https://jonas.github.io/tig/doc/tigrc.5.html

**Comment by cweiske** [comment]
thanks. I did not know this was already implemented and thought your first comment was a suggestion how this could be implemented.
