### ISSUE TITLE
Feature request – a view with a terminal window?

### ISSUE THREAD

**Issue by psprint** [jonas/tig#1203]
Would it be hard to add view-terminal, that would provide a view with a terminal (embedded), like e.g.: in Vim (`:terminal` to open it)? Would be a patch providing such support be accepted?

**Comment by koutcher** [comment]
Quite hard yes. Tig was built as an enhanced pager, it runs some commands, captures the output and displays it. To support a terminal view, you'd need to create a pty and interact with it. Tig's prompt handling, especially the readline integration would have to be completely rewritten.
