### ISSUE TITLE
Question about view-blob implementation 

### ISSUE THREAD

**Issue by psprint** [jonas/tig#1206]
View-blob has currently problems with input - backspace and cursors do not work. 

I looked at the source and the input is realized via prompt_incremental_input(). However it seems that the function is designed to read key combos, ie the commands that are then checked against bindings. 

That would explain the limited editing support. Am I right?

**Comment by psprint** [comment]
via a key shortcut bound to view-blob

czw., 23 cze 2022, 19:38 użytkownik Thomas Koutcher <
***@***.***> napisał:

**Comment by koutcher** [comment]
Have you redefined the generic mapping for arrow keys ?

**Comment by psprint** [comment]
Yes:
```

**Comment by psprint** [comment]
Here is another cast with backspace / find file: debugging:

    https://asciinema.org/a/gFdzfc0P4khmNoQAMEsXy2XCt

**Comment by psprint** [comment]
I have established a few facts: it is true that the `read_prompt_incrmental()` path is distinct from regular `read_prompt()` path in that the first one is used by combo-reading and `Find file:` (`view-blob`) view, while the second by the `:`-prompt.

The `read_prompt_incremental()` path  is using `get_input()` to read the key. And it isn't recognizing `^H` as backspace, only `^?`, as it has revealed from the following test binding:

```
bind main <Backspace> view-blob
```

Pressing backspace doesn't yield any reaction only the unknown key message, while pressing `Ctrl-Shift-?` (or `Ctrl-Shift-/` to be more correct) does open the expected `view-blob` view.

So, how to make `get_input()` see `^H` as backspace?

**Comment by koutcher** [comment]
Tig relies on ncurses which in turn relies on terminfo. I'd check the consistency of the TERM variable with the kind of terminal.

**Comment by psprint** [comment]
My TERM is `xterm-256color` and it's the original, unmodified value set by `xterm` itself. So it turns out that xterm support is little broken? For view-blob? As other inputs, namely the `:…` prompt does correctly handle backspace? Also, it's a long time that I've seen backspace to be `^?`, everybody use `^H`, so why tig expects `^?` in this single place?

**Comment by koutcher** [comment]
Tig doesn't expect anything, all is performed within ncurses based on the terminfo database. If Tig was compiled with readline support, it explains why you observe a different behaviour with the prompt. The value used for backspace depends on the terminal configuration and XTerm itself may use `^?` or `^H` depending on resources like ptyInitialErase and some others. `stty erase` must match this setting. There is nothing that can be done at Tig level.

**Comment by koutcher** [comment]
No, backspace works well on xterm provided that kbs entry in terminfo database matches xterm configuration. The default kbs for xterm in terminfo database from ncurses source code is indeed `^H` but, for example, Red Hat ships with a patched xterm entry with `kbs=\177` (`^?`) to match `*VT100*backarrowKey: false` in app-defaults. Wether it's a good or a bad thing is out of the scope of Tig.
