### ISSUE TITLE
Word diff doesn't work for unstaged changes

### ISSUE THREAD

**Issue by majutsushi** [jonas/tig#1207]
When enabling the `word-diff` option the diffs of normal commits are displayed as expected, with the changed words highlighted. However when looking at unstaged changes in the `stage` view, the highlighting completely disappears instead, not even line-wise highlighting is shown. Since the stage view is one of the most useful places to have word diffs it would be great if that could be supported as well.

**Comment by koutcher** [comment]
Good catch. This will be easy to fix, however note that you won't be able to stage chunks (with `u`) when viewing word-diff as the patch is required for this.

**Comment by majutsushi** [comment]
That's okay, it's easy enough to switch between modes with a keyboard shortcut. I wonder if it would be possible to change the `u` behaviour to switch modes automatically before and after applying a patch, but that may be too tricky to get right.
