### ISSUE TITLE
tig_history should be in ~/.local/state/tig_history by default

### ISSUE THREAD

**Issue by itaranto** [jonas/tig#1208]
`tig` *does not* fully respect the XDG directory specification, by default it writes its history to `~/.tig_history`.

By default it should be `~/.local/state/tig_history` (or `~/.local/share/tig_history`), the user *shouldn't* need to do any extra configuration like creating the file beforehand of setting any of the XDG variables.

**Comment by koutcher** [comment]
Full XDG compliance was not the intent. We have done as much as we are willing to do for now to make it possible for those who want their history stored following the XDG specification without forcing the others to do so.

**Comment by peterhoeg** [comment]
Specifically the storage of history is broken ref #1215
