### ISSUE TITLE
%(lineno) broken in custom bindings for the blame view

### ISSUE THREAD

**Issue by pspacek** [jonas/tig#1209]
Version affected: 13bcb402230a3ff7e668966cda9e5d125711a4d4

No matter what I try the `%(lineno)` expansion for "blame" view custom binding always returns value "9".

### Reproducer
Configuration:
```
bind blame e !/tmp/test.sh %(commit) %(file) %(lineno)
```

Script `/tmp/test.sh`:
```
#!/bin/bash
COMMIT="$1"
FILE="$2"
LINENO="$3"

echo $COMMIT
echo $FILE
echo $LINENO
```

Command:
```
tig blame src/ui.c
```
Now press `e` while standing on the first line of blame view.

test.sh output:
```
395611ebf13cbcebee1791b5c9d81ef2c6823475
src/ui.c
9
```
Huh?

I tried to move the cursor to a different line but number 9 stays there. Valgrind does not complain about uninitialized memory.

**Comment by koutcher** [comment]
Valgrind is a bit overkill here, a simple `:!echo %(lineno)` would have been enough to let Tig off the hook. test.sh is the one to blame here, you can't use `LINENO` for a variable name, see `bash(1)`.

**Comment by pspacek** [comment]
Thank you very much - and my apologies! I did not suspect Bash builtin :facepalm:
