### ISSUE TITLE
Tig Colors Are Missing Inside Tmux

### ISSUE THREAD

**Issue by IanEdington** [jonas/tig#1210]
Thanks for this awesome programme. I use it daily!

I've lost color in tig 😭

I'm using `TERM=tmux-256color` because it fixes some italic and true color issues I was having with `screen-256color`.

here's some debug info that was asked on another issue:

```
> infocmp | head -2
#       Reconstructed via infocmp from file: /Users/ian/.terminfo/74/tmux-256color
tmux-256color|tmux with 256 colors,

> infocmp | grep -e smcup -e rmcup
        ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
        sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
```

I'm currently using `alias tig="TERM=screen-256color tig"` but I'd rather have it work properly with the TERM I have.

**Comment by IanEdington** [comment]
Thank you! Yes I used a custom version of `xterm-256color` and it worked fine. I had to change to a standard terminfo so tried a couple others but `tmux-256color` seems to be the best option. The only issue I've found with `tmux-256color` is the `tig` color.

**Comment by koutcher** [comment]
Beside the header that tells us that your `tmux-256color` is actually not a standard one, the interesting line in your infocmp output would be the one with `pairs`. macOS stock ncurses version does not handle `pairs#0x10000` or `pairs#65536` and so far Homebrew maintainers have refused to use a newer version of ncurses, so the only option we're left with is to use a patched terminfo.

Try
```
/usr/local/opt/ncurses/bin/infocmp -x tmux-256color | sed -e 's/pairs#0x10000/pairs#32767/' -e 's/pairs#65536/pairs#32767/' > tmux-256color.src
/usr/bin/tic -x tmux-256color.src
```
Note that the latest tmux version in Homebrew has been modified to use `screen-256color`, but unfortunately this terminfo is also broken, at least on 10.11, so you will probably have to do the same to get a working one.

**Comment by IanEdington** [comment]
Unfortunately, that didn't work.

It sounds like I have a non-standard tmux-256color definition. I got it from invisible-island.net so I thought it would work.
Do you know where I should get terminfo definitions if they aren't included on my system or is that generally not a good idea?

Since this is an issue with my setup, I'll close this ticket.

Thanks for the help!

**Comment by koutcher** [comment]
invisible-island.net is just fine, you have to replace the pairs#10000 as well to use it with macOS ncurses version. You may want to try starting with an empty ~/.terminfo as it has more precedence than the system one.

**Comment by IanEdington** [comment]
For anyone who comes later this helped a lot:

https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/

@koutcher, your comment about pairs makes a lot more sense now. Thanks
