### ISSUE TITLE
Question about defaults vs toggles

### ISSUE THREAD

**Issue by shmup** [jonas/tig#1212]
I quite like getting thinner columns on the "default view" (whatever you call the view right when you run tig), and I was wondering what control you have over customizing this particular view. Specifically, is there a way to default the view to what I'm achieving by manually toggling `A` and `D` as seen in this screenshot?

And while I have y'all here, what about adusting the width of the columns on this view? I've read the example tigrc but my tests weren't producing the result I tried. Such as, for example, setting a particular column's maxwidth. An example of that would be stellar, too.

<img width="553" alt="Screen Shot 2022-07-13 at 9 43 24 AM" src="https://user-images.githubusercontent.com/118710/178748332-5b5ac1b1-628d-42ae-bc71-a4166744526d.png">

**Comment by koutcher** [comment]
After using the toggles to configure the display as you wish, you can use `:save-options options.txt` to generate the corresponding `tigrc`. [The default tigrc](https://github.com/jonas/tig/blob/master/tigrc) documents quite well the use of maxwidth option, in particular the columns to which it can be applied.

**Comment by shmup** [comment]
Wow, `:save-options` is a very cool feature I overlooked. Appreciate it, and pointing me towards a default tigrc to examine. I'll close this issue.
