### ISSUE TITLE
Refresh `status view` with status view shortcut `s`

### ISSUE THREAD

**Issue by deniciocode** [jonas/tig#1214]
As a user I would like to keep my `status view` open and refresh the page by pressing `s` to update new files in the view.

**Comment by Daghall** [comment]
Press `h` to open the help view. Use `/` to search.
Refresh is bound to `R` and `F5`, respectively, as in seen there.

The exact feature you want can easily be achieved by adding the following to your `.tigrc`:
```
bind status s :refresh
```

`man tigrc` for more info.

**Comment by deniciocode** [comment]
@Daghall thank you very much and thank you for the info. I did not know about `.tigrc`

**Comment by Daghall** [comment]
No, problem @deniciocode. 😄
For some inspiration you can take a look at [the defaults](https://github.com/jonas/tig/blob/master/tigrc) and [my `.tigrc`](https://github.com/Daghall/dotfiles/blob/master/.tigrc).
