### ISSUE TITLE
`tig status` throws `Encoding failure` for unstaged files with very long lines (>2048 chars)

### ISSUE THREAD

**Issue by MaxWinterstein** [jonas/tig#1227]
When having very long lines in a file, and trying to use `tig status` the preview of a file breaks when it contains long lines (>2048).

Running on a recent Intel MacBook, installed via brew.

```bash
tig -v
tig version 2.5.6
ncursesw version 6.3.20211021
readline version 8.1
```

Reproduction:

```bash
echo 'short line - you should see me' > test.txt
echo -n "freaking long line - i break things" {1..600} >> test.txt
echo '' >> test.txt
echo 'another short line - can you see me?' >> test.txt
```

`tig status` with `test.txt` untracked:

![image](https://user-images.githubusercontent.com/5927148/182374312-38c959f5-f13d-466c-b1d4-5f6cd77f0aa3.png)

`tig status` with `test.txt` added:

![image](https://user-images.githubusercontent.com/5927148/182374390-7db1e8bd-198a-411e-aa09-3a41d6ef0cf3.png)

Having the line not shown in full might be okay, but dying and not displaying the following rows lead to some confusion here 😉

**Comment by koutcher** [comment]
Thanks for reporting the issue. Indeed encoding failures should be reported but not fatal.
