### ISSUE TITLE
[BUG] %(text) isn't set in status view, resulting in a problem

### ISSUE THREAD

**Issue by psprint** [jonas/tig#1230]
Hi,
I would like to configure tig so that patches are colorized when displayed. I select the patches comfortably in status view, but they aren't by default processed nor colorized in the pager view that opens them. Solution could be the following binding:

```
bind status <Enter> <zsh -c 'cat %(text) | tig'
```

However the `%(text)` var is substituted to an empty string. I see this as a general bug, not only a bug for this particular use case – `%(text)` should be set as it is also in other views, like the pager view (`%(text)` is there set to the current highlighted line).

**Comment by koutcher** [comment]
The manual is a little ambiguous here, one should read `%(text)             The text *column* of the currently selected line.`
In the status view, there is no text column. In this case you want to use `%(file)`.

**Comment by psprint** [comment]
You're right `%(file)` works. Closing this but check out a Tig Suite announcement: #1251.
