### ISSUE TITLE
"Not a git repository", in a git repository (with a commit)

### ISSUE THREAD

**Issue by xparq** [jonas/tig#1232]
(See also #451 and #445. Sorry those who saw the notifis. of my earlier sleep-deprived, half-baked, and then deleted, comments there; I ended up submitting this instead.)

~~~~
Z:\transit\tig>git log
commit 1b1177fd8fae6b352b06c2f359bd5233825cb2e0 (HEAD -> master)
Author: ...
Date:   Fri Sep 2 18:15:29 2022 +0200

    crap

Z:\transit\tig>[...path\to\portable\git\]\usr\bin\tig
tig: Not a git repository

Z:\transit\tig>[...path\to\portable\git\]\usr\bin\tig -v
tig version 2.5.7
ncursesw version 6.3.20211021
readline version 8.1
PCRE2 version 10.40 2022-04-14

Z:\transit\tig>git -v
git version 2.37.3.windows.1
~~~~

(`tig` and `git` both from the same `PortableGit-2.37.3-64-bit.7z` package. So, there was no install, whatsoever.)

What am I missing? Is `tig` not supposed to be invoked via its direct executable path, perhaps? (Note: `git` was invoked via a proxy `git.cmd` on the `PATH` that just forwards the call to `[...path\to\portable\git\]\cmd\git.exe`, hence the different command lines.)
Thanks!

**Comment by koutcher** [comment]
Sounds like tig doesn't find the `git` command (I don't think it is able to use the proxy `git.cmd`) and an error in the initial `git rev-parse` is interpreted as not being in a valid git repository.
