### ISSUE TITLE
chinese font display is not correct in detail windows

### ISSUE THREAD

**Issue by jiftle** [jonas/tig#1236]
![image](https://user-images.githubusercontent.com/10773495/190118266-ba2ccfe7-d73f-4e2a-8e56-811a34b2e0a0.png)

![image](https://user-images.githubusercontent.com/10773495/190118449-60d0ed54-50de-4488-b34c-0b60d3c32175.png)
![image](https://user-images.githubusercontent.com/10773495/190118556-d36deb4e-7335-4732-bdda-20f897571881.png)

**Comment by koutcher** [comment]
You may try with `git config --global core.quotepath false`.

**Comment by jiftle** [comment]
> You may try with `git config --global core.quotepath false`.

thank u , it's work.
