### ISSUE TITLE
start `tig blame somefile` on given line

### ISSUE THREAD

**Issue by pkitszel** [jonas/tig#1237]
It would be perfect to have an option to open tig blame view on specific line, instead of begining of file.
Prefferably, by adding :number at the end, as is typicaly done for code editors, grep output, and so on.

**Comment by krobelus** [comment]
you can use
    
		dir=$(git rev-parse --show-toplevel)
		tig -C "$dir" blame -C +123 -- "${FILENAME##$dir/}"

`+<number>` (here +123) is a Tig-specific option, it works great for blame

**Comment by pkitszel** [comment]
Thanks @krobelus !

I have made a bash alias for that, `tb`:

    function tb() {
    	__=${!##*:}
    	set -- +$((${__////})) "${@:1:${#}-1}" "${!#%:*}"
    	tig blame "$@"
    }
