### ISSUE TITLE
[feature] only show a specific set of user provided revisions 

### ISSUE THREAD

**Issue by ryenus** [jonas/tig#1244]
### Problem
Tig is really great at presenting an interactive repository view, but compared to git, it lacks the abundant options of possible ways to filter the revisions to be displayed, like the options in `git revisions` and `git log`. 

Especially when working with large repositories where it's difficult for tig to load and present all the commits.

### Expected
I'd like to have git produce a list of filtered reviews and use it as input for tig, so that tig only include the provided revisions for user interaction

E.g.:
- `git log -G "<keyword>" --format="%h" | tig`
- `echo -e "commit-1\ncommit-2" | tig`

**Comment by krobelus** [comment]
> Especially when working with large repositories where it's difficult for tig to load and present all the commits.

usually you want to select an interesting commit range, for example `tig @{u}@{1}..` ("everything since the previous fetch of the upstream branch")

> git log -G "<keyword>" --format="%h" | tig

tig accepts most options accepted by git log.
So you can run `tig -Gkeyword`

> echo -e "commit-1\ncommit-2" | tig

not sure if this is possible but rarely needed in practice. You can do `tig commit-1 -1` and `tig commit-2 -1`

**Comment by ryenus** [comment]
@krobelus thank you for looking into this.

I just checked and `tig -Gkeyword` indeed works, too bad that I only tried `tig -G keyword` and it didn't :-(, which I would expect it should work the same :-)

Meanwhile given `tig -Gkeyword` works, it means that internally tig can already take a list of commits and shows exactly the selected commits, tig seems to achieve that by internally executing the `git log -Gkeyword` to get the list of matching commits. 

I guess what I'm asking for is something equivalent, that is to allow the list of commits to be provided via stdin or maybe via a command line option. That's what I mean by `echo -e "commit-1\ncommit-2" | tig`, to explain such idea.

**Comment by krobelus** [comment]
> I guess what I'm asking for is something equivalent, that is to allow the list of commits to be provided via stdin or maybe via a command line option. That's what I mean by echo -e "commit-1\ncommit-2" | tig, to explain such idea.

you're in luck, you can do 

   echo -e "commit-1\ncommit-2" | tig --stdin

**Comment by ryenus** [comment]
@krobelus, thank you!, however I tried `tig --stdin` but it seems to work differently:

1. basically `tig -G<keyword>` works as expected, it just shows the commits that matches `-G<keyword>` criteria.
2. but with `git log -G<keyword> --format='%h' | tig --stdin` or `echo -e "commit-1\ncommit-2" | tig --stdin`, tig would only pick **the first commit** and present the commit history from that point, and dropped all other provided commits except the first one.

Maybe I could just move away and happily take the first approach, by passing the git CLI options to tig (with adaptation) to get what I expect. while be careful that:

1. Possibly not all git CLI options can be used for tig, or with some trick required, such as `tig -G<keyword>` vs. `tig -G <keyword>`, where the seemingly harmless extra space is not allowed in tig.
2. One might need to pre-process the commits list before passing to tig, especially in cases where one might need to load the same commits into tig multiple times, like reusing the same input for multiple tig invocations.
3. Performance wise, if tig can be told to just load the specified commits, then it doesn't have to process the commit history at all, which probably would save lots of performance overhead with large repositories, like [vscode](https://github.com/microsoft/vscode) or [linux](https://github.com/torvalds/linux).

**Comment by krobelus** [comment]
sorry it should be

    echo -e "commit-1\ncommit-2" | tig show --stdin

(as per the man page)

**Comment by ryenus** [comment]
Problem solved, actually this works:

```sh
echo -e "commit-1\ncommit-2" | tig --no-walk --stdin
```

Here `tig --no-walk --stdin` does the trick that I expect, thank you!
