### ISSUE TITLE
Bug: Scrolling with ] in a diff causes the window to close

### ISSUE THREAD

**Issue by jgarte** [jonas/tig#1245]
Holding down `]` to scroll in a diff window causes the window to close so I'm forced to repeatedly press `]` to scroll instead of just holding it down.

I'm using
```
 tig --version
tig version 2.5.6
ncursesw version 6.2.20210619
readline version 8.1
```

screenshot of the view in which it happens:

![image](https://user-images.githubusercontent.com/47760695/201529616-323a7b07-f9db-48b7-a888-4dd6bad49889.png)

**Comment by krobelus** [comment]
`]` doesn't really scroll but rather increase the diff context by one.
It recomputes the entire diff which can be expensive.

A proper fix would be to add debouncing logic: recomputing the diff should happen in the background, and each new press of `]` would cancel any old operation and start a new one.
Not sure if this is easy to implement. It should be if we are willing to accept a slim possibility of race conditions.
