### ISSUE TITLE
Bugfix: smart-case search does not work with numbers in the string

### ISSUE THREAD

**Issue by JC-WV** [jonas/tig#1246]
Any search containing numbers turns "ignore-case" from "smart-case" into "no" e.g. looking for some code like cb7a would not find CB7A when ignore-case is set to smart-case. This might be related with a previous issue where strings containing space characters did not work:
https://github.com/jonas/tig/pull/1108

**Comment by koutcher** [comment]
#1108 was fixed in 2.5.4, which version do you have ?
