### ISSUE TITLE
.tigrc not loaded on Windows

### ISSUE THREAD

**Issue by wuxb45** [jonas/tig#1248]
I have .tigrc under C:\Users\<username>\.tigrc, right next to .gitconfig but tig does not seem to load the .tigrc.
Is it supposed to be somewhere else?

**Comment by koutcher** [comment]
Tig is looking for `~/.tigrc` and `~` is a synonym for `HOME`, maybe try to define `HOME` as `%USERPROFILE%`.

**Comment by wuxb45** [comment]
@koutcher Thank you.
