### ISSUE TITLE
Feature Request: If `$XDG_DATA_HOME` exists, autocreate `$XDG_DATA_HOME/tig/`

### ISSUE THREAD

**Issue by alichtman** [jonas/tig#1258]
I have my `XDG` vars set up:

```bash
$ echo $XDG_DATA_HOME
/home/alichtman/.local/share
```

But `tig` still uses `~/.tig_history` to store history.

```
$ ll ~/.tig_history
.rw------- alichtman alichtman 5 B Fri Jan 27 2023 08:19:23 AM  /home/alichtman/.tig_history
```

I have to manually create `$XDG_DATA_HOME/tig` if I want the history file to stop cluttering up `~`. Would be nice if `tig` did this for me.

**Comment by koutcher** [comment]
Make sure you are using 2.5.7 and your variable is exported.
