### ISSUE TITLE
ability to customize the message of %(prompt)

### ISSUE THREAD

**Issue by Avinash-Bhat** [jonas/tig#1263]
a simple message would suffice here.

Consider the setup:

`bind refs <Ctrl-P> !?git push %(prompt) %(branch)`

typing Ctrl+P in the reference view, will ask for prompt with message `Command argument: `
this can be confusing for some less used commands.

If we can provide the argument name in the prompt say like: 

`bind refs <Ctrl-P> !?git push %(prompt:remote) %(branch)`

and have it prompt with a message: `Command argument 'remote':`  it would be very clear.

PS: This also would help me in dropping the `?` from the above setup as I won't need to review the final command.

**Comment by koutcher** [comment]
Already implemented in d81958e3a7b2c5623c17a892329cf11d8730808e.
