### ISSUE TITLE
"fatal: could not read <wrong home path>/.stCommitMsg" when attempting to commit from tig

### ISSUE THREAD

**Issue by bsrz** [jonas/tig#1272]
## Issue

Unable to commit from tig.

```zsh
fatal: could not read '/Users/ben/.stCommitMsg': No such file or directory
Press Enter to continue
```

Because `ben` isn't my username.
Is there a way to configure this? If not, maybe this is bug?

**Comment by koutcher** [comment]
This message is from Git, not from Tig. Check your Git configuration, especially `commit.template`.

**Comment by bsrz** [comment]
gah, you're absolutely right 🤦‍♂️
Not sure how long that config has been there, or which other app added it. And why has no other app complained about it... 

In any case, problem fixed.
Thanks for the help!
