### ISSUE TITLE
pinentry-curses compatibility

### ISSUE THREAD

**Issue by slve** [jonas/tig#1274]
While pinentry-curses renders properly when trying to preview a commit that contains gpg files,
on input the keycodes are passed through down to tig preventing the user to enter their passphrase.

My stable yet very suboptimal workaround for now as follows.
```
diff --git a/src/display.c b/src/display.c
index b2fe8b9..a6dcf2b 100644
--- a/src/display.c
+++ b/src/display.c
@@ -45,7 +45,7 @@ static struct io script_io = { -1 };
 bool
 is_script_executing(void)
 {
-	return script_io.pipe != -1;
+	return script_io.pipe != -1 || system("pgrep pinentry-curses > /dev/null") == 0;
 }
 
 enum status_code
```

**Comment by koutcher** [comment]
Have you tried with `GPG_TTY` environment variable set with `export GPG_TTY=$(tty)` prior to starting Tig ?
