### ISSUE TITLE
Error when executing `:!git commit --amend`

### ISSUE THREAD

**Issue by MartyLake** [jonas/tig#1285]
In `tig`, executing `:!git commit --amend` tries to call EDITOR, in my case vim, but fails, displaying

>vim input is not a from terminal
>vim output is not from terminal

after that, `tig` is unresponsive and I have to close this terminal and open a new one.

Is there a way to call `git commit --amend` from tig that does not suffer from this issue ?

**Comment by krobelus** [comment]
On Tue, Jun 13, 2023 at 10:45:05AM -0700, Matthieu Talbot wrote:
> In `tig`, executing `:!git commit --amend` tries to call EDITOR, in my case vim, but fails, displaying
> 
> >vim input is not a from terminal
> >vim output is not from terminal
> 
> after that, `tig` is unresponsive and I have to close this terminal and open a new one.

confirmed. We could probably loan the tty to the subprocess here.

> 
> Is there a way to call `git commit --amend` from tig that does not suffer from this issue ?

meanwhile you can do

	bind generic aca !git commit --amend

or

	bind generic aca >git commit --amend

**Comment by MartyLake** [comment]
Thanks for the `bind` trick!

**Comment by koutcher** [comment]
As per `man tigmanual` you want to do `:exec !git commit --amend` to leave the tty to the subprocess.
