### ISSUE TITLE
Terminal mouse focus reporting glitching tig since ncurses 6.4-20230514

### ISSUE THREAD

**Issue by liskin** [jonas/tig#1292]
[ncurses 6.4-20230514](https://github.com/ThomasDickey/ncurses-snapshots/commit/b9f9d6304f6abd71a5fdbfd500a645e521edf8b6) unconditionally [enables focus reporting](https://github.com/ThomasDickey/ncurses-snapshots/commit/b9f9d6304f6abd71a5fdbfd500a645e521edf8b6#diff-01544c577762d3308a1d232aa7afc79acf64b9a5057f88a004df82fda89549b7R5940) in terminals supporting SGR-mouse, but tig unfortunately doesn't know how to interpret the sequences reported back to it by the terminal, so it results in [those sequences](https://github.com/ThomasDickey/ncurses-snapshots/blob/b9f9d6304f6abd71a5fdbfd500a645e521edf8b6/misc/terminfo.src#L5907C1-L5907C1) triggering key bindings such as `[` etc.:

https://github.com/jonas/tig/assets/300342/a3864f3c-b8c9-46ad-8277-cb6cb3a2ecd2

(Personally I don't think enabling focus reporting unconditionally was a good idea, but tig is the only app on my system that glitches. Others like htop work fine as long as the [xterm+focus](https://github.com/ThomasDickey/ncurses-snapshots/blob/b9f9d6304f6abd71a5fdbfd500a645e521edf8b6/misc/terminfo.src#L5905) bits are included in the terminfo definition.)

Related issues:
* https://codeberg.org/dnkl/foot/issues/1367
* https://bugs.archlinux.org/task/78585

**Comment by paul-ri** [comment]
This affects me too. No luck with the foot terminal and the suggestion to use the `foot-extra` terminfo. Nor using the latest ncurse (`6.4.20230826`) package.

Same with xterm.

I'd love to know any workaround

**Comment by koutcher** [comment]
Adding the following to your `.tigrc` should help:
```
bind generic    <Esc>[I :none                   # Ignore xterm focus events
bind generic    <Esc>[O :none
```
I'm not sure yet whether we should fix it with this simple trick or output a `\033[?1004l` to revert the focus reporting activation. Let's see first if it makes it to ncurses 6.5.

**Comment by paul-ri** [comment]
Woop woop! That makes loads of sense.

I had to be careful about what I was looking for in tig. I can go back to switching windows senselessly again

Thanks a lot : )

**Comment by koutcher** [comment]
Just wondering if this is still an issue after ncurses 6_4_20231028... Can anyone confirm ?

**Comment by liskin** [comment]
> Just wondering if this is still an issue after ncurses 6_4_20231028... Can anyone confirm ?

Not an issue any more. :tada:
Tested with the `6.4+20231118-1` that's in Debian unstable now.
