### ISSUE TITLE
Chinese (utf-8) character display problem

### ISSUE THREAD

**Issue by echoonly** [jonas/tig#1294]
Hi，
I have met a problem with the display of Chinese (utf-8) characters. The Chinese contained in the commit message or code will be displayed as a `~` symbol when viewed in tig:
![iShot_2023-08-29_17 04 01](https://github.com/jonas/tig/assets/11766632/85a6818f-eab9-4510-bdc6-914491deb017)

`git log` command output is normal:
![iShot_2023-08-29_17 17 53](https://github.com/jonas/tig/assets/11766632/cc31ade3-3604-48f8-bd35-f819b404c92c)

I checked the previous issue, which mentioned that it is necessary to link to the ncursesw to support UTF-8 character display. 
But, I have compiled tig with ncursesw using git source, `tig --version` output is:
![image](https://github.com/jonas/tig/assets/11766632/2f8f1e44-3e63-4a61-983b-a1a3db6228ce)

The compilation command:
```
make configure && ./configure --prefix=${DEST_PATH}/tig
make -j 4 && make install
```
The output related to ncursesw when the configure command is executed is:
![image](https://github.com/jonas/tig/assets/11766632/a3faec49-8e70-49ba-94e5-ce85e57e3b61)

Is there anything wrong with this process?  Thank you!

**Comment by koutcher** [comment]
The process looks correct. It seems not all characters are affected as the third and last are ok, so the problem could be somewhere else. Centos/RHEL 7 I believe, based on the libraries versions. Do you have an example of accessible repository where you see the problem ?

**Comment by echoonly** [comment]
Yes, my os is Centos 7
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core
```

> Do you have an example of accessible repository where you see the problem ?

I don't quite understand what example you need.
