### ISSUE TITLE
[Feature Request] Add a way to overwrite default git options

### ISSUE THREAD

**Issue by qleveque** [jonas/tig#1305]
Some tig options exist to overwrite the underlying behaviour of git (e.g. `diff-options`).
However, there are default parameters which cannot be modified (in the case of `diff-options`, the parameter `--patch-with-stat` will always be passed.)

Because of that, some behaviours are unexpected and differ from git.
For example `tig log -p .` would display filenames and stat, and this unexpected behaviour cannot be overwritten.

This would be great to add a tig option so that no unrequested parameters are added.

**Comment by koutcher** [comment]
For most views options are here because Tig's shortcuts rely on them. `tig log` would be the exception and we could move `--cc --stat` to `tigrc` so it could be overwritten. Until then, you still have the option to run `git log -p . | tig`.

**Comment by Whenti** [comment]
Indeed you're right, I tried to recompile tig without the forced parameter `--patch-with-stat`, and some links were broken, so it's not as simple as I thought!
Thanks for the workaround suggestion
