### ISSUE TITLE
[Question] Is it possible to show current branch name in the Title Window

### ISSUE THREAD

**Issue by mg** [jonas/tig#1306]
I am wondering if it is possible to customise with config what is shown here:

<img width="1319" alt="image" src="https://github.com/jonas/tig/assets/1972/6447ad9f-23cf-4f97-ac64-950a27c069e2">

I've looked through https://jonas.github.io/tig/doc/tigrc.5.html but haven't found a way.

**Comment by koutcher** [comment]
The Title Window is not configurable.

**Comment by mg** [comment]
Ok, thanks for the confirmation

**Comment by sim590** [comment]
~~In relation to this question, it seems that tig doesn't update the window title at all to tell the parent terminal window that it's running. It should send OSC 2 escape sequences. This is an important feature of TUI applications to let window managers distinguish terminal windows from one another. For e.g., window switcher need the title to be set to let the user find a window by title.~~

Actually, my comment is out-of-scope. I'll comment elsewhere about this.
