### ISSUE TITLE
[Error] character used in tig interface broken

### ISSUE THREAD

**Issue by gwannuu** [jonas/tig#1307]
<img width="409" alt="image" src="https://github.com/jonas/tig/assets/83270461/0eb5e5a7-7892-4648-9dfe-4cc89c992379">
Suddenly, I have this broken characters. How can i fix it?

I reinstalled tig command by `sudo apt remove tig` & `sudo apt install tig`. But tig looks same.

**Comment by koutcher** [comment]
You are using a terminal that does not allow VT100 line drawing in UTF-8 mode. PuTTY has an option for this. Another workaround is to add `export NCURSES_NO_UTF8_ACS=1` to your environment before starting Tig.

**Comment by gwannuu** [comment]
Thank you for your answer

"Actually, I use the iTerm terminal application on my M1 MacBook to connect via SSH to my Ubuntu server. However, I recently encountered a problem where the box-drawing characters were not displaying correctly on this server, even though they used to work fine. Interestingly, on another server, the box-drawing characters display normally."

I tried `export NCURSES_NO_UTR*_ACS=1` command but it seems not work
