### ISSUE TITLE
RFE: jump to hash

### ISSUE THREAD

**Issue by igalic** [jonas/tig#1317]
I would like to have a function which allows jumping directly to a diff of a specific hash.
Currently, search doesn't allow to "search" for a git commit hashes.

Ideally, I could use that to navigate to a selected hash in a commit message.

**Comment by krobelus** [comment]
not quite what you're asking but there is `:goto <SHA>` in the main view; it works if the referenced commit is found in the view (may need to use `%` or `^` to toggle any pathspec or revspec filters)

**Comment by igalic** [comment]
Aye, thank you.
I guess i wasn't able to find it myself in the help, because you can't search the help 😅

**Comment by krobelus** [comment]
after pressing `h` you can use `/` to search. But `goto` is not really discoverable there

**Comment by igalic** [comment]
yeah, the only reference i see is `H :goto HEAD`
The `:goto` command itself is not documented at all.

**Comment by krobelus** [comment]
it's in the manual, see `man tig tigrc tigmanual | less +/goto`
The help view is autogenerated from key bindings

**Comment by igalic** [comment]
thank you very much!
