### ISSUE TITLE
keybind with `+[cmd]` would not trigger view refreshing

### ISSUE THREAD

**Issue by liangkarl** [jonas/tig#1323]
Hello,

I have a question about `@` and `+`. Simply compare `@` with `+`. `bind stage co @git checkout %(file)` would trigger view refreshing automatically, but `bind stage co +git checkout %(file)` would not.

I have no idea how to output the first line of the results and refresh the view at the same time. Does anyone could help to fix the problem? Thanks!

```
       @   Run the command in the background with no output.
       +   Run the command synchronously, and echo the first
           line of output to the status bar.
```

**Comment by koutcher** [comment]
When you use `+`, the view trigger is bypassed otherwise you wouldn't see the text in the status line.

**Comment by liangkarl** [comment]
Got it.
So, it's a dependent behavior with showing text and refreshing view, right?
Is it possible to adjust the sequence like refresh view before show the text in status bar?
Since I have tried to change to `<`, '>' and '!', as well as adjust 'refresh-mode', I have no idea how to make it.

**Comment by koutcher** [comment]
You can't without code change. Try with #1324. It requires the removal a `report_clear()` call in view.c that doesn't seem to do any harm and at least doesn't fail any test but more thorough non regression testing will be needed before considering merge.

**Comment by liangkarl** [comment]
Okay, thanks a lot!
