### ISSUE TITLE
Allow binding multiple commands

### ISSUE THREAD

**Issue by liangkarl** [jonas/tig#1328]
Is it possible to bind a key with multiple command just like `tmux.conf` did?
For example, I could bind a key with two tmux commands by adding `;`.
`bind r move-window -r ';' select-layout -E	# sort the windows`
However, it seems like we could not do the same thing in `tig`.
`bind diff  -p :set diff-options = --patience ';' set diff-view = ...`

If it could be supported, I think it would be a really helpful feature. Thanks~

**Comment by koutcher** [comment]
Duplicate of #935
