### ISSUE TITLE
--stdin makes vim complaining

### ISSUE THREAD

**Issue by herrerog** [jonas/tig#1330]
When running `tig --no-walk --stdin < cherry-picks.txt` and trying to edit a file by pressing `e`, with vim, I'm getting:
`Vim: Warning: Input is not from a terminal`
This is a similar issue as in #1229 but I tried with `master` and it still happen.

**Comment by koutcher** [comment]
#1229 correction only targeted readline so it's normal it doesn't work, but I agree, the editor should to be fixed as well.
