### ISSUE TITLE
Buffer content does not disappear

### ISSUE THREAD

**Issue by maliyan** [jonas/tig#1335]
After turning down a page and exiting the tig interface, the terminal will retain part of the list data. Not sure if it's a bug

<img width="1245" alt="image" src="https://github.com/jonas/tig/assets/5624855/1db921da-2ab0-47a6-8c5f-4cbb7c788ecb">

**Comment by koutcher** [comment]
This was recently requested as a feature but it is not implemented. You get this behaviour if alternate screen is not enabled on your terminal or if your TERM variable points to a terminfo entry that doesn't have smcup/rmcup (or doesn't match your terminal).
