### ISSUE TITLE
Feature request: Shortcur for push to git[lab|hub]

### ISSUE THREAD

**Issue by Django-BOfH** [jonas/tig#1340]
I use tig very often and with pleasure, as it helps immensely in my daily work. The only thing I miss is a shortcut for a push after I have entered my commit message.

**Comment by koutcher** [comment]
You can add you own key bindings in your `.tigrc`, e.g. `bind generic P +git push`.

**Comment by Django-BOfH** [comment]
I'm using `bind generic P !git push` and it works as expected. Thanx 4 helpl!

**Comment by Django-BOfH** [comment]
I'm using `bind generic P !git push` and it works as expected. Thanx 4 helpl!
