### ISSUE TITLE
Inconsistencies in "remote" and "branch" variables

### ISSUE THREAD

**Issue by xicod** [jonas/tig#1358]
If I'm not mistaken, following this commit 3c2cdb438a42a03d3ea06c522854829db459a993 the %(branch) variable is now empty for commits that are not directly referenced.
So I had this key binding:

bind main P !git push %(remote) %(commit):%(branch)

That now stopped working.
I've changed %(branch) to %(repo:head) and got it to work again. 
What I don't understand is why %(remote) is still set?
I would expect to use %(repo:remote) instead, but that is set to 'origin/master' instead of the expected 'origin' and git fails to push.

Thoughts?

**Comment by koutcher** [comment]
Unlike %(branch), %(remote) was created with a default value when unset.

I agree that, for consistency with Git, the current %(repo:remote) should actually be named %(repo:upstream) and that %(repo:remote) should contain only the remote name.

**Comment by xicod** [comment]
Thanks!
