### ISSUE TITLE
Support "less" pager keyboard shortcuts

### ISSUE THREAD

**Issue by mrjbq7** [jonas/tig#138]
It would be nice to have `^F` scroll forward and `^B` scroll backward.

Less also supports `f` and `b` as well, but I find myself using the Ctrl sequence more often.

Great app, thanks!

**Comment by Sequoia** [comment]
+1 on making it default :)

Also `shift-space` to reverse `space` scroll behavior.

**Comment by mrjbq7** [comment]
For reference, you now have to:

```
bind generic <Ctrl-f> scroll-page-down
bind generic <Ctrl-b> scroll-page-up
```

Also, it seems ``<Shift-Space>`` doesn't work, so I'm not sure how to do that for reverse space behavior.

**Comment by vivien** [comment]
In the meantime, it would be nice to propose a new `contrib/less.tigrc` file.
Then someone would be able to source the prefered bindings, or even have bindings to easily switch between *ema^Wvim* or *less* key bindings.

**Comment by Sequoia** [comment]
Of course with 2 panes some changes to standard `less` bindings are necessary, but I'm scratching my head about why `space`/`shift-space`/`^f`/`^b` don't just work out of the box.

Is there any reason this pager should *not* use standard `less` keybindings? It would def. ease entry for many people (me included :smile:)

**Comment by jonas** [comment]
Keybindings has been added gradually over time which explains why not all of less' bindings are there, but only the one the person submitting the patch cared about.

Regarding why `Shift-Space` is not working, it might be a restriction in Ncurses. I don't remember if this is properly documented ([other than in the code](https://github.com/jonas/tig/blob/master/src/display.c#L629)).
