### ISSUE TITLE
[Feature request] Mouse support

### ISSUE THREAD

**Issue by losingkeys** [jonas/tig#157]
It'd be nice to be able to scroll/click like vim with `set mouse=a`

**Comment by andrewmchen** [comment]
Just found this feature and holyshit is it a lifesaver. Scrolling through diffs with j/k or <C-d> is so tedious. Only problem is that this feature isn't visible enough.

**Comment by sdegutis** [comment]
This doesn't seem to work in git-bash in Windows Terminal, even though it works in Ubuntu in Windows Terminal, and mouse support does work in git-bash since it works in `lazygit`.
