### ISSUE TITLE
Display commit date in the user’s local timezone

### ISSUE THREAD

**Issue by SimonSapin** [jonas/tig#162]
The tree view of tig 1.1 show the "author date" of each commit, in the timezone of that date, but does not show the timezone itself. This view is missing valuable when showing multiple commits in different timezones, and is confusing when comparing dates. But just showing timezones uses precious space and is not useful in the (common?) case where all commits are in the same timezone.

Instead, I propose converting dates in the tree view to the user’s local timezone.

**Comment by xenomachina** [comment]
For anyone else arriving here and discovering that `set show-date = local` no longer works, the incantation for modern versions of tig seems to be:

```
set main-view-date-local = yes
```
