### ISSUE TITLE
Show diffs/logs of submodule versions instead of just the hashes.

### ISSUE THREAD

**Issue by nightlyone** [jonas/tig#171]
As a  user I would like to see diffs/logs of the actual changes in submodules instead of just the hashes in order to get a better overview what really changed and what are the intentions behind it.

**Comment by pomozoff** [comment]
tig-2.2.2 (built May  7 2017)
Same here.
How it supposed to work with submodules?

**Comment by odnoletkov** [comment]
Here `--submodule` is just an option passed through to underlying git diff-generating commands. You can find how `--submodule` works in `git help show`. In particular without any value it makes diff show only summary of submodule commits. If you want full diffs from submodules, use `--submodule=diff`.
