### ISSUE TITLE
TIG_DIFF_OPTS can make tig fail to run

### ISSUE THREAD

**Issue by rchl** [jonas/tig#191]
Documentation states that one can set TIG_DIFF_OPTS to override the way diffs are displayed. So I've tried:
TIG_DIFF_OPTS="--word-diff=color" tig
but tig doesn't start with these options. It prints:
tig: No revisions match the given arguments.

I wonder if it internally depends on there being +/- characters before added/removed lines.

**Comment by avatar-lavventura** [comment]
Does `tig` support the word diff format, now?
