### ISSUE TITLE
Is there a plan for supporting `git push` operation?

### ISSUE THREAD

**Issue by larrylv** [jonas/tig#199]
Basically, I use `tig` instead of `git` everyday.

Except when I want to push my codes to remote. I have to open another tmux pane to `git push`. Since tig already supports `git commit` or `git cherry-pick`, why not support `git push`?

I think lots of tig user would be very happy about this.

**Comment by c02y** [comment]
~~~
bind status P !git push origin
~~~
always asks for password, it is weird, since I already set `postBuffer` in ~/.gitconfig to 24 hours, and in terminal, `git push` won't ask for passwd evey time, but in tig, it does.

**Comment by c02y** [comment]
> 
> 
> ```
> bind status P !git push origin
> ```
> 
> always asks for password, it is weird, since I already set 24 hours as value of `postBuffer` in ~/.gitconfig, and in terminal, `git push` won't ask for passwd evey time, but in tig, it does.

Is there anyone knowing how to fix this, this is really annoying, and I come here again.

I'll raise a new issue page for this problem.
