### ISSUE TITLE
Empty or one-line output from external commands should not create "Press ENTER" prompt

### ISSUE THREAD

**Issue by majutsushi** [jonas/tig#200]
I would like to echo a short status message after the suggested "copy revision to clipboard" binding to confirm that the command has been executed, but that requires me to hit Enter after every copy which is quite annoying. If the output is short enough to fit into one line there is no real need to prompt the user for confirmation.

**Comment by linduxed** [comment]
I'm wondering the same thing. Is there some way to echo out something to the status line at the bottom?

**Comment by edi9999** [comment]
I like that idea too

**Comment by jonas** [comment]
Me too ;).

But I would prefer it would require a special flag(suggestions are welcome)
that turns this on since capturing output could increase memory usage
considerably for verbose commands. Ideally this flag would cause the
command to be executed with stdout being a pipe from which tig can read and
simply remember the last line.

**Comment by edi9999** [comment]
Maybe something like :

`bind generic 9 <@ sh -c 'echo "copied"'`

The `<` meaning take the output from that command to tig.

**Comment by edi9999** [comment]
I think that's how it works also with the confirm flag with `?@`

**Comment by edi9999** [comment]
Any update on this ?

**Comment by jonas** [comment]
Didn't get around to working on this, yet.

On Mon, Jun 22, 2015 at 7:48 AM, Edgar Hipp <notifications@github.com>
wrote:

> Any update on this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/200#issuecomment-114076420>.
>



-- 
Jonas Fonseca

**Comment by jonhiggs** [comment]
I'd like to +1 this issue too. My first guess to fix it was adding a <CR> or two to the end but that didn't work.

**Comment by nishantvarma** [comment]
This can also help when you do a git push origin right? Would like to avoid the extra enter usually  ... the alternative currently is to do pull in Vim which can execute a command silently.

**Comment by netei** [comment]
Yes, if that syntax was implemented, you could do something like : 

    bind generic p <@ sh -c 'git push origin master > /dev/null && echo "Done" || echo "Fail"'

**Comment by jonas** [comment]
Fixed in 4a3d90a, which uses the `+` modifier. I am considering to rewire it to `<` (which currently means quit-after-command).
