### ISSUE TITLE
showing signature in log view

### ISSUE THREAD

**Issue by Avinash-Bhat** [jonas/tig#208]
Currently there is no way to see which commit has signature (GPG/PGP).
This is a huge benefit to a maintainer as he/she can see the unsigned commits without using an external command by using only the cursor keys in the log view.

**Comment by specious** [comment]
I've got tig 2.3.2, and after adding the following to my `~/.tigrc` I see PGP signatures both when I do `tig log` and when viewing commit details in `tig` proper:

```
set log-options = --show-signature
set diff-options = --show-signature
```
