### ISSUE TITLE
Control-y sends SIGTSTP signal and suspend tig on Mac OSX

### ISSUE THREAD

**Issue by kyanny** [jonas/tig#214]
Hi, I had an unexpected behaviour of tig on Mac OSX.

When I press Control-y key sequence during running tig, tig suspends and go background.
I read tig.c and found that the default behaviour of Control-y is REQ_SCROLL_LINE_UP.
I tried to same thing on Ubuntu, it works as expected.
I googled and found some Q&A about SIGTSTP and curses issue (*1) (*2), but can't reason why it occurs.

My environment:
- `uname -a` `Darwin Kensukes-MacBook-Pro.local 12.5.0 Darwin Kernel Version 12.5.0: Mon Jul 29 16:33:49 PDT 2013; root:xnu-2050.48.11~1/RELEASE_X86_64 x86_64`
- `$ gcc --version` `i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)`

gdb message:

https://gist.github.com/kyanny/7085526

When I manually trap SIGTSTP signal in main() function of tig.c, this issue not happened. (but this change completely disables Control-y key functionality, too)

https://github.com/kyanny/tig/compare/ignore_sigtstp_macosx
- (*1) http://www.linuxmisc.com/9-unix-programmer/5f5274eaaadc51a6.htm
- (*2) http://www.linuxmisc.com/9-unix-programmer/f19bde92a416cd9a.htm

**Comment by erikw** [comment]
Thanks, had this problem too.

Could we do something in tig to help OSX users to not having to change `dsusp`?
