### ISSUE TITLE
cannot detect unstaged changes in working dir created with git new-workdir 

### ISSUE THREAD

**Issue by maverickwoo** [jonas/tig#224]
git-core/contrib/workdir/git-new-workdir is a contributed script that supports creating separate working directories based on one .git directory.

Steps to reproduce, assuming ~/foo is the original git repo:
1. cd ~; git new-workdir foo bar
2. cd bar; [change a tracked file in bar here]
3. tig
tig will not show that there are unstaged changes

**Comment by JIghtuse** [comment]
Reproduces with `git worktree` too. Any thoughts how to track that down?

**Comment by JIghtuse** [comment]
Saw a TRACE variable in https://github.com/jonas/tig/issues/437, here is output:

    [project_add_license]$ TIG_TRACE=out tig status
    [project_add_license]$ cat out 
    git rev-parse --git-dir --is-inside-work-tree --show-cdup --show-prefix HEAD --symbolic-full-name HEAD 
    git config --list 
    git ls-remote /tmp/tig_test/project/.git/worktrees/project_add_license 
    fatal: '/tmp/tig_test/project/.git/worktrees/project_add_license' does not appear to be a git repository
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    git update-index -q --unmerged --refresh 
    git ls-files -z --cached --exclude-standard 
    git diff-files -z 
    git ls-files -z --others --exclude-standard 

Oddly enough, tig shows unstaged changed if launched as `tig status`, but not shows them in "main" window.

Here is actions to reproduce it:

    [project]$ git init
    Initialized empty Git repository in /tmp/tig_test/project/.git/
    [project]$ touch README.md
    [project]$ git add README.md
    [project]$ git commit -m "Initial commit"
    [master (root-commit) 2652bfc] Initial commit
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 README.md
    [project]$ git checkout -b license
    Switched to a new branch 'license'
    [project]$ touch LICENSE
    [project]$ git add LICENSE
    [project]$ git commit -m "Add license"
    [license d74fa31] Add license
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 LICENSE
    [project]$ echo "something" > LICENSE
    [project]$ git diff
    diff --git a/LICENSE b/LICENSE
    index e69de29..deba01f 100644
    --- a/LICENSE
    +++ b/LICENSE
    @@ -0,0 +1 @@
    +something
    [project]$ git status
    On branch license
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   LICENSE

    no changes added to commit (use "git add" and/or "git commit -a")
    [project]$ tig
    [project]$ git stash
    Saved working directory and index state WIP on license: d74fa31 Add license
    HEAD is now at d74fa31 Add license
    [project]$ git checkout master
    Switched to branch 'master'
    [project]$ git worktree add ../project_add_license license
    Enter ../project_add_license (identifier project_add_license)
    Switched to branch 'license'
    [project]$ cd ../project_add_license/
    [project_add_license]$ ls
    LICENSE  README.md
    [project_add_license]$ git stash pop
    On branch license
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   LICENSE

    no changes added to commit (use "git add" and/or "git commit -a")
    Dropped refs/stash@{0} (d3019665d840a0fbe15d458a7e10655fea05344c)
    [project_add_license]$ tig
    [project_add_license]$ git diff
    diff --git a/LICENSE b/LICENSE
    index e69de29..deba01f 100644
    --- a/LICENSE
    +++ b/LICENSE
    @@ -0,0 +1 @@
    +something
    [project_add_license]$ git status
    On branch license
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   LICENSE

    no changes added to commit (use "git add" and/or "git commit -a")

On the first launch (in `project` directory) tig shows unstaged changes, on the second (in `project_add_license`) it doesn't show them.
