### ISSUE TITLE
Is it possible to syntax-highlight the source lines in blame view?

### ISSUE THREAD

**Issue by aniruddha-a** [jonas/tig#229]
By filtering through GNU source-highlight etc, if installed?

**Comment by pelegm** [comment]
This could have been very nice.

**Comment by netei** [comment]
You could use a keybinding to open that file in your editor, in gitblame mode (with a plugin)

**Comment by nick87720z** [comment]
What if delta was used for that? It makes ready to use output for blame, grep, diff tools (what I exactly tried). Thus, it could help enhance not only blame view.
