### ISSUE TITLE
tig status does not show untracked files outside of current directory

### ISSUE THREAD

**Issue by BenBergman** [jonas/tig#230]
I just noticed that untracked files are not showing up in `tig status` if they are not in the current directory or lower.

For example, say we have this directory structure:

```
root
 |- dir_a
 |   '- old_file
 '- dir_b
     '- new_file
```

If we are currently in `dir_b` or `root` and run `tig status`, we see the untracked file `new_file`, but if we are in `dir_a`, we see `(no files)` listed.

Edit: I'm running `tig` from source, version `tig version 1.1-89-g9439272`

**Comment by makrem025** [comment]
+1

Tig version: 2.0.3 and Git version: 2.3.0

**Comment by shilov** [comment]
I'm no longer experiencing the issue after upgrading to a newer version of Ubuntu, equipped with an updated version of zsh. Might have something to do with one of these.
