### ISSUE TITLE
Multiselect in StatusView

### ISSUE THREAD

**Issue by janbaer** [jonas/tig#267]
Is it possible to select more than one file in the status view and then make a operation like undo with all selected files?

**Comment by gilescope** [comment]
or stage with all selected files. It would be nice if it were possible...

**Comment by mclucario** [comment]
I would really like this. It makes working with huge codebases alot more bearable.

**Comment by mclucario** [comment]
@jonas Would you mind explaining us why it's not possible, just for future reference?

**Comment by gilescope** [comment]
Would a PR be accepted if someone were to find a way? (I think what we’re saying here is we _really_ like tig)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
