### ISSUE TITLE
Author date / commit date confusion

### ISSUE THREAD

**Issue by chirayuk** [jonas/tig#294]
The main view displays the "Author Date" (though all the documentation for `tig` and `tigrc` refers to it as the "Commit Date".)  I would really like to see the actual Commit Date.  I assume that it isn't supported (I didn't see an option for it – I just built a fresh tig from source.)  The Commit Date is super helpful when scanning the upstream log to see which breaking commits are newer and and require rebase attention.  (I missed a conflicting commit because I thought I had already rebased on it.)  I would love to see some support this.

**Comment by natemccurdy** [comment]
Looks like there's an open PR to address this: https://github.com/jonas/tig/pull/810

**Comment by jremus** [comment]
It would be great to toggle between the author and commit date. Especially in the `tig reflog` view the commit date would be more valuable than the author date.

**Comment by vt-alt** [comment]
To being able to see commit date would be extremely useful. As in most projects author date is almost an arbitrary thing, but committer date really shows when change is introduced.

**Comment by vt-alt** [comment]
@koutcher Thanks much!

**Comment by jremus** [comment]
@koutcher Awesome, thanks a lot!

**Comment by chirayuk** [comment]
@koutcher 🙏

**Comment by PaulChanHK** [comment]
https://github.com/jonas/tig/commit/7351f170b0e4e6f7675ccff9167b4892ed9f426b has some issues
1. In main view, committer date column is not updated after entering command 'set main-view-date-use-author = no|yes'
2. Author name and date should come in a pair, can we have both name+date toggled between Author/Committer ?

For some projects, author fields are useful for 3rd party/picked changes. I closed https://github.com/jonas/tig/pull/810 as it was too old, but I really want the feature for name+date.
Many hesitations as I don't want to maintain my branch/PR, yet it seems maintainers are not willing to comment/merge/rework some PRs.
