### ISSUE TITLE
Delete files in status view

### ISSUE THREAD

**Issue by svenn71** [jonas/tig#31]
I just started using tig and found myself looking for the possibility to delete untracked files in the status view. The scrollable view is a nice way to root out generated files which should not be added to the repository. Sometimes it is easier to delete most of the known unwanted files before starting the search for the wanted ones to add. I have not found in the documentation any hints on how to delete the current highlighted file.

**Comment by Schroedingers-Cat** [comment]
Yes, files should be removed if untracked when pressing "!". You have to confirm that action, so I wouldn't be concerned about it, I'd rather expect it.

**Comment by fabioperrella** [comment]
does anybody knows if it is possible to refresh the status view after deleting the file (in this bind)?

**Comment by evmorov** [comment]
> does anybody knows if it is possible to refresh the status view after deleting the file (in this bind)?

@fabioperrella have you found the way to do that?

**Comment by fabioperrella** [comment]
@evmorov you can refresh pressing `R`

**Comment by evmorov** [comment]
@fabioperrella oh, ok. It's not that I wanted to head. Thanks!

**Comment by psprint** [comment]
Further refining the binding – require **two** `D`-key presses:
```sh
bind status DD !@?rm %(file)
```

**Comment by dagadbm** [comment]
why not just implement the status-revert action to also delete files behind a prompt?
! is used everywhere for destructive behavior... makes no sense to add a new D keybinding for it
