### ISSUE TITLE
If I bind a command to <Ctrl-v>, I need to press Ctrl-v twice to invoke the command

### ISSUE THREAD

**Issue by clarkgrubb** [jonas/tig#314]
I put this in my .tigrc

```
bind generic <Ctrl-v> move-page-down
```

But for some reason I need to press `Ctrl-v` twice to page down.  If I bind `move-page-down` to `<Ctrl-a>`, I don't need to press `Ctrl-a` twice.  I looked thru the online tig help, and I don't see any bindings for `<Ctrl-v>`.  I am running this in Terminal.app with bash.  Other curses apps seem to be able to bind `Ctrl-v` to commands, so it doesn't _appear_ to be my environment.

**Comment by jonas** [comment]
Fixed by @rolandwalker in #619
