### ISSUE TITLE
Scrolling up works, but not down

### ISSUE THREAD

**Issue by paps** [jonas/tig#321]
Currently on an unstable Debian, I'm using tig (version 2.0.2) in tmux (version 1.9) in xterm (version 308).

In my `.gitconfig` I have:

```
[tig]
    mouse = true
```

Moving with the arrow keys and JK works as excepted. Scrolling with the mouse wheel to go up also works as expected. However scrolling down with the mouse wheel does nothing...

Mind you, my mouse wheel works well everywhere else, be it in vim or tmux to scroll buffers (up AND down).

So, do you have any idea of what can cause this?

Thanks :)

**Comment by michaelbarlow7** [comment]
I'm getting this as well, running the latest tig on Linux Mint 17. 

I have a feeling it's a curses problem. I ran this sample code and I'm getting the same issue.

http://pastebin.com/dSGc4KSg

Scrolling up works correctly (I get "Get mouse was ok"). Scrolling down shows "getMouse failed".

Versions:
- Xterm(297)
- ncurses: 5.9.20140118

**Comment by michaelbarlow7** [comment]
Also happens on Xubuntu 14.04.

**Comment by jonas** [comment]
Thanks for giving this some more testing. I arrived at the same conclusion when I looked at this a while back.

**Comment by lucc** [comment]
I also have this problem on Arch Linux.
xterm: 322
urxvt: 9.22
ncurses: 6.0
tig: 2.1.1

Are there any news on this? Should this be reported upstream?

**Comment by php-coder** [comment]
The same behavior on Fedora 22, tig 2.11, gnome-terminal 3.16.2 and ncurses-5.9-18.20150214

**Comment by navytux** [comment]
I've digged it a bit. The problem is ncurses is built without --enable-ext-mouse in e.g. Debian and with old events encoding there is no way to represent button5. Details:

https://bugs.debian.org/838376

**Comment by colorwin** [comment]
Up and down is Ok, bug left and right not work. Can you support it?

Mac, iterm2 Build 3.1.5
tig version 2.3.3-17-g0ea017d
ncurses version 5.7.20081102
readline version 7.0
