### ISSUE TITLE
tig slows down for large repositories

### ISSUE THREAD

**Issue by grumbelbart** [jonas/tig#324]
Hi,

tig is usually quite responsive and speedy. However, when using it on my large repo (~65000 commits in master, in an almost linear history), showing commits becomes slow (~1 second delay).

Steps to reproduce:
- open tig on a large repo (probably with a long history?)
- Press return to view the diff of the current commit
- press up, down to scroll

tig takes ~1 second to go to the next commit in the list and to show its diff. It works normally when not showing the diff (just scrolling through the list of commits).

Cheers and Thanks
- Eph

**Comment by grumbelbart** [comment]
Much faster now, when using tig master. Thanks!

**Comment by jonas** [comment]
Please see https://github.com/jonas/tig/blob/master/contrib/large-repo.tigrc for a list of options to speed up Tig in large repos.

**Comment by dustymabe** [comment]
when you set `main-options = -n 1000` to limit to 1000 commits would it be possible to "load more commits" once you reach the bottom? i.e. load them on demand?

**Comment by igaw** [comment]
Maybe these options could be documented in tig manual? I was told that tig needs to be configured on large git repositories to be fast. So I checked the manual, but didn't find anything on it. Could also be that I just oversaw it.

**Comment by jonas** [comment]
@igaw Great idea. I've created #770. Are you up for making a PR?

**Comment by xinyunliu** [comment]
> Please see https://github.com/jonas/tig/blob/master/contrib/large-repo.tigrc for a list of options to speed up Tig in large repos.

`set commit-order = default`  does matter for `tig version 2.2`

**Comment by metux** [comment]
I've got the same problem:

even with "set main-view-commit-title-graph = v1" and limited to 100 commits, it takes about 10secs to show the kernel history.

tig version: 2.2 (devuan rev 2.2-1+b2)
machine: 4x I7, 8G ram, SSD

With some older tig version (dont recall which one exactly) this took less than a second.

Any ideas how to get it fast again ?

thx
--mtx
