### ISSUE TITLE
Feature Request: Ability to show short commit hash in main view

### ISSUE THREAD

**Issue by dustymabe** [jonas/tig#340]
When I go into git blame view on a file within tig I see the short commit hash for each line of the file. I can then press enter and see the log message and diff for that commit. It would be great for the main view to have the ability to show the short commit hash alongside time/author etc.. This is nice for when you want to copy/paste multiple references quickly without having to move to each one in tig to find the hash. 

Thanks!

**Comment by hossbeast** [comment]
what is the correct incantation to enable this feature in .tigrc?

I have ````set main-view = yes```` but it does not work

**Comment by jonas** [comment]
@hossbeast Use `set main-view-id = yes` and alternatively `set main-view-id-width = 20` to set the width of the column.

**Comment by VonUniGE** [comment]
It's `:toggle id` now.

**Comment by poige** [comment]
`:toggle id` worked in Ubuntu 16.04's `tig` version, but `set main-view-id = yes` in .tmuxrc didn't.

**Comment by koutcher** [comment]
@poige, maybe you should try **.tigrc** instead of .tmuxrc...

**Comment by poige** [comment]
@koutcher thank you, but this was a mistype I've made somehow when commenting. Here's what I meant instead:

```
%  cat ~/.tigrc; lsb_release -a
set main-view-id = yes

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by koutcher** [comment]
@poige, what is your tig version (`tig -v`) ?

**Comment by poige** [comment]
It's not "my tig version", currently I have Ubuntu 18.04 where, my comment was purely informational — for those who still use Ubuntu 16.04. I doubt it'd be ever possible to ship a fix into 16.04 package.

**Comment by heyakyra** [comment]
> It's `:toggle id` now.

this and `SHIFT+x` gives me:
```
`:toggle id` not supported
```

**Comment by laoshaw** [comment]
ubuntu 20.04 here, tig does not work with 'set main-view-id=yes', however, this works in .tigrc:

set main-view-id-display = yes

**Comment by jairusmartin** [comment]
or Shift + X

**Comment by benjie** [comment]
Seems to be `:toggle id-display` now.

**Comment by benjie** [comment]
@jonas Maybe you could append something like this to the top comment:

```md
---

**MAINTAINER ANSWER**: Use Shift + X or `:toggle id-display`
```

This issue is still the top google result for "tig show hash" (for me at least)

Thanks! ❤️
