### ISSUE TITLE
Feature Request: Ability to search file tree

### ISSUE THREAD

**Issue by jcowgar** [jonas/tig#342]
You can search the screen right now and that will work somewhat in Tree view, but it would be nice to be able to search for a file in any directory and go there in tree view.

**Comment by CodeMan99** [comment]
Could you not use `:!file %(directory) -name '{keyword}'` ?

**Comment by vivien** [comment]
Indeed, `:bind tree t !find %(directory) -name %(prompt)` might be a quick alternative.

**Comment by jcowgar** [comment]
It seems that `:bind tree t !find %(directory) -name %(prompt)` simply searches for the file and will show where it resides. The feature request would be for tig to actually go to that file in the file tree so one could interact with it, such as blame.

**Comment by jonas** [comment]
@jcowgar I pushed an initial version to `master`. Please give it a try if you are able. I decided to mark the issue as fixed, however, many improvements are possible. Right now you can open the file finder by entering the blob view with no file selected. You can reopen the file finder by pressing the key to open the blob view from within the blob view.

**Comment by CodeMan99** [comment]
@jonas To leave the "find" input mode I had to hit escape twice. Was that intentional? Only asking because you did not describe that in your comment, I think the workflow is fine.

**Comment by jonas** [comment]
No and I cannot reproduce it. Note that after you hit escape there's usually a small delay before you see it reflected. Could you try to run tig like this and see if you still have to call escape twice:
```
$ ESCDELAY=200 tig
```
Else I'll need to know what terminal you are using and if you are using readline.

**Comment by CodeMan99** [comment]
Seems to be the `ESCDELAY` time. Hitting escape once is fine. Guess that isn't part of my normal workflow since I use GNU nano.

**Comment by jcowgar** [comment]
@jonas, I love it! It works great and is exactly what I was looking for. Thank you for implementing this!

**Comment by jonas** [comment]
Super, thanks for testing.
