### ISSUE TITLE
tig modules / extensions

### ISSUE THREAD

**Issue by edi9999** [jonas/tig#343]
Is they a way to write custom modules (or extensions) to tig.

For example, I would like to create a keymapping to jump from the commit under the cursor to the url of that commit in github.com ?

Is they a way to create such mappings ?

**Comment by ryuheechul** [comment]
Thanks for all the great suggestions above!
So I tried the current wiki version below.

```bash
bind generic B @sh -c "xdg-open 'https://'$(git remote -v | grep -Eo 'github.com[:/][^.]+' | head -1 | tr : /)'/commit/%(commit)'"
```

It worked for most part but failed at two scenarios:
- remote host not being github.com
- repo contains `.` in the name like https://github.com/folke/lazy.nvim

So I improved this to work with those as well with below.

```bash
bind generic o @sh -c "open 'https://'$(git remote -v | head -n1 | cut -f2 | sed 's|^https://||' | sed 's|^ssh://git@||' | sed 's|.git\ .*$||')'/commit/%(commit)'"
```
Few notes on above:
- I used `open` here but you can change to `xdg-open` and it should still work
- using delimiter of `/` and `#` did not work in tigrc file even though it works in bash
- so I used `|` with quoting instead and that seem to work

_And here is my corresponding [dotfile changes](https://github.com/ryuheechul/dotfiles/commit/8e11c6a07dceba45ec54b408a956cafa748c3fa5) for that._
