### ISSUE TITLE
Recent update broke tig? It does not open the interface

### ISSUE THREAD

**Issue by gerroon** [jonas/tig#349]
Hi

I recent;ly upgraded Debian and tig was upgraded as well. Since then tig is not opening the interface in a git repo folder. I tried the latest sources as well and the result is same.

All I get is this

"tig: No revisions match the given arguments."

tig version 2.0.3-47-g5f4d4ef

thanks

**Comment by jonas** [comment]
@gerroon I was wondering if you would have time to help and narrow down this issue?

**Comment by gerroon** [comment]
@jonas 

I think it was something to do with my repos. I am unable to replcate the issue. Thanks for your time.
