### ISSUE TITLE
Improvement of reference lookup using hashtable

### ISSUE THREAD

**Issue by danielfranca** [jonas/tig#350]
Hi jonas,
We talked to you last month, as we were trying to improve tig performance to handle our repository.
We did an implementation using glib hash table, replacing the search in both add_to_refs and get_ref_list.
It was before we realize that there's a hash table implementation in the source already, so we tried to move the code to use the compat/hashtable.c.
We could make it work for add_to_refs, but no success for get_ref_list, our code is failing in some of the tests.
What you think? Should we try to do this? The code working with glib hashtable was working fine for that, probably is something that we didn't understand well in the way compat/hashtable works. Can you help us to figure out if there's something clearly wrong?

The commit with the changes for get_ref_list is in https://github.com/jerojasro-booking/tig/commit/7c153d3844268f6fcbd980c8d670239cdc39a9e2
Let me know if there's something else we can do.

Best,
Daniel

**Comment by jonas** [comment]
Finally got around to figuring out how to handle 'replaced refs' so this could be merged.
