### ISSUE TITLE
Jump from blame to commit

### ISSUE THREAD

**Issue by CyberShadow** [jonas/tig#355]
Is it possible to jump to the history context of the commit of a blamed line, similarly to the git-gui option which opens gitk on the corresponding commit?

I notice `m` already filters the history to only show commits touching the specified file, it just doesn't jump to the corresponding commit.

The reason for asking this is that it's often useful to know which pull request was a commit part of, as that's where the discussion and code review occurred. If you find the commit in the main view, you can find its merge commit, which has the pull request # in it.

**Comment by xemle** [comment]
+1
