### ISSUE TITLE
Screenshots ?

### ISSUE THREAD

**Issue by Gys** [jonas/tig#358]
I cannot find any screenshots of this. Does that mean it is only command line based ? I somehow expected a text window based interface. Something like vim. Am I mistaken ?

**Comment by edi9999** [comment]
Here's a screenshot. It is indeed a text based interface inside the console:

![selection_042](https://cloud.githubusercontent.com/assets/2071336/5606880/b3552176-9444-11e4-95ba-bcfccec02dd5.png)

**Comment by Gys** [comment]
Great ! Thank you. I think you should put some in the readme.
