### ISSUE TITLE
Can we do interactive git commands ?

### ISSUE THREAD

**Issue by nishantvarma** [jonas/tig#359]
Is it possible to do interactive git commands like git add --patch or git add --interactive ?
Patch especially would be helpful to have. Interactive is probably optional feature to have.

**Comment by edi9999** [comment]
In my `~/.tigrc`

I have put 

`bind status P !git add --patch %(file)`

to be able to press P on a file to decide which patch to apply.

Also, if you are in status view and press enter on a file, you can update lines with `u`, just like patch would do

**Comment by CodeMan99** [comment]
That's what status view is for. It's actually better than using `git add --patch` directly because you can chose a hunk or an individual line (by pressing '1' while selecting the line) in the same program. You need an editor to select lines otherwise.

**Comment by edi9999** [comment]
Didn't know about the `1` shortcut, really helpful !

**Comment by jonas** [comment]
Thanks for the suggestions @CodeMan99 and @edi9999 ...
@nishantvarma I will go ahead and close this, since it looks resolved to me.
