### ISSUE TITLE
Erasing with ^H does not work

### ISSUE THREAD

**Issue by erikw** [jonas/tig#360]
I always erase character backwards using ^H instead of Backspace. Unfourtunately this does not work well in tig e.g. in the search field. Pressing ^H produces a capital H. Fixing this would make life so much easier :)

**Comment by jonas** [comment]
Are you using the readline support? It improves the search and prompt substantially.

**Comment by jonas** [comment]
Closing this as more info is needed. Feel free to reopen when you get around to taking a look at it again.
