### ISSUE TITLE
allow tig to "follow" renamed files

### ISSUE THREAD

**Issue by dustymabe** [jonas/tig#361]
Is it possible to have tig "follow" history of renamed files.. Specifically if I run *git log --oneline --follow renamed_file.txt* then I am able to see all the history of that file. If I just run tig renamed_file.txt then I don't see it. My suggestion would be to add a mode to tig (just like git log) that allows history to be followed: *tig --follow*

Is this possible already? Did I miss it somewhere.

Thanks,
Dusty

**Comment by vivien** [comment]
Indeed, options are passed to git, so `tig --follow renamed_file.txt` will work as expected.

**Comment by dustymabe** [comment]
you are right!! wow.. some programs allow you to specify arguments anywhere on the line and so I was mistakenly running it this way: **tig  renamed_file.txt --follow**. It works if you put --follow first.

Thanks
