### ISSUE TITLE
How to show latest checked-in version of file?

### ISSUE THREAD

**Issue by mahemoff** [jonas/tig#363]
Hitting Enter on a file shows the diff. Would be nice if there was a way to just see the original file alone - is this possible at present? If not, please consider it a feature request.

**Comment by jonas** [comment]
You can view the complete file content by opening the blob view (bound to
'f' by default) while in the diff (c)hunk concerning the file.
Alternatively you can also press 'e' to open the file at the selected diff
line in an editor of your choice.

**Comment by mahemoff** [comment]
Perfect. Thanks @jonas
