### ISSUE TITLE
navigate code blocks with vim shift + '{' and shift + '}' 

### ISSUE THREAD

**Issue by ruebenramirez** [jonas/tig#364]
Apologies if this issue has already been submitted.  (I couldn't find it)

Tig is the best!  I use it every day in my normal workflow.  

I code in vim and use the shift + '{' and shift + '}' to navigate code blocks/paragraphs quickly.  Is there a way to navigate tig diffs with these key bindings?  If not, is there a plan to include this feature in the future?

Thanks!

**Comment by jonas** [comment]
There's a default keybinding for navigating diff (c)hunks which simply
searches for the next line starting with `@@` when `@` is pressed:

    bind stage @ :/^@@

Is this what you are looking for?

**Comment by ruebenramirez** [comment]
oh nice!  Yeah I can give that a shot.  Thanks!

**Comment by jonas** [comment]
@ruebenramirez I'll assume that `@` did the job. Please reopen if this is not the case.
