### ISSUE TITLE
Feature Request: Expose %(remote)

### ISSUE THREAD

**Issue by CodeMan99** [jonas/tig#365]
Quite simply I'd like to write binding that include a remote name, and just saying `origin` is not sufficient since the remote name can be anything.

For example if you want to support issue #199 you should have a variable remote name for this.

My workflow currently including pushing only some commits, not all, so I would bind:
`bind main P !git push %(remote) %(commit):%(branch)`
(I would also like to bind a yes/no prompt to avoid accidental pushes)

**Comment by CodeMan99** [comment]
Sorry! Did not realize how old my build was. (silly package managers).

Side note: I did not see `%(remote)` in the documentation.

**Comment by jonas** [comment]
> (I would also like to bind a yes/no prompt to avoid accidental pushes)

You can achieve this by using the `?` flag in front of the command. Example:

    bind main P !?git push ...

**Comment by CodeMan99** [comment]
Thank you. Wonderful tool. :trophy: I will contribute at some point. :electric_plug: :octocat:
