### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by Konafets** [jonas/tig#369]
Hi, 

I have more a question than an issue. I like to create a custom color scheme for tig and like to tweak the provided colors or add new ones. For example the green looks a litte bit too neon for me. I am using ITerm2 on OSX 10.10. How can I do that. I read in the docu to use color0, color1, ..., colorN, but don't understand what that mean. 

Thanks in advance

**Comment by jonas** [comment]
Hi,

The _colorN_ specification where _N_ can be 0 to 255 allows to use the colors defined in the xterm 256  color chart. Wikipedia has a nice image showing the colors here
http://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg:

![http://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg](http://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg)

**Comment by Konafets** [comment]
Thanks for the answer. I will try it out.

**Comment by vivien** [comment]
Having some `contrib/colors/<scheme>.tigrc` files would be wonderful!
