### ISSUE TITLE
Segfault on s -> R -> q

### ISSUE THREAD

**Issue by commonquail** [jonas/tig#370]
This one is peculiar.

As of 196c4bc47d1c147e24f27e04001724d41c6ccf3d, when I compile `master` with
```sh
$ ./configure && make
```
`./src/tig` consistently segfaults when I leave (`q`) the status window (`s`) if and only if I manually refreshed the display (`R`). However, when checking out the above commit-ish, or `refs/bisect/bad` pointing to it, I am consistently *unable* to reproduce the segfault. I have not made a point of using tig like this so I don't know if it would crash eventually.

This seems to happen whether or not the repo is dirty.

**Comment by jonas** [comment]
Thanks for the excellent test case. The regression was introduced when the reference DB was updated to use a hash table.

**Comment by jonas** [comment]
Oops and now I broke the build because I was too lazy to run the whole test suite. ;)

**Comment by commonquail** [comment]
In the meantime, I can report that I've experienced no issues since filing the report by compiling the commit-ish as mentioned. That said, I don't often move outside the mentioned views, and for instance have not tested the blame view at all.
