### ISSUE TITLE
Status View is not updated after pressing u inside a file (when running in tmux)

### ISSUE THREAD

**Issue by edi9999** [jonas/tig#372]
When I'm inside a file that I want to put into the staging area, my usual workflow is to open the files diff using `<enter>`. Than I press `u` to stage the few lines under the cursor. The only problem with this is that the view of the diff is not updated. Even pressing `F5` or `R` does'nt change that.

I'm running in tmux, and I just figured out that it does work as expected when not in tmux.

Do you maybe have an idea why they is such a behaviour but only in tmux ?

**Comment by vivien** [comment]
Hi @edi9999, try to set TERM for tmux: `TERM=screen-256color tig`.

**Comment by edi9999** [comment]
That works. Thanks!

**Comment by jonas** [comment]
Cool. This should go into a FAQ file or maybe a trouble shooting section in the manual or tig(1).
