### ISSUE TITLE
"tig: Failed to load refs"

### ISSUE THREAD

**Issue by bbolli** [jonas/tig#374]
I have a repo [here](https://github.com/bbolli/tumblr-utils) that produces the above error since commit c9bf04eb66c9bf064331235d964cdd8920b1156a (found by bisecting).

**Comment by jonas** [comment]
I cannot reproduce this in a clean checkout of the repo using the current version in master.

**Comment by bbolli** [comment]
On 15.02.15 21:53, Jonas Fonseca wrote:
> I cannot reproduce this in a clean checkout of the repo using the
> current version in master.

You can download the .git directory here:

https://drbeat.li/dl/issue-374.tar.gz

Thanks,
Beat
-- 
https://drbeat.li
pgp: 0x506A903A; 49D5 794A EA77 F907 764F  D89E 304B 93CF 506A 903A
gsm: 4.7.7.6.0.7.7.9.7.1.4.e164.arpa
icbm: 47.0452 N, 7.2715 E

"It takes love over gold, and mind over matter" -- Dire Straits

**Comment by jonas** [comment]
Thanks this is fails to load refs.

**Comment by jonas** [comment]
@bbolli Thanks for reporting this. I can no longer reproduce it with the `.git` directory you sent me.

**Comment by bbolli** [comment]
Thanks, it also works for me.
