### ISSUE TITLE
Crash when staging a hunk

### ISSUE THREAD

**Issue by jasontibbitts** [jonas/tig#376]
Noticed this in Fedora's bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1186676
Fedora has git 2.0.3 and carries no additional patches.

Steps to Reproduce:
1. open tig
2. go to Unstaged changes
3. press d
4. navigate to some chunk
5. press u

Core was generated by `tig'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  view_no_refresh (view=view@entry=0x0, flags=flags@entry=OPEN_REFRESH) at src/view.c:559
559                    ((flags & OPEN_REFRESH) && !view_can_refresh(view));
(gdb) bt full
#0  view_no_refresh (view=view@entry=0x0, flags=flags@entry=OPEN_REFRESH) at src/view.c:559
No locals.
#1  0x00000000004155b8 in load_view (view=0x0, prev=prev@entry=0x0, flags=flags@entry=OPEN_REFRESH) at src/view.c:770
        refresh = <optimized out>
#2  0x000000000041f30d in stage_request (view=0x63bb40 <stage_view>, request=<optimized out>, line=<optimized out>) at src/stage.c:442
No locals.
#3  0x000000000040340c in view_driver (request=REQ_STATUS_UPDATE, view=0x63bb40 <stage_view>) at src/tig.c:206
        i = <optimized out>
#4  main (argc=<optimized out>, argv=<optimized out>) at src/tig.c:697
        codeset = <optimized out>
        pager_mode = false
        request = <optimized out>
        view = <optimized out>

I will be happy to shuttle any information between this issue and the Fedora ticket.  Will offer the reporter a package generated from current git head to see if the issue still occurs there.

**Comment by jonas** [comment]
Thanks for forwarding this.

**Comment by jasontibbitts** [comment]
No problem; thanks for fixing it.
