### ISSUE TITLE
Usage of EDITOR in test/tools/libtest.sh

### ISSUE THREAD

**Issue by heiko3** [jonas/tig#379]
In test/tools/libtest.sh EDITOR is overwritten with $fake_editor which has no effect because GIT_EDITOR has a higher preference. I suggest to use GIT_EDITOR in test/tools/libtest.sh instead.

Steps to reproduce:

make test GIT_EDITOR=vi

**Comment by jonas** [comment]
Thanks for reporting this. I took the opportunity to also add a couple of other environment variables that might break the test suite.

**Comment by heiko3** [comment]
If you stay with EDITOR you should clear at least VISUAL too.

Try:
make test VISUAL=vi
