### ISSUE TITLE
Unstaged changes should be shown above staged changes

### ISSUE THREAD

**Issue by proski** [jonas/tig#383]
Staged changes are shown above unstaged changes. That's not the logical order. Unstaged changes can modify staged changes (see screenshot) but not the other way around. It's just like a newer commit can modify text added by an older commit. New commits are shown above old commits, so it's logical to follow that pattern for local changes.

To look at it another way, staged changes are closer to the commits. It's trivial to commit staged changes only - it's the default `git commit` behavior. It's much trickier to commit unstaged changes and omit staged changes, especially if both affect the same file. Thus staged changes should be closer to commits, i.e. lower.

![tig](https://cloud.githubusercontent.com/assets/1317472/6337973/71035b06-bb79-11e4-9293-c525ea371488.png)

**Comment by jonas** [comment]
That's a good point. gitk does it that way also, which is the where the feature was stolen from.

**Comment by proski** [comment]
Thank you!
