### ISSUE TITLE
no display of remote refs if tag exists

### ISSUE THREAD

**Issue by heiko3** [jonas/tig#390]
tig shows remote refs only if there is no tag for this commit. Bisect shows that commit 26c858d introduces this problem.

To reproduce use the small shell script below. It outputs for me:

    OK   2015-03-16 16:04 Heiko Schlichting I [master] {origin/master} {origin/HEAD} commited
    FAIL 2015-03-16 16:04 Heiko Schlichting I [master] <Marke> commited

```
#!/bin/sh

check() {
    grep -q origin/master $1 && echo -n "OK   " || echo -n "FAIL "
    head -1 $1
}

TDIR=$(mktemp -d)
mkdir $TDIR/fern
cd $TDIR/fern
git init > /dev/null
date > file
git add file > /dev/null
git commit -m "commited" > /dev/null
cd $TDIR
git clone fern nah > /dev/null 2>&1
cd $TDIR/nah
TIG_SCRIPT=$TDIR/tig.script
export TIG_SCRIPT
OUT=$TDIR/tig.display
cat > $TIG_SCRIPT << EOF
:save-display $OUT
:quit
EOF
tig
check $OUT
git tag Marke
tig
check $OUT
echo "For cleaning up remove $TDIR"
```

**Comment by jonas** [comment]
Should be fixed in 4462e25145a1c57635d4639f114c1b0a9b862e56 with Alexanders patch. I added your test case as a regression test.

**Comment by jonas** [comment]
@heiko3 I forgot to add that you are the most awesome bug reporter! Thanks for taking the time to write a test case.

**Comment by heiko3** [comment]
Thanks - also for your lightning fixing of bugs.
