### ISSUE TITLE
visualize white spaces

### ISSUE THREAD

**Issue by gaborbernat** [jonas/tig#392]
Any way to visualize the type of white space?

All IDE-s have this. Like to see the number of tabs, and the number of spaces.

**Comment by jonas** [comment]
There's no way to do this. However, I am considering adding support for running filter commands, which would basically allow an external script to highlight (e.g. syntax highlight) the content. The main contender would be to run `diffhighlight` as requested in issue  #313. But it could probably solve this case also.

**Comment by dwijnand** [comment]
That's awesome news!
