### ISSUE TITLE
Feature request: Delete untracked files from status view

### ISSUE THREAD

**Issue by xi** [jonas/tig#393]
In [git cola](https://git-cola.readthedocs.org/en/latest/git-cola.html#delete-file-s) I can easily delete an untracked file (or add it to `.gitignore` which is less important to me). It would be great to have that feature in tig, too.

**Comment by jonas** [comment]
You can add something like the following to your `~/.tigrc` if you want to
delete a file:

    bind status D @rm %(file)

This will ask for confirmation before running `rm`. If you don't want that
change the `@` to `!`.

To ignore you can do:

    bind status D !sh -c "echo %(file) >> .gitignore"

**Comment by xi** [comment]
Works well. Just one thing: `@` does not ask for confirmation. `?` does that, but that will execute in foreground.

**Comment by jonas** [comment]
True, `@` means run in the background. You can combine the flags:
```
bind status D ?@rm %(file)
```
