### ISSUE TITLE
What does SHIFT-G trigger?

### ISSUE THREAD

**Issue by evamindbench** [jonas/tig#394]
By accident, I hit SHIFT-G in tig and I got this output:

```
Counting objects: 26, done.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (26/26), done.
Total 26 (delta 5), reused 26 (delta 5)
Press Enter to continue
```

What does SHIFT-G trigger?

**Comment by lkraav** [comment]
Garbage collection, right? git gc

**Comment by evamindbench** [comment]
Interesting, here's a link with info on it: http://think-like-a-git.net/sections/graphs-and-git/garbage-collection.html

**Comment by jonas** [comment]
Yes, `G` used to be bound to `git gc`, but this binding was removed when all default options were moved to an external `tigrc` file.
