### ISSUE TITLE
A remote ref didn't show in main view.

### ISSUE THREAD

**Issue by CodeMan99** [jonas/tig#395]
This occurred with tig version 2.1 (3dff6697acf8317edd882ca9c0cce19a37a2ec9e).

I would expect to see `{origin/develop}` on the selected commit.

![main](https://cloud.githubusercontent.com/assets/6373201/6888075/40e62f20-d640-11e4-9853-0bc56354fec4.png)

Here is the ref I am referring to.

![refs](https://cloud.githubusercontent.com/assets/6373201/6888074/40e5b1c6-d640-11e4-99c6-7f8c3fdce482.png)

**Comment by CodeMan99** [comment]
Was this fixed by 4462e25145a1c57635d4639f114c1b0a9b862e56?

**Comment by jonas** [comment]
Would it be possible for you to test this in the current master? This sounds similar to issue #390 which has been fixed by commit 4462e25145a1c57635d4639f114c1b0a9b862e56.

**Comment by jonas** [comment]
@CodeMan99 I believe so.

**Comment by CodeMan99** [comment]
Does seem to be fixed by 4462e25145a1c57635d4639f114c1b0a9b862e56. Maybe make another release tag since this is a common bug to hit? 2.1.1 maybe.

**Comment by jonas** [comment]
Thanks for verifying. Yes, a 2.1.1 (or 2.2) sounds like a good idea.
