### ISSUE TITLE
Arrow keys does not work when searching

### ISSUE THREAD

**Issue by ptzz** [jonas/tig#397]
After initiating a search with "/" and entering search text, arrow key back does not work. Expected to move cursor back in the search query but does nothing. OS X 10.10.2, iTerm2.

**Comment by jonas** [comment]
Are you using readline?

**Comment by ptzz** [comment]
I have readline installed from homebrew, tig from homebrew as well. Do I need to enable readline for tig explicitly?

**Comment by jonas** [comment]
I'm asking because this sounds similar to issue #396. If you move back and type something are the search text modified at the end of where you expect the cursor to be?

**Comment by ptzz** [comment]
It seems arrow back has no effect. If I press it a couple of times (cursor stays) and then write something, text is appended at the end.

Backspace works as expected.

**Comment by ptzz** [comment]
If I force readline and install tig from source:
```bash
brew link --force readline    # "OS X provides the BSD libedit library, which shadows libreadline"
brew install --build-from-source tig
```
I see the the same behavior as in #396. But that seems to introduce other issues, e.g. `ESC-q` adding a "q" to the search query instead of quitting the search.

**Comment by ptzz** [comment]
Homebrew/homebrew#38301 fixes the issue and building from `HEAD` makes the cursor move correctly as well
