### ISSUE TITLE
Tig not showing all branches

### ISSUE THREAD

**Issue by axelson** [jonas/tig#398]
Using tig 2.1 it appears that when run as `tig --all` tig does not show all remote branches. Is this expected behavior or is it potentially a bug? I don't see anything in the manual about it:

http://jonas.nitro.dk/tig/tigrc.5.html

One way to reproduce it is to clone the tig repo. Run `tig --all` and you should see the `origin/master` and `origin/HEAD` branches/references. Switch to the release branch, then run `tig --all` and now only `origin/master` is shown and we cannot see `origin/HEAD`.

**Comment by jonas** [comment]
This is a duplicate of #390 and #395 and has been fixed by commit 4462e25145a1c57635d4639f114c1b0a9b862e56. I plan to make a new release when I get some time.

**Comment by axelson** [comment]
Okay, thanks. I guess my searching through the old issues wasn't complete. I'm going to mark it as resolved. Thanks for your great work on tig! I use it daily.
