### ISSUE TITLE
Unstaged changes view closes after every staging command

### ISSUE THREAD

**Issue by joshproehl** [jonas/tig#399]
Since upgrading to 2.1 on both OSX (homebrew) and ArchLinux:

Open tig
Open unstaged changes
Select a line/chunk to stage
Press 1 or u to stage

Expected result: Chunk/line is staged, unstaged changes view remains open for further staging, views refresh to indicate that there are now staged changes.
Actual result: Chunk/line is staged, but unstaged change view closes immediately, views do not refresh. (Re-opening unstaged changes view usually does not have the refreshed staging details)

(On my Arch box everything was working fine on 2.0.x, and upgrading *only* the tig package caused this behavior to begin.)

**Comment by jonas** [comment]
Thanks for reporting this. I've added an additional check for this feature. The regression was introduced when the rendering of staged/unstaged changes lines was moved from `main_open` to when the HEAD of the current branch is rendered.
