### ISSUE TITLE
history graph doesn't match gitk

### ISSUE THREAD

**Issue by jpritikin** [jonas/tig#400]
git version 2.1.4
tig version 2.0.2

Note that the parent of "SEM: Rename paramHistLen" should be "Observe caution in display". However, tig sorts this commit earlier than the other commits in the simplify branch. Thoughts?

![screenshot from 2015-04-14 13 33 37](https://cloud.githubusercontent.com/assets/2002771/7143051/17f12a26-e2ab-11e4-814e-3f4d2de1637a.png)
![screenshot from 2015-04-14 13 33 42](https://cloud.githubusercontent.com/assets/2002771/7143050/17eded2a-e2ab-11e4-8480-53a754a710c7.png)

**Comment by vivien** [comment]
Just curious, do you have different graphs when changing the commit order? Try `:toggle commit-order` several times.

**Comment by jpritikin** [comment]
Ah ha! Looks like I want topo order.

**Comment by vivien** [comment]
Then you can add `set commit-order = topo` in your `~/.tigrc`. Feel free to close the issue if it looks good to you!

**Comment by jonas** [comment]
Note that from version 2.0.3, topo order is used by default when graph rendering is enabled.

**Comment by jpritikin** [comment]
Yay!
