### ISSUE TITLE
Option to show all refs in Main view

### ISSUE THREAD

**Issue by InfernoZeus** [jonas/tig#401]
I've noticed that I can get the Main view to show all refs by going to Refs view, pressing Enter on the "All references" line, and then qq-ing back to the Main view, but this isn't remembered after restarting tig. Is there any way to set this as the default view?

**Comment by jonas** [comment]
You can start Tig like this: `tig --all`

On Fri, Apr 17, 2015 at 9:37 AM, Ben Fox-Moore <notifications@github.com>
wrote:

> I've noticed that I can get the Main view to show all refs by going to
> Refs view, pressing Enter on the "All references" line, and then qq-ing
> back to the Main view, but this isn't remembered after restarting tig. Is
> there any way to set this as the default view?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/401>.
>



-- 
Jonas Fonseca

**Comment by InfernoZeus** [comment]
Thanks, I didn't spot that :)
