### ISSUE TITLE
tig out of bounds read on xserver git repository

### ISSUE THREAD

**Issue by mherrb** [jonas/tig#402]
tig master dumps core under OpenBSD when trying to display the xserver repository (git://anongit.freedesktop.org/git/xorg/xserver). The stack trace is:

#0  0x00000c47bba3a095 in shift_left (row=0xc4a76750c50,
    prev_row=0xc4a76750c70, pos=64) at src/graph-v2.c:493
493             if (!graph_column_has_commit(&row->columns[pos]))
(gdb) bt
#0  0x00000c47bba3a095 in shift_left (row=0xc4a76750c50,
    prev_row=0xc4a76750c70, pos=64) at src/graph-v2.c:493
#1  0x00000c47bba3aad7 in graph_generate_symbols (graph=0xc4a76750c00,
    canvas=0xc4a5c144450) at src/graph-v2.c:671
#2  0x00000c47bba3ac86 in graph_render_parents (graph_ref=0xc4a76750c00,
    canvas=0xc4a5c144450) at src/graph-v2.c:701
#3  0x00000c47bba35c3b in main_read (view=0xc47bbc54f40, buf=0x7f7fffff3e30)
    at src/main.c:431
#4  0x00000c47bba23fa5 in update_view (view=0xc47bbc54f40) at src/view.c:651
#5  0x00000c47bba21cbe in get_input (prompt_position=-1, key=0x7f7fffff3f24)
    at src/display.c:572
#6  0x00000c47bba1dd43 in prompt_input (prompt=0xc47bbb3d3c7 "",
    input=0xc47bbc4eee0) at src/prompt.c:48
#7  0x00000c47bba1e35d in read_prompt_incremental (prompt=0xc47bbb3d3c7 "",
    edit_mode=false, allow_empty=false,
    handler=0xc47bba0c072 <key_combo_handler>, data=0x7f7fffff43e0)
    at src/prompt.c:177
#8  0x00000c47bba0c2b6 in read_key_combo (keymap=0xc47bbc4d420)
    at src/tig.c:631
#9  0x00000c47bba0c5bc in main (argc=1, argv=0x7f7fffff49b8) at src/tig.c:693
(gdb) p pos
$1 = 64
(gdb)

Under Linux it doesn't dump core, however valgrind find an invalid read approxymatly at the same place:==5030== Memcheck, a memory error detector
==5030== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==5030== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==5030== Command: /home/matthieu/src/tig/src/tig
==5030==
==5030== Invalid read of size 1
==5030==    at 0x42430F: shift_left.isra.11 (graph-v2.c:493)
==5030==    by 0x42506C: graph_render_parents (graph-v2.c:671)
==5030==    by 0x421AF2: main_read (main.c:431)
==5030==    by 0x41687E: update_view (view.c:651)
==5030==    by 0x413DDE: get_input (display.c:572)
==5030==    by 0x410987: prompt_input (prompt.c:48)
==5030==    by 0x404668: read_key_combo (tig.c:631)
==5030==    by 0x403889: main (tig.c:693)
==5030==  Address 0x5af7724 is 4 bytes after a block of size 1,536 alloc'd
==5030==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5030==    by 0x4C2CF1F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5030==    by 0x42449D: graph_insert_column.isra.5 (graph-v2.c:79)
==5030==    by 0x4247D0: graph_render_parents (graph-v2.c:304)
==5030==    by 0x421AF2: main_read (main.c:431)
==5030==    by 0x41687E: update_view (view.c:651)
==5030==    by 0x413DDE: get_input (display.c:572)
==5030==    by 0x410987: prompt_input (prompt.c:48)
==5030==    by 0x404668: read_key_combo (tig.c:631)
==5030==    by 0x403889: main (tig.c:693)
==5030==

**Comment by jonas** [comment]
@mherrb Thanks for taking the time to validate this in valgrind. If you have time, please validate if [the referenced commit](https://github.com/jonas/tig/commit/38e8e7d1527cab1d7c9d5cc8030c940d4e2485fb.patch) fixes this issue for you.

I tried to test with the xserver repo locally on my OS X and was not able to reproduce it. I'll try to schedule some time and add an option to run the test suite with valgrind to hopefully make this type of bugs easier to find.

**Comment by mherrb** [comment]
Yes this patch fixes the crash I was seeing when browsing the xserver repository on OpenBSD. 
Thank you.

**Comment by jonas** [comment]
Thanks for testing the patch.
