### ISSUE TITLE
tig split view problem in 2.1.1

### ISSUE THREAD

**Issue by tankywoo** [jonas/tig#407]
In version `2.1.1`
when I open main view and vertical split diff view, the view is like below, the right diff view only show a small section.

![tig-wrong](https://cloud.githubusercontent.com/assets/1169499/7469331/e9a2f906-f344-11e4-990a-9b49facc30e5.png)

then I switch to previous version, such as `2.0.2`:
![tig-right](https://cloud.githubusercontent.com/assets/1169499/7469344/293981d4-f345-11e4-9466-50b10526f07f.png)

My environment:

* MacOS 10.9.5
* Terminal: iterm2
* LANG="en_US.UTF-8"

**Comment by jonas** [comment]
In 2.1.1, could you provide the settings by starting tig and entering this
prompt command?

    :save-options /tmp/opts.tigrc

I only need to see the first part named 'Settings'.

On Tue, May 5, 2015 at 4:40 AM, Tanky Woo <notifications@github.com> wrote:

> In version 2.1.1
> when I open main view and vertical split diff view, the view is like
> below, the right diff view only show a small section.
>
> [image: tig-wrong]
> <https://cloud.githubusercontent.com/assets/1169499/7469331/e9a2f906-f344-11e4-990a-9b49facc30e5.png>
>
> then I switch to previous version, such as 2.0.2:
> [image: tig-right]
> <https://cloud.githubusercontent.com/assets/1169499/7469344/293981d4-f345-11e4-9466-50b10526f07f.png>
>
> My environment:
>
>    - MacOS 10.9.5
>    - Terminal: iterm2
>    - LANG="en_US.UTF-8"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/407>.
>



-- 
Jonas Fonseca

**Comment by tankywoo** [comment]
@jonas Hi, this is the Settings section:

https://gist.github.com/tankywoo/7ac3e711925dd4e2f88d

**Comment by jonas** [comment]
The guilty line is this:

set split-view-width = 0%

Did you install the tigrc file for version 2.1.1?

Else if you put the following in your ~/.tigrc it should work:

set split-view-width = 50%

**Comment by tankywoo** [comment]
@jonas thanks, I put `set split-view-width = 50%` in .tigrc and it's ok.

> Did you install the tigrc file for version 2.1.1?

How to install tigrc file?

**Comment by jonas** [comment]
It is installed automatically when you install tig from sources and run
`make install`, so the question is how did you install version 2.1.1? From
git? From a tarball?

**Comment by tankywoo** [comment]
@jonas I installed tig from brew(not head version), which seems from a tarball

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tig.rb

**Comment by jonas** [comment]
Strange, I just upgraded the Tig version from brew locally and `/usr/local/etc/tigrc` seems fine and it looks like it knows about that file:

    $ strings /usr/local/bin/tig | grep /tigrc
    /usr/local/etc/tigrc

And it works fine when I run:

    TIGRC_USER= /usr/local/bin/tig

Not sure what else to try.

**Comment by benek** [comment]
Same issue on v2.1.1 installed from Homebrew.

In /usr/local/etc/tigrc I don't have that property (split-view-width), so I've created ~/.tigrc and with ```set split-view-width = 50%``` view split is fine now.

Thanks.

**Comment by jonas** [comment]
@benek Could you try to reinstall with `brew uninstall tig`, and then `rm /usr/local/etc/tigrc` and `brew install tig`?

**Comment by jonas** [comment]
@tankywoo The issue seems to be with how homebrew maintains its `/etc` files. You had version 2.0.2 installed which didn't have the option and it looks like `/usr/local/etc/tigrc` didn't get updated when you upgrade the tig package to version 2.1.1. Removing the package and `/usr/local/etc/tigrc` and reinstalling the package should fix it.

**Comment by tankywoo** [comment]
@jonas yes :+1:  the default file `/usr/local/etc/tigrc` is not udpated with version 2.1.2

**Comment by minhas23** [comment]
I had the same problem and now I am using horizontal split.
You can do it by changing property in usr/local/etc/tigrc
set vertical-split              = horizontal

**Comment by jonas** [comment]
The fix to Homebrew has been merged. To make it take effect you need to

    rm -f /usr/local/etc/tigrc
