### ISSUE TITLE
Stage single line doesnt work anymore

### ISSUE THREAD

**Issue by edi9999** [jonas/tig#410]
Hi,

I've upgraded my tig version to `2.1.1` . I compiled it myself with the `ncursesw` and the special characters are showing well. I think I had 2.x where that issue didn't appear, but can't remember x (but I know I downloaded it after April 1 2015).

However, when I press `1` in the file that has not been updated on that line that has been changed nothing happens

TEST_HELLO_REPO
```
tig -v
tig version 2.1.1
git init
echo "Hello" > hello.txt
git add .
git commit -m "first commit"
echo "Hello2" >> hello.txt
tig status
```

Enter the file and press `1` on the line (nothing happens)

However, if I stage that change and open that file in tig, I can unstage that line with `1`.

I tried commenting out my whole `.tigrc` but this still happen.

Do you know what could be the issue ?

Thanks in advance

**Comment by edi9999** [comment]
Strangely, on other repos, the `1` shortcut works on some of the lines, but not all of them

**Comment by edi9999** [comment]
I think they are multiple bugs here, because on one of the repo, commenting out `wrap-lines = true` in my ~/.tigrc solved the problem.

I also tried rolling back to tig version 2.1.0, and the problem with TEST_HELLO_REPO is still there.

**Comment by jonas** [comment]
The test case you mentioned should be fixed. Please test.

I marked staging for wrapped lines as "not supported". If you really need this feel free to open a new ticket.

**Comment by edi9999** [comment]
Ok,

I have disabled wrapped lines in my tigrc, so I'm going to report if I see any other cases where `1` or `u` do not work.

Thanks again for the change, really nice tool and very good support !
