### ISSUE TITLE
Use mailmap

### ISSUE THREAD

**Issue by mmehra** [jonas/tig#411]
tig does not seem to be honouring .mailmap file. Any plans on supporting it?

**Comment by jonas** [comment]
Yeah, I had planned that since my diku.dk mail address got closed. Glad I finally got around to finishing this. See the NEWS file for instructions.

**Comment by ypid-geberit** [comment]
Works nicely, thanks. Maybe worth making `set mailmap = yes` the default?

**Comment by koutcher** [comment]
@ypid-geberit, `set mailmap = yes` has already been made the default in tig-2.5.4.
