### ISSUE TITLE
2.1.1 %(branch) is blank when branch is checked out

### ISSUE THREAD

**Issue by colinkahn** [jonas/tig#416]
As the title says, when I run a command using `%(branch)` on a branch in branch view when it's checked out it's replaced with nothing. 

Example:

`bind branch     >    !?git push origin %(branch)`

If I run the command using `>` on a checked out branch I just get: `git push origin`, if I do it on a branch that isn't checked out it replaces `%(branch)` with the correct value.

**Comment by jonas** [comment]
Thanks for reporting this. Easily reproduced.
