### ISSUE TITLE
2.1.1 Redraw issues when used with TMUX

### ISSUE THREAD

**Issue by colinkahn** [jonas/tig#423]
When using tig in a tmux pane and resizing it to be larger, tig doesn't properly redraw itself. Similarly if the pane is resized because the terminal becomes larger the same thing happens.

Resizing works fine when not using tmux.

**Comment by colinkahn** [comment]
This seems to be an issue with iTerm, using the OS X Terminal I don't have this problem.

**Comment by jonas** [comment]
I can reproduce this in iTerm. Running inside tmux the problem actually disappears.
What version of tmux and iTerm are you using?

**Comment by colinkahn** [comment]
I was using:

tmux 1.9a 
iTerm 2.1.4

Upgraded to tmux 2.1 and the problem in tmux has gone away.
