### ISSUE TITLE
Refresh mode not working

### ISSUE THREAD

**Issue by HageMaster3108** [jonas/tig#430]
Hi,

refresh mode is not working at all right now - using tig 2.0.3 on os x (retrieved via brew).
My .tigrc looks like this:

```
set refresh-mode = periodic
set refresh-interval = 5
```

Also tried the "auto" mode.

Tickets #389 and #301 seem to indicate that it is related to large repos? I can't confirm that. I have just setup a clean empty repo with just a single text file and can't get it to work.

Cheers,
Patrick

**Comment by geakstr** [comment]
Same for me. OS X 10.10.5, git 2.3.2, tig 2.1.1.

**Comment by jonas** [comment]
Yes, this is definitely broken.

**Comment by nevik** [comment]
@jonas, is there any way we can provide useful debugging info for this issue?

The auto-refresh would be the "killer feature", as it were, to make me use tig.

I'm currently on OS X 10.11 with `tig-2.1.1 (built Sep 13 2015)` (installed via homebrew).

**Comment by napcae** [comment]
Can confirm, does not work. If I can provide any information, please tell me how.
```
$ brew info tig
tig: stable 2.1.1 (bottled), HEAD
Text interface for Git repositories
http://jonas.nitro.dk/tig/
/usr/local/Cellar/tig/2.1.1 (8 files, 428K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tig.rb
==> Dependencies
Recommended: readline ✔
==> Options
--with-docs
        Build man pages using asciidoc and xmlto
--without-readline
        Build without readline support
--HEAD
        Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
```
SystemInformation:
````
$ archey

                 ###                  User: napcae
               ####                   Hostname: butterfinger
               ###                    Distro: OS X 10.11.1
       #######    #######             Kernel: Darwin
     ######################           Uptime: 11:09  up 5 days,  8:41, 1 user, load averages: 2,19 2,16 2,18
    #####################             Shell: /bin/bash
    ####################              Terminal: screen-256color iTerm.app
    ####################              Packages: 149
    #####################             CPU: Intel Core i5-4258U CPU @ 2.40GHz
     ######################           Memory: 8 GB
      ####################            Disk: 95%
        ################              Battery: 54,27%
         ####     #####               
```
tigrc:
```
$ less ~/.tigrc
      1 set refresh-mode = auto
/Users/napcae/.tigrc (END)
```

**Comment by sevagh** [comment]
Is this only an OSX problem? Refresh doesn't seem to be working for me on Linux (Fedora).

**Comment by geakstr** [comment]
@jonas, can you indicate where this functionality implemented in sources? I can try to research this problem.

**Comment by vaygr** [comment]
Can confirm that's still valid for **2.2.1** on Linux.

**Comment by jonas** [comment]
Yes, didn't get around to looking at this issue yet.

**Comment by sevagh** [comment]
If you could give me a clue on where to start looking in the source code, I'd like to attempt a fix.

**Comment by jonas** [comment]
@sevagh That would be great. The main logic is inside `src/watch.c`

**Comment by mnarrell** [comment]
Any update here?

**Comment by spytheman** [comment]
I've just made a pull request for this issue: https://github.com/jonas/tig/pull/591 .

**Comment by frontsideair** [comment]
Can we get a release too? ☺️

**Comment by jonas** [comment]
@frontsideair The fix has been release in https://github.com/jonas/tig/releases/tag/tig-2.2.2

**Comment by timotheecour** [comment]
could we reopen?

this doesn't work reliably at all. It seems to work for the 1st 2 or so edits, then doesn't refresh when a file is updated again.

 tig --version
tig version 2.3.3

Distro: OS X 10.13.3

I tried both:
set refresh-mode = auto
and 
set refresh-mode = periodic
set refresh-interval = 5

**Comment by jonas** [comment]
@timotheecour Please create a new issue.
