### ISSUE TITLE
'd' in main view ignores selection when used with 'set cmdline-args = --all'

### ISSUE THREAD

**Issue by bchallenor** [jonas/tig#431]
When in the main view, it's useful to be able to use 'd' or 'enter' to interact with the highlighted commit.

However I recently wanted to make `--all` the default when opening tig, and I [found](http://stackoverflow.com/questions/31960316/tig-configuration-set-on-tigrc-all-as-default) that I could do this by adding `set cmdline-args = --all` to tigrc. Now it seems that the highlighted commit is ignored - instead 'd' and 'enter' always apply to the last commit on master.

Interestingly this doesn't happen when I run `tig --all` directly, instead of specifying it in tigrc. So I'm not sure if this is a bug, or if attempting to set `--all` with cmdline-args is an unsupported hack. (In which case is there a better way to do it?)

**Comment by jonas** [comment]
@bchallenor You should use `main-options` instead of `cmdline-args` for this. I've replied to the SO question.

**Comment by bchallenor** [comment]
Thanks @jonas! Shall I close this issue?

**Comment by jonas** [comment]
@bchallenor Done as part of the a commit to remove the option all together.
