### ISSUE TITLE
Handling really big repository

### ISSUE THREAD

**Issue by yhnavein** [jonas/tig#436]
Hi, 
Is it possible to avoid load of the all commits on opening `tig`?
I have a quite big repository with 32000 commits and `tig` is unusable for around 10-15 seconds, because it loads absolutely everything.

Screenshot attached.
![loading](https://cloud.githubusercontent.com/assets/516709/9642210/24155f78-51bb-11e5-9069-9fa27ce23143.png)

OS: `Linux Ubuntu 14.04`
TIG Version: `2.1`

**Comment by vivien** [comment]
See https://github.com/jonas/tig/blob/master/contrib/large-repo.tigrc

**Comment by yhnavein** [comment]
Thanks, @vivien.

That's fixing my problem :)
