### ISSUE TITLE
refresh-mode = period doesn't work when specifying --all on the command line

### ISSUE THREAD

**Issue by eresonance** [jonas/tig#441]
Using tig 2.1.1, running it as
`tig --all`
It doesn't seem to auto refresh regardless of what options are set in tigrc. Without the --all option, tig will auto refresh automatically as expected.

**Comment by whitesiroi** [comment]
Looks like I have similar issue http://stackoverflow.com/questions/33251436/tig-stucks-and-getting-black-screen-tig-centos
