### ISSUE TITLE
tig: No revisions match the given arguments. (unknown revision or path not in the working tree.)

### ISSUE THREAD

**Issue by ttohin** [jonas/tig#442]
From TIG_TRACE:
```
git rev-parse --no-revs --no-flags --all 
git rev-parse --flags --no-revs --all 
git rev-parse --symbolic --revs-only --all 
git rev-parse --git-dir --is-inside-work-tree --show-cdup --show-prefix HEAD --symbolic-full-name HEAD 
git config --list 
git ls-remote /repo/.git 
git log --encoding=UTF-8 refs/heads/A refs/heads/B refs/heads/master
--porcelainrefs/remotes/origin/C -zrefs/remotes/origin/D  
--untracked-files=norefs/remotes/origin/E  
```

I'm on master and I don't understand where tig takes branches A and B from, because I removed them locally. I expect that it should be just like this:
```
git log --encoding=UTF-8 refs/heads/master
```

If I execute git log manually:
```
#: git log --encoding=UTF-8 refs/heads/A refs/heads/B refs/heads/master
--porcelainrefs/remotes/origin/C -zrefs/remotes/origin/D  
--untracked-files=norefs/remotes/origin/E  

fatal: ambiguous argument 'refs/heads/A': unknown revision or path not in the working tree.
```

**Comment by jonas** [comment]
How do you start tig? Any special arguments?

**Comment by ttohin** [comment]
no. just tig

**Comment by ttohin** [comment]
by the way: macosx and tig 2.1.1

**Comment by jonas** [comment]
I didn't notice the `--all`. What happens if you run `git log --all`?

It looks like tig might be parsing the output of `git rev-parse --symbolic --revs-only --all` incorrectly. It would be better to treat `--all` so that the argument is passed directly to `git-log`

**Comment by ttohin** [comment]
So. I managed that I had alias ```tig="tig --all"``` and tig without arguments works correctly. But I still need in the option ```--all```
By the way ```git log --all``` works correctly.

**Comment by ttohin** [comment]
```tig --all``` stopped working after we added 10000 tags into the repository. Maybe it is because of memory corruption or small buffers to parse tags.

**Comment by jonas** [comment]
I think it is because tig tried to add all 10k tags to the command line and
something breaks. I'll try to special case `--all` to not resolve all
references.

On Mon, Oct 5, 2015 at 4:37 AM, Anton Simakov <notifications@github.com>
wrote:

> tig --all stopped working after we added 10000 tags into the repository.
> Maybe it is because of memory corruption or small buffers to parse tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/442#issuecomment-145463578>.
>



-- 
Jonas Fonseca

**Comment by ttohin** [comment]
Any updates? By the way: output of ```git ls-remote``` contains 20k lines.

**Comment by jonas** [comment]
No, didn't have a chance to look at it yet

**Comment by jonas** [comment]
@ttohin Sorry for the long wait. I've added a special case for `--all` when parsing arguments.
