### ISSUE TITLE
Show untracked files with a stash that includes them

### ISSUE THREAD

**Issue by blueyed** [jonas/tig#443]
When using `git stash [-u|--include-untracked]` to create a stash, the untracked files are not displayed with `tig stash`.

According to http://stackoverflow.com/a/12681856/15690 they are stored in the 3rd parent of the stash commit, e.g. `stash@{0}^3`.

It would be nice if tig would display them.

**Comment by jonas** [comment]
I think the best would be to present "a stash" similar to the status view with three sections, so instead of a diff subview it would be a status subview, where diff can then be shown for each section or files. This would also fix #328.

**Comment by moll** [comment]
Perhaps as a temporary solution we could just have Tig append the diff of untracked files at the end of the modified files? It's a little misleading to see nothing for stashes that only have untracked files in them.

**Comment by nickspoons** [comment]
It's also easy to _lose_ stashed, untracked files. It'd be really nice to have them listed so we can see at a glance if the untracked files we're looking for are in the stash.

**Comment by koutcher** [comment]
I assume that, by now, everyone needing this feature is using `git config --global stash.showIncludeUntracked true` that was introduced since the issue was created and that it can be closed.
