### ISSUE TITLE
Potential bug in below_commit()

### ISSUE THREAD

**Issue by proski** [jonas/tig#446]
GNU Autoconf defaults to the rather poor "CFLAGS = -g -O2" without any warning options. One warning may indicate a real bug:
<pre>
src/graph-v2.c: In function ‘below_commit’:
src/graph-v2.c:628:11: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
  if (!pos == graph->prev_position)
           ^
</pre>
Indeed, it's strange to compare a boolean value to a position, which is likely integer.

**Comment by jonas** [comment]
Thanks, I finally got around to updating my XCode version and fixed this issue in cf74a8ce3854e09e66a9df3680ee1e350ace91c6.
