### ISSUE TITLE
Search by author name and commit name simultaneously

### ISSUE THREAD

**Issue by rominf** [jonas/tig#448]
I want to search in a big repository (https://github.com/saltstack/salt) by author name ("Roman Inflianskas") and by commit name ("zypper") simultaneously.

I've tried to make this from the main view by using regex:
```
.*Roman Inflianskas.*zypper.*
```

But this doesn't work.

How can I do that?

**Comment by rominf** [comment]
OK, I remembered about piping to tig:
```
git log --author="Roman Inflianskas" | tig
```

**Comment by jonas** [comment]
@rominf `tig --author="Roman Inflianskas"` also works

**Comment by rominf** [comment]
Oh, thank you, didn't know that, that's even better.

**Comment by andys8** [comment]
@jonas Hmm, is this feature currently still working? Am I doing something the wrong way?

```shell
git log --author andreas
[..] // lots of output
```

```shell
tig --author andreas
tig: No revisions match the given arguments.
```

```shell
tig --version
tig version 2.5.0
ncursesw version 6.2.20200212
readline version 6.3
```

**Comment by koutcher** [comment]
tig's command line parser is quite primitive, you have to use `tig --author=andreas`.

**Comment by andys8** [comment]
@koutcher Ahh, thanks for the hint. I've totally overseen this difference.
