### ISSUE TITLE
Non-helpful message with problematic gitconfig

### ISSUE THREAD

**Issue by alexkiousis** [jonas/tig#451]
Hi,
if you have garbage on your gitconfig tig outputs this:
```
  alexk:~/bin/puppet$ tig
  tig: Not a git repository
```
Which is misleading:
```
  alexk:~/bin/puppet$ git status
  fatal: bad config file line 1 in /home/alexk/.gitconfig
```
Is there any way this can be detected?

**Comment by jonas** [comment]
Somewhat related with #445, basically propagate git command stderr if possible

**Comment by alexkiousis** [comment]
Sorry forgot about this on. You are right, i'm closing this.

**Comment by lunakid** [comment]
I get the error with a repo already having a commit, `git status` is clean. But #451 has been closed -- anyone else having this? Should we reopen that one then? Or what's going on? (Version 2.37, git and tig from the same portable package.)
