### ISSUE TITLE
Missing support for git-worktree

### ISSUE THREAD

**Issue by Oblomov** [jonas/tig#458]
The fix to issue #437 for the support of git-worktree in `tig status` is not sufficient in general. For example, when in a secondary worktree, `tig` will fail to visualize refs.

The reason for this is that when the worktree feature is in use, there is not a single repository git dir: there is one for the worktree-specific files and one (the one of the main repository) for everything else.

As a result, it is not possible to “find” things by just concatenating (`%s/%s`) the `repo.git_dir` with whatever path is found: instead, `git rev-parse --git-path stuffWeWantThePathOf` should be used for every `stuffWeWantThePathOf`.

A quick hack would be to add a `repo.main_git_dir` entry to be used for anything that is not found in the (secondary) git dir (which is almost everything outside of `index` and `HEAD`), but the proper solution would be (sadly) to invoke a `git rev-parse --git-path` for everything 8-/

**Comment by roidelapluie** [comment]
:+1:

**Comment by netei** [comment]
+1

**Comment by jonas** [comment]
Can you help me come up with a small script to create a test case? I am not using worktrees, so I don't know how to set up such a test repository and how to reproduce the problem you are describing.

**Comment by mickeyh** [comment]
To reproduce the failure to visualize references make a temporary directory and inside of it run:

```bash
mkdir main_repo
cd main_repo
git init .
echo 'contents' > file
git add file
git commit -m 'A commit.'
git worktree add ../worktree
```

Running `tig` inside of the `main_repo` folder will open the main Tig screen will correctly show refs (you should see both `[master]` and `[worktree]` refs). But running `tig` inside of the `worktree` directory will not show refs.

**Comment by jonas** [comment]
I'm not able to reproduce this as of today's `master` branch (0ace5cd61ecada9b2b3fcb45539388eac291294b).
