### ISSUE TITLE
"Press Enter to continue" after a commit message

### ISSUE THREAD

**Issue by solarsailer** [jonas/tig#463]
Hello,

I don't know if it's tig's problem or Vim or git, but when I commit my changes in the status view, tig asks me to press enter to go back in the status view after writing the commit message:

![image](https://cloud.githubusercontent.com/assets/478621/11693533/b359282c-9ea5-11e5-931e-78954e85e6a5.png)

Is there a way to disable this behavior? I want to re-open the status view ASAP without my intervention. I can't find a way to specify this (either in my `.tigrc` or somewhere else).

Thanks.

**Comment by jonas** [comment]
Right now there's no way to disable it. We can add a new open flag for user-defined commands. Maybe `>` as the opposite of `<` which currently means "exit Tig after command". This would allow you to write:

    bind generic C >git commit

**Comment by solarsailer** [comment]
What would it mean exactly ?

```
>     Re-open Tig instantly in the last displayed view after executing the command.
```

Something like that? Would be perfect. :)

**Comment by DiegoPomares** [comment]
I use difftool (vimdiff) to check diffs and the message annoyed me. Here's the pull request that implements >

https://github.com/jonas/tig/pull/738
