### ISSUE TITLE
Segfault when hitting return in empty file search

### ISSUE THREAD

**Issue by quchen** [jonas/tig#464]
Tig 2.1.1 segfaults when I hit return in an empty file search on multiple different computers.

Assuming default settings, this is reproducible by

1. Open tig
2. Hit `f`to open file search
3. Enter stuff until the list of found files is empty
4. Hit return

**Comment by konnykonny50** [comment]
I also use tig 2.1.1 and have the same problem. But it seems like it got fixed in the current version here on GitHub.

**Comment by jonas** [comment]
Yes, this was fixed in b9fa048e20e72bc5b18365d7fe3e4361f6d99bb1.

On Wed, Dec 30, 2015 at 6:54 AM, konnykonny50 <notifications@github.com>
wrote:

> I also use tig 2.1.1 and have the same problem. But it seems like it got
> fixed in the current version here on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/464#issuecomment-167985785>.
>



-- 
Jonas Fonseca

**Comment by quchen** [comment]
Alright, thanks everyone!
