### ISSUE TITLE
Fuzzy search in the tree view

### ISSUE THREAD

**Issue by samiraguiar** [jonas/tig#465]
Any plans to add fuzzy search to look for files in the tree view mode?

**Comment by jonas** [comment]
Did you try the file finder view? It is new in version 2.1.1 and opens automatically when pressing `f` and no file has been selected.

https://asciinema.org/a/18525

**Comment by samiraguiar** [comment]
Yeah, that's exactly what I wanted.
Sorry about that, I'm stuck with Windows so I was using Cygwin's build (version 2.0).
BTW, I've managed to successfully build and install version 2.1.1 under Windows 10 64-bit with Cygwin. The required packages were gcc, make, libiconv-devel and libncurses-devel. After that, running `./configure`, `make` and `make install` went smooth and everything seems to be working so far.

**Comment by jonas** [comment]
Feel free to submit a patch to the INSTALL docs if you want.

I added
https://github.com/jonas/tig/blob/master/contrib/config.make-CYGWIN_NT-6.1
to automatically have `make` do the right thing. Not sure if that file
works on Windows 10. It uses `uname -s`

On Mon, Jan 4, 2016 at 11:09 PM, samiraguiar <notifications@github.com>
wrote:

> Yeah, that's exactly what I wanted.
> Sorry about that, I'm stuck with Windows so I was using Cygwin's build
> (version 2.0).
> BTW, I've managed to successfully build and install version 2.1.1 under
> Windows 10 64-bit with Cygwin. The required packages were gcc, make,
> libiconv-devel and libncurses-devel. After that, running ./configure, make
> and make install went smooth and everything seems to be working so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/465#issuecomment-168891098>.
>



-- 
Jonas Fonseca

**Comment by samiraguiar** [comment]
Done on #468

**Comment by jonas** [comment]
Awesome, thanks.
