### ISSUE TITLE
Split pane is drawn only 3 chars wide

### ISSUE THREAD

**Issue by joshma** [jonas/tig#467]
I just upgrade from 2.0.2 to 2.1.1, and when viewing split pane the right pane is only 3 chars wide. As an example:

![image](https://cloud.githubusercontent.com/assets/64739/12160048/ef4ed040-b49c-11e5-99c7-a64bfc395b43.png)

Is this something misconfigured, maybe a bug?

**Comment by joshma** [comment]
Hm, not sure what's going on, but after a brew update and re-install of tig, I'm back on 2.1.1 and it's working again.

**Comment by jonas** [comment]
This is a duplicate of #407 and was fixed by Homebrew/homebrew#44055
