### ISSUE TITLE
Tig dies with error message when spamming G in main view

### ISSUE THREAD

**Issue by h3xx** [jonas/tig#470]
Tig version: 88962f1901344caf27a4355c954bdcfd8108e035
Git version: 2.6.4
Slackware Linux (x86_64)
Xterm

## Steps to reproduce:

1. Clone any git repository with a fair amount of history (jonas/tig works nicely).

    $ git clone https://github.com/jonas/tig.git
    $ cd tig

2. Increase X11 keyboard repeat rate to something quick but manageable:

    $ xset r rate 145 45

3. Open tig to the main view inside the git repo:

    $ TIGRC_USER=/dev/null tig

4. Spam <kbd>G</kbd> a few times (hold down <kbd>Shift</kbd>+<kbd>g</kbd>)

## Outcome:

Tig flashes a few times, then exits back to the prompt with the following error message:

> tig: No revisions match the given arguments.

The flashes are because it's executing `:toggle commit-title-graph` and redrawing the digraph.

## Trace output:

    git rev-parse --git-dir --is-inside-work-tree --show-cdup --show-prefix HEAD --symbolic-full-name HEAD 
    git config --list 
    git show-ref --head --dereference 
    git log --encoding=UTF-8 --topo-order --date=raw --parents --no-color --pretty=format:commit %m %H %P%x00%an <%ae> %ad%x00%s -- 
    git status --porcelain -z --untracked-files=no 
    git log --encoding=UTF-8 --topo-order --date=raw --parents --no-color --pretty=format:commit %m %H %P%x00%an <%ae> %ad%x00%s -- 
    git status --porcelain -z --untracked-files=no 
    git log --encoding=UTF-8 --date=raw --parents --no-color --pretty=format:commit %m %H %P%x00%an <%ae> %ad%x00%s -- 
    git status --porcelain -z --untracked-files=no 
    git log --encoding=UTF-8 --topo-order --date=raw --parents --no-color --pretty=format:commit %m %H %P%x00%an <%ae> %ad%x00%s -- 
    git status --porcelain -z --untracked-files=no

**Comment by jonas** [comment]
Thanks for reporting this. Should be fixed even if it is a strange corner case.

**Comment by h3xx** [comment]
Confirmed fixed. Tested version 3ce063120cc8137e2d028f0f64a2280c15ba411b (2016-04-19).
