### ISSUE TITLE
External command does not resolve %(file) from working directory

### ISSUE THREAD

**Issue by commonquail** [jonas/tig#473]
Wherever tig is started from, file paths always show as if tig were started from the Git root. Internal commands that operate on files (`e`) resolve the actual paths correctly, but external commands simply append the path from the root to the working directory.

Custom key bindings (`bind status p !ls %(file)`) also resolve correctly (which really isn't surprising).

I discovered this in the status view but it applies anywhere `%(file)` exists.

To reproduce:

0. Open tig anywhere below the Git root.
0. In any view that exposes `%(file)`, attempt to operate on it with an external command: `:!vim %(file)`.
0. Compare with internal command, e.g. `e` (edit).

**Comment by jonas** [comment]
Looks like a duplicate of #412 which has been fixed

**Comment by commonquail** [comment]
You're right. Sorry!

**Comment by jonas** [comment]
Thanks for checking.
