### ISSUE TITLE
Magenta tilde wrapped to next line, trashing the next line's color

### ISSUE THREAD

**Issue by RyuKojiro** [jonas/tig#474]
This is interestingly easily reproducible in the git history of [classic-wm's master branch](https://github.com/RyuKojiro/classic-wm/), you just need to scroll past the commit shown in the screenshot, and then scroll back up over it to get it to turn pink. However, your terminal needs to be exactly 158 columns wide when you do this. I've attached screenshots of it happening on OS X and NetBSD (both tig 1.2.1).
![tigbug](https://cloud.githubusercontent.com/assets/3972033/12534888/e80adc2e-c221-11e5-98ca-541f4e14b836.png)
![screen shot 2016-01-23 at 10 24 44 pm](https://cloud.githubusercontent.com/assets/3972033/12534889/f6297fae-c221-11e5-9d4e-988a33a99cad.png)

**Comment by RyuKojiro** [comment]
Realized how old 1.2.1 is, so I cloned tig and built it fresh just now. Slightly better result, but now getting a white lowercase i on the next line. I'm not sure where the ^C is coming from, I don't think that character is actually in the commit message, unless git show is hiding it.

![screen shot 2016-01-23 at 10 46 39 pm](https://cloud.githubusercontent.com/assets/3972033/12534922/7ab4ac48-c223-11e5-994d-a9b912a65c4d.png)

**Comment by jonas** [comment]
Looks like some unsanitized characters are written to the screen.
