### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by stweller** [jonas/tig#475]
I am trying to read some documentation, but http://jonas.nitro.dk/ seems to be down. Could you take a look?

Thanks!

**Comment by jonas** [comment]
OK, I might end up migrating the website and documentation to GitHub. In the meantime, documentation can also be read from here: https://github.com/jonas/tig/blob/master/doc/

**Comment by stweller** [comment]
Thanks!

**Comment by jonas** [comment]
It is back up.
