### ISSUE TITLE
Search bindings broken

### ISSUE THREAD

**Issue by nkouevda** [jonas/tig#476]
After 1be122802b50b31d3cb1402d06e7f649ae2386d8, when a previous search pattern exists, `:/` and `:?` do not set a new search pattern, and thus function like `n` and `N`. This breaks search bindings since they must use `:/` and `:?` instead of `/` and `?` (which still work). For example, the default `bind diff @ :/^@@` does not work correctly following a search for a different pattern.

**To reproduce**: Search `/foo` and then search `:/bar` (note `:/`, not `/`), for any distinct `foo` and `bar`.

**Output**: `Line X matches 'foo' (1 of N)` followed by `Line Y matches 'foo' (2 of N)`.

**Expected output**: `Line X matches 'foo' (1 of N)` followed by `Line Y matches 'bar' (1 of M)`.

**Comment by jonas** [comment]
I believe this is now fixed. Thanks for reporting this issue.
