### ISSUE TITLE
Add support for conditionally set an option

### ISSUE THREAD

**Issue by lifepillar** [jonas/tig#477]
I happen to use tig in environments having different color schemes (say, in different terminals or within NeoVim), and I would like tig to use different colors in the different situations. Tmux allows you to write something like this in `.tmux.conf`:

    if '[[ "$TERM_PROGRAM" =~ iTerm.app ]]' '<set option>'

I wonder whether a similar syntax might be supported by tig.

**Comment by netei** [comment]
You could create a bash file that would output the desired configuration depending on the environment, and use a function tig that would run : 

tig () {
    TIGRC_USER=<(/bin/generatetigrc.bash) \tig "$@"
}

I think adding ifs, is out of scope of tig, because you can do that easily by combining it with other programs (like I proposed)

**Comment by lifepillar** [comment]
Following your suggestion, I have ended up adding something along these lines to my `.bashrc`:

```
function tig {
  if [ "$TERM_PROGRAM" == "iTerm.app" ] ; then
    TIGRC_USER=$HOME/.tigrc-gruvbox command tig "$@"
  else
    TIGRC_USER=$HOME/.tigrc-solarized command tig "$@"
  fi
}
```

Each `.tigrc-*` file is as follows:

```
# Environment-specific configuration goes here
color title-focus color15 color8
# etc...

# Load common settings:
source ~/.tigrc
```

**Comment by netei** [comment]
Yes, this works well too !

**Comment by jonas** [comment]
@lifepillar Awesome, I'll see if I can integrate this into the docs

**Comment by blueyed** [comment]
@lifepillar 
I am looking for a solarized scheme for tig - do you use/have `.tigrc-solarized` still?
Found the following in your dotfiles only: https://github.com/lifepillar/dotfiles/blob/master/dot-tigrc

**Comment by lifepillar** [comment]
I was using this: [dot-tigrc-solarized](https://gist.github.com/lifepillar/2912d65344538d623f331a5f4d4ad8d1) (it's not in my public repo). It assumes that your terminal is using the Solarized palette, of course.

**Comment by blueyed** [comment]
@lifepillar 
Awesome, thanks!
Just tried it quickly - noticed that `color  title-blur    color10 color14` is off
![2019-03-26-200205_623x506_escrotum](https://user-images.githubusercontent.com/9766/55025869-11c83180-5002-11e9-8d4d-6aeb55e72e4c.png)
(tried both dark and light)

**Comment by lifepillar** [comment]
For me it looks like this:

<img width="557" alt="Screenshot 2019-03-26 at 20 33 15" src="https://user-images.githubusercontent.com/1193314/55027814-75ecf480-5006-11e9-9a8d-5e0dcc85c2ac.png">

Color 10 should be #586E75 and color 14 #93A1A1.

**Comment by blueyed** [comment]
Ah, I am using base16, to have the normal colors in a useful / normal range:
![2019-03-26-222751_308x287_escrotum](https://user-images.githubusercontent.com/9766/55034769-93c25580-5016-11e9-8a36-27e149d5e847.png)
![2019-03-26-222818_296x285_escrotum](https://user-images.githubusercontent.com/9766/55034770-93c25580-5016-11e9-93ac-b0d0e93ff32e.png)

Thanks again, this will be a good starting point!
