### ISSUE TITLE
is there a functionality to checkout to any commit? 

### ISSUE THREAD

**Issue by Wingie** [jonas/tig#481]
i've had to do that quite a few times today and was wondering if there was an alternative to copy-pastaing  the commit after i close tig.

**Comment by jcowgar** [comment]
Add something like this to your tigrc 

bind main c ?git checkout %(commit)

Making c whatever you want of course. This will prompt are you sure and then do it

**Comment by jonas** [comment]
Yes, this is best handled with custom key bindings.

**Comment by TamaHobbit** [comment]
it seems as if the default keybindings are already conflicted; In the help list, it shows that
C ?git checkout %(branch)
But in the status view, this is overwritten with:
C !git commit

**Comment by specious** [comment]
I'm curious why there isn't a default key binding for checking out commits.  It's one of the most common actions on a git repository.

**Comment by yorch** [comment]
Love Tig! been using for a couple of years, thank you!
But my 2c, I agree, this should be something that comes out of the box, instead of having to configured it on every machine (specially since I use tig in a bunch of linux servers, so it's a pain to have to sync a `tigrc` across all
