### ISSUE TITLE
Unbind the default quit key binding doesn't work

### ISSUE THREAD

**Issue by jcherqui** [jonas/tig#483]
The unbinding `bind main q none` in my .tigrc doesn't work.
It's work only with `bind generic q none`

**Comment by jonas** [comment]
Confirmed, looks like a regression.

**Comment by nkouevda** [comment]
@jonas Unfortunately ad71cae breaks a different use case:

I used to do this in order to bind `G` to `move-last-line` in all views:

```
bind generic G move-last-line
bind main G none
```

But now this results in `G` being completely unbound in `main`, regardless of the order of those lines.

There is of course this workaround:

```
bind generic G move-last-line
bind main G move-last-line
```

But this seems worse than falling through to `generic` bindings when view-specific ones are unbound.

**Comment by jonas** [comment]
Oops, forgot to put a test case for that. Will fix.

On Wed, Apr 27, 2016 at 2:36 PM, Nikita Kouevda <notifications@github.com>
wrote:

> @jonas <https://github.com/jonas> Unfortunately ad71cae
> <https://github.com/jonas/tig/commit/ad71caef1bd2cfb53cb49600ec1f6b8c60e6e23f>
> breaks a different use case:
>
> I used to do this in order to bind G to move-last-line in all views:
>
> bind generic G move-last-line
> bind main G none
>
> But now this results in G being completely unbound in main, regardless of
> the order of those lines.
>
> There is of course this workaround:
>
> bind generic G move-last-line
> bind main G move-last-line
>
> But this seems worse than falling through to generic bindings when
> view-specific ones are unbound.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jonas/tig/issues/483#issuecomment-215185424>
>



-- 
Jonas Fonseca

**Comment by jonas** [comment]
@nkouevda After giving it some more thinking the way to fix this would be to introduce an `unbind`.
