### ISSUE TITLE
Feature Request: File history view

### ISSUE THREAD

**Issue by ManiacViper** [jonas/tig#484]
Is it possible to have a view that displays git log history for a file.

Not sure if this exists already, I googled but didn't see this.

**Comment by XVilka** [comment]
Just call it like `tig some/file.c` for example to get the view of history for this file.

**Comment by ManiacViper** [comment]
nice one! thanks!

**Comment by vitalybe** [comment]
You add a binding that will allow you to jump easily between diff/status view to the history of the file, like so:

    bind diff H !sh -c "tig \"$(git rev-parse --show-toplevel)/%(file)\""
    bind status H !sh -c "tig \"$(git rev-parse --show-toplevel)/%(file)\""

**Comment by huangyingw** [comment]
is it possible for tig to do sth like this?
````
gitk --all -p --full-diff 
````

I want to see the file history across all branches, and even the history before rename(change file name from A to B, or delete, etc).
