### ISSUE TITLE
Control characters in commit messages

### ISSUE THREAD

**Issue by grawity** [jonas/tig#485]
Commit e75e9f39c95b in <http://anongit.freedesktop.org/git/xorg/driver/xf86-video-amdgpu> has an ASCII CR (`\r`) in its subject line, causing the remainder of the subject overlay the date/author columns. Maybe such control characters (i.e. 0x00–0x09, 0x0B–0x1F) should be shown escaped?

**Comment by h3xx** [comment]
This particular commit message causes strange behavior in tig.

The first line of the commit is:

>extend conditional group GBM_BO_USE_LINEAR`0x0d` over both usages

Tig displays this as:

> over both usagesional group GBM_BO_USE_LINEAR

Looks like the `\r` character is causing it to overwrite part of the line.

**Comment by jonas** [comment]
Thanks for reporting this. I extended the existing machinery for "normalizing" string before rendering them to also handle whitespace and control characters. Used a minified version of the referred repository as a test case.
