### ISSUE TITLE
unexpected "failed to read filename" error

### ISSUE THREAD

**Issue by gcb** [jonas/tig#487]
If you have the (sane) option to hide diff filename prefixes, tig will fail to find the filename for things like blame functionality.

How to reproduce:
1. set these settings
```
diff.mnemonicprefix=false
diff.prefix=false
diff.noprefix=true
```
2. open tig, open any commit, try to see a blame (b key default)

offending code is at https://github.com/jonas/tig/blob/master/src/diff.c#L469

here is how a diff looks like with those options, it hides the fake `a/` and `b/` path.

```
-- src/file.c
++ src/file.c
```

**Comment by jonas** [comment]
Looks like tig needs to learn to ignore prefixes. The main challenge will be to figure out which prefix to ignore, e.g. if one had `diff.noprefix=true` but not the other prefix options disabled.
