### ISSUE TITLE
Can I do an asychronous github push using tig?

### ISSUE THREAD

**Issue by varmanishant** [jonas/tig#489]
Currently I execute github pull/push as a blocking command using the `!command`. However I am wondering if I can make this asynchronous? It would be really nice to have asynchronous support these days for almost everything as its all over the web.

**Comment by jonas** [comment]
Asynchronous command could be cool where stdout/stderr would be shown in a pager, but I think this kind of functionality would belong in a "remote" view.

**Comment by varmanishant** [comment]
Thanks. Just curious what is a "remote" view? I mean we might need to have a split for showing up the stdin stdout and stderr I think a bit like how magit does it. I will try to read up on how this can be achived though I am not an expert coder.

**Comment by jonas** [comment]
Take a look at this issue comment, which discusses introducing a view for managing remotes: https://github.com/jonas/tig/issues/199#issuecomment-23784683

**Comment by jonas** [comment]
Please continue discussion on that issue.
