### ISSUE TITLE
greping in diff view only highlights first hit in a line

### ISSUE THREAD

**Issue by avivey** [jonas/tig#493]
eg, `tig show cf74a8ce3854e09e66a9df3680ee1e350ace91c6` (current head of tig) and grep for `graph` misses the second hit in these lines:
![image](https://cloud.githubusercontent.com/assets/1530242/14445048/d7c64856-fffe-11e5-9f1c-f1ca64ca6707.png)

**Comment by h3xx** [comment]
That's not a "grep" function you're reporting the issue in. It's using <kbd>/</kbd> to highlight and search through text in the diff view.

**Comment by h3xx** [comment]
I'm seeing this in the main view too, and pressing <kbd>/</kbd> <kbd>s</kbd> <kbd>Enter</kbd>:

![screenshot-2016-0421-1054](https://cloud.githubusercontent.com/assets/615684/14715812/eca0bc62-07af-11e6-82b7-7178ac48c3a3.png)

**Comment by jonas** [comment]
I lazily didn't implement highlighting of all matches when I added this feature. Should be fixed now.

**Comment by avivey** [comment]
:+1:  Thanks!
