### ISSUE TITLE
Green highlight problem with base16 colorscheme.

### ISSUE THREAD

**Issue by KuoE0** [jonas/tig#495]
I use [base16](https://github.com/chriskempson/base16) color scheme as my terminal colorscheme. And I found the highlight would be green and it made my eyes uncomfortable. See the following screenshot:

<img width="1680" alt="screen shot 2016-04-22 at 01 49 29" src="https://cloud.githubusercontent.com/assets/892413/14719043/7ac25538-082c-11e6-83bf-dfea92ee8bad.png">

And this problem also happened on Vim. Please see the following link: https://github.com/chriskempson/base16-vim#green-line-numbers.

And we can add `let base16colorspace=256` into `.vimrc` to fix it. Is there some solution to fix that?

**Comment by jonas** [comment]
You can change the [color of the cursor](https://github.com/jonas/tig/blob/3ce063120cc8137e2d028f0f64a2280c15ba411b/tigrc#L344) to something else by adding the following line to `~/.tigrc`:

    color cursor			white	red	bold

**Comment by KuoE0** [comment]
Oh..that's great! Thank you! 👍

**Comment by avatar-lavventura** [comment]
`color cursor            black   yellow bold` this one is also easy to read
