### ISSUE TITLE
how to show main view ordered by commit time?

### ISSUE THREAD

**Issue by FAKERINHEART** [jonas/tig#497]
When I merge a branch into another specific branch which both develop from the master, such as:
git merge a;
![qq 20160425174410](https://cloud.githubusercontent.com/assets/13352188/14780017/5f961978-0b0d-11e6-8c5d-a2002fb8c235.png)

I found that, in the main view of tig, for commits of the branch 'b'(HEAD now), the commits of branch 'a' are always ahead of the commit branch 'b'(HEAD) whether the commit time of the former are earlier than that of the latter, namely they are not ordered by commit time.
ps: For the log view, they are normally ordered by time.

Therefore, I wanna know how to show main view ordered by commit time. Or there is another alternative.

**Comment by jonas** [comment]
Tig sorts by topo order when graph rendering is enabled. You can change the
order in ~/.tigrc or by passing on of the commit order flags supported by
git-log for example --date-order

**Comment by FAKERINHEART** [comment]
Thank u~ @jonas

**Comment by jonas** [comment]
You're welcome
