### ISSUE TITLE
Bind shortcut to generic git command execution

### ISSUE THREAD

**Issue by vitalybe** [jonas/tig#498]
I've tried to do the following key binding:

`bind main <Ctrl-g> ?git "%(prompt)"`

However, when I entered as parameter `branch temp` that doesn't work as the resulting command is: `git "branch temp"`. I've tried to fix it by doing:

`bind main <Ctrl-g> ?"git %(prompt)"`

Running that with the same argument produces no result at all.

**Comment by jonas** [comment]
Try:

    bind main <Ctrl-g> ?sh -c "git %(prompt)"

**Comment by vitalybe** [comment]
Works thanks!
