### ISSUE TITLE
Bind command stops working when diff sidebar is open

### ISSUE THREAD

**Issue by vitalybe** [jonas/tig#499]
I have the following bindings:

`bind main <F4> !git difftool -d %(commit)^!`
`bind status <F4> !sh -c "git difftool -y \"$(git rev-parse --show-toplevel)/%(file)\""`

However, if I press **Enter** and the sidebar is visible, these bindings stop working.

The only solution that I see is making a `bind diff <F4>` but since these commands are different for `main` and `status`, it wouldn't really work.

Is there a workaround for that?

**Comment by jonas** [comment]
The `main` and `status` view use different sidebars (or subviews) for disabling the diff, so this can be solved by having:

    bind diff <F4> ... # binding for main's subview
    bind stage <F4> ... # binding for status' subview
