### ISSUE TITLE
Enhancement request: add very basic support to view svn and hg repos

### ISSUE THREAD

**Issue by rcampbel3** [jonas/tig#501]
I love tig! I love the ease with which I can browse code repository changes. When I have to work with a svn or hg repo, I really miss tig.

If there were some way to have tig be able to show a BASIC commit list comments for mercurial and subversion repositories, I would be ecstatic.

**Comment by jonas** [comment]
Sorry, this is out of scope. A workflow with `git-svn` will allow you to browse Subversion repos. I don't know if a similar tool exists for Mercurial.
