### ISSUE TITLE
Highlight line is split when running tig undex tmux

### ISSUE THREAD

**Issue by nvdv** [jonas/tig#502]
```
~ tig --version
tig version 2.1.1
```
![screen shot 2016-05-27 at 16 04 00](https://cloud.githubusercontent.com/assets/745431/15608791/cde66e2a-2424-11e6-857c-d544f12cc79f.png)

**Comment by Kdecherf** [comment]
It may be linked to $TERM and ncurses.

I see the same behavior when using `TERM=xterm tig` (or mutt for example) inside tmux but it disappears with TERM=screen.

(I always set TERM=screen* in my tmux sessions to avoid this behavior)

**Comment by nvdv** [comment]
Since it's know issue and there's workaround, I am closing this.
