### ISSUE TITLE
How to change local branch color on commit title?

### ISSUE THREAD

**Issue by alfaproject** [jonas/tig#507]
I've been playing around a bit with .tigrc, but so far didn't get very far.
I'm trying to change the color of the local branch bit of the commit title, because for some reason it shows black on yellow with my base16 scheme setup: http://puu.sh/ps6Vt/81cf5b802a.png

Tried plenty of things without avail. Would appreciate any help.

**Comment by edentsai** [comment]
try this
```
color main-head yellow default
# or
color main-ref yellow default
```

Reference: http://jonas.nitro.dk/tig/tigrc.5.html

**Comment by jonas** [comment]
@alfaproject Tig also reads colors configured for git so also check if `git config --list` contains `color.branch.current`. You can disable this feature by adding the following line to `~/.tigrc`:

    set git-colors = none
