### ISSUE TITLE
Issue with search and terminal resize

### ISSUE THREAD

**Issue by koutcher** [jonas/tig#515]
Tig version: 2.2

If you perform a search while displaying a commit in vertical split mode, tig exits right away with glibc complaining about a double free. The same operation works fine with tig-2.1.1.

Looks like at least view->width is not initialized, so problem could come from changes in apply_vertical_split implementation for commit 39acb5a.

**Comment by koutcher** [comment]
Problem occurs with ncurses-5.4 but not with ncurses-5.7.

**Comment by koutcher** [comment]
Problem is actually not linked to vertical split nor to ncurses version. 

Crash occurs when the terminal is resized while a search is in progress.  It is systematic with RHEL4 but could not be reproduced with RHEL6. 

Valgrind shows that the problem comes from malloc in draw_view_line_search_result (introduced with commit bef366c in Tig 2.2). The allocated buffer is 1-byte too short.

**Comment by jonas** [comment]
Fixed by #550
