### ISSUE TITLE
it is not right show Chinese in git log by tig!!

### ISSUE THREAD

**Issue by dwyangd** [jonas/tig#520]
my os is centos 6.5 !
what could i do?
hope help!
thank you

**Comment by peterhoeg** [comment]
I'm not involved with this project, but I'm pretty sure that the developer would want some additional details in order to be able to help you. I suggest you create a new repository and make a few commits that highlight the problem. Then share the link here.

**Comment by Lluvio** [comment]
@dwyangd it works well with tig 2.0.2

**Comment by jonas** [comment]
Chinese (and UTF-8 representable text) is supported as long as Tig is compiled with ncursesw (ncurses with wide character support).

Closing this for now. @dwyangd if you manage to reproduce with an ncursesw-based build of tig please update the issue.
