### ISSUE TITLE
Changed name propagates to old commits

### ISSUE THREAD

**Issue by petersohn** [jonas/tig#526]
If the name of a user changes, the new name will be displayed for all commits corresponding to the same e-mail address.

Consider the following repository. I created two commits. `tig` output is:

```
2016-09-19 16:44 Péter Szabados o [master] Second
2016-09-19 16:43 Péter Szabados I Initial commit
```

Now I change the name of my user (but not the e-mail address) of my user:

``` bash
git config user.name 'Foo Bar'
```

After the next commit, `tig` shows the new user name for all commits.

```
2016-09-19 16:45 Foo Bar o [master] Changed username
2016-09-19 16:44 Foo Bar o Second
2016-09-19 16:43 Foo Bar I Initial commit
```

If I checkout the previous ("Second") commit, then `tig` shows the old user name, as before.

This is inconsistent with the behavior of `git status`, which shows the actual user name for each commit instead of the newest name for all commits.

```
commit 4e929703b957fe0f4cea807ec9b063b5829f6061
Author: Foo Bar <peter.szabados@ericsson.com>
Date:   Mon Sep 19 16:45:20 2016 +0200

    Changed username

commit 146fdfcd044adf97c562aacc3f931377d67913ae
Author: Péter Szabados <peter.szabados@ericsson.com>
Date:   Mon Sep 19 16:44:28 2016 +0200

    Second

commit 6d42a2c099929e568a3c56f9cdc5d58b22871083
Author: Péter Szabados <peter.szabados@ericsson.com>
Date:   Mon Sep 19 16:43:03 2016 +0200

    Initial commit
```

**Comment by jonas** [comment]
Fixed by #547
