### ISSUE TITLE
custom commit command

### ISSUE THREAD

**Issue by select** [jonas/tig#528]
Is it possible to add a custom commit command? I recently discovered https://github.com/commitizen/cz-cli and like the idea of automatically creating releases with semantic versiong created from structured commit messages. I did not find an option to change the commit command so I wanted to check if it's possible.

**Comment by jonas** [comment]
The default commit command is defined in the system tigrc as

    bind status	 C	!git commit

To change it, add the above to you `~/.tigrc` file and modify what is after `!`.
