### ISSUE TITLE
scroll-half-page-up and scroll-half-page-down

### ISSUE THREAD

**Issue by amigrave** [jonas/tig#531]
It would be cool to have `scroll-half-page-up` and `scroll-half-page-down` for scrolling, like we have `move-half-page-up` and `move-half-page-down`. Scrolling code by page makes it so easy to get lost.

As a workaround, let's say that I want to have a binding in order to scroll by chunk of 8 lines, how could I do that ?

```
bind    diff        <C-PgUp>       none
bind    diff        <C-PgUp>       <repeat N times scroll-line-up ???>
bind    diff        <C-PgDown>     none
bind    diff        <C-PgDown>     <repeat N times scroll-line-down ???>
```

**Comment by hasufell** [comment]
This is important, imo. Git is about viewing diffs. Diffs are huge. I need to have proper navigation capabilities.

**Comment by amigrave** [comment]
@koutcher Thanks a lot for this !
