### ISSUE TITLE
How to see commit message for annotated tag

### ISSUE THREAD

**Issue by Mondane** [jonas/tig#535]
In my repository, I have several annotated tags but I can't seem to find a way in tig to see the message that goes with such a tag. How can I achieve reading that message?

**Comment by jonas** [comment]
You can use `tig show <tag>` to see the message. Under the hood it just shows the output of `git show <tag>`. There's not currently a way to show this information from within Tig.

For example in the Tig repo `tig show tig-2.2` will render something like the following:

```
tag tig-2.2
Tagger:     Jonas Fonseca <jonas.fonseca@gmail.com>
TaggerDate: Wed Aug 10 22:38:25 2016 -0400

tig version 2.2
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEABECAAYFAler5SEACgkQJfQykjqsXHeoQwCfdSu2YU7v4jsvX0kglWnTyK6c
+8EAn1H+r1ONfRrire/2NCkWiVWpAllv
=AcMP
-----END PGP SIGNATURE-----

commit bba76f5141aaad75bde15dadc8a0f258fda86fe0
Refs: <tig-2.2>, tig-2.2-19-gdfa26fd
Author:     Jonas Fonseca <jonas.fonseca@gmail.com>
AuthorDate: Wed Aug 10 22:38:25 2016 -0400
Commit:     Jonas Fonseca <jonas.fonseca@gmail.com>
CommitDate: Wed Aug 10 22:38:25 2016 -0400

    tig-2.2
---
 Makefile          |  2 +-
 NEWS.adoc         |  4 ++--
 tools/aspell.dict | 14 ++++++++++++--
 3 files changed, 15 insertions(+), 5 deletions(-)
```

**Comment by mgenereu** [comment]
Bummer.  I just had this conversation with someone and thought `tig` would have it.  `git log` falls short all the time and `tig` picks up the slack!
