### ISSUE TITLE
issue with prepare-commit-msg hook

### ISSUE THREAD

**Issue by rsmarshall** [jonas/tig#543]
I'm trying to edit my pre commit message hook to add the [refs branchname]. What I have works fine, though when I am in tig it now commits, even if i quit out of the commit message window.

Any ideas on how to stop this happening?

**Comment by rsmarshall** [comment]
It seems if i quit vim  with ':cq:' and then ctrl c to get out of the continue window in tig it doesn't commit. :) Is this the best way? If so then feel free to close.

**Comment by jonas** [comment]
Are you using the default keybinding?

    bind status     C       !git commit

If prepare-commit-msg adds text to the commit buffer then Git will use whatever text is there when Vim exits as the commit message. Normally when the commit buffer is empty it won't commit anything. So I think this is not an issue with Tig but more with using prepare-commit-msg

**Comment by rsmarshall** [comment]
Thanks. :) 

I assumed that was the case, just figured someone here might have seen the same issue as a tig user and not using command line to commit.

It didn't really warrant an issue, more a question.

Thanks again.
