### ISSUE TITLE
diff-highlight: uses italic instead of reverse with TERM=tmux-256color

### ISSUE THREAD

**Issue by blueyed** [jonas/tig#548]
When using `set diff-highlight = /usr/share/git/diff-highlight/diff-highlight` I've noticed that it will use italic instead of reverse inside of tmux, where I use `if-shell '[ "$TERM" = "linux" ]' 'set -g default-terminal "tmux"' 'set -g default-terminal "tmux-256color"'`.
When using `set -g default-terminal "tmux` explicitly, reverse is used correctly.

```
% infocmp tmux tmux-256color
comparing tmux to tmux-256color.
    comparing booleans.
    comparing numbers.
        colors: 8, 256.
        pairs: 64, 32767.
    comparing strings.
        setab: '\E[4%p1%dm', '\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m'.
        setaf: '\E[3%p1%dm', '\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m'.
```

**Comment by jonas** [comment]
I'm not sure there's a lot we can do about this in Tig since it relies on ncurses to apply the STANDOUT attribute. What do you propose?

**Comment by jonas** [comment]
The diff-highlight colors are configurable since #625 and #633 . This should allow you to set the colors to work in touch when 256 colors are enabled.
