### ISSUE TITLE
Is there a way to mark two commits and view the diff?

### ISSUE THREAD

**Issue by ShengYun** [jonas/tig#553]
In gitk there is this feature to mark a commit and diff "this->selected", is there a way to mark commits in tig and show the diff in diff mode?

also it would be great if there is a key to call `difftool` or `difftool -d`

**Comment by ShengYun** [comment]
I noticed that `git difftool -d` can be called by external commands and also https://github.com/jonas/tig/issues/219 mentioned that it will come later :)

But still don't know how to mark a commit.

Will update this issue if I found something

**Comment by jonas** [comment]
Regarding `difftool` this should be as simple as putting the following in `~/.tigrc`:

    bind main C !git difftool -d %(commit)

**Comment by jonas** [comment]
Will go ahead and close this one. Please follow #219 for external diff viewer support.
