### ISSUE TITLE
`--all` does not what the help says

### ISSUE THREAD

**Issue by matthiasbeyer** [jonas/tig#555]
If you call `tig --all` it does: `Display all branches:` (from `man tig`). This is _not_ what it does:

I have refs in `.git/refs/foo/` which are also shown - technically, these are also branches, but not semantically. Semantically, only things in `.git/refs/{remotes,heads,tags}` are branches.

After all, I'm not entirely happy with the semantics here. I would like to propose the following changes:

* Keep the `--all` flag and its current behaviour, change the documentation accordingly
* Introduce `--all-branches` or something like that to only show (semantical) branches
* Introduce another flag to show all `.git/refs/*` but _not_ the branches from the `{heads,remotes,tags}`.

What do you think?

**Comment by jonas** [comment]
I've updated the documentation using the wording from [`git-log(1)`](https://git-scm.com/docs/git-log#git-log---all). Hopefully this makes it more clear what `tig --all` does.

You can pass any `git-log` flag you want to Tig and it should select and filter as if you called `git-log`. If you only want branches something like this should work:

    tig --branches

Given that `git-log` already has an extensive number of flags I'd prefer not to add any custom flags to Tig itself.

**Comment by matthiasbeyer** [comment]
Hm, this does not work for me, unfortunately. I mean, it also lists refs from `refs/remotes/upstream`, even when I pass `--exclude=refs/remotes/upstream/*`

**Comment by jonas** [comment]
I've pushed a fix for using `--exclude=refs/remotes/upstream/*` together with `--all`.
