### ISSUE TITLE
Empty stash diff when `mailmap = true` is set

### ISSUE THREAD

**Issue by smancill** [jonas/tig#556]
The diff view for stashs goes empty if I set this in my `.tigrc` (even when it is the only line in the file):

    set mailmap = true

It does not matter if there is a `.mailmap` file in the repository or not.

If I remove that line, I can see the diffs just fine. I tried on both OS X and Linux, same result.

    $ tig --version
    tig version 2.2.1

    $ git --version
    git version 2.11.0

**Comment by jonas** [comment]
Thanks for reporting. Should be fixed now.
