### ISSUE TITLE
Print external command output in the status bar

### ISSUE THREAD

**Issue by simark** [jonas/tig#557]
Is it possible to have an external command print something in the bottom status bar?  For example, I am thinking of enhancing the "copy sha1 to clipboard" example to have it print something to let the user know that the action was triggered:

    bind generic 9 !sh -c "echo -n %(commit) | xclip -selection c && echo Copied %(commit) to clipboard"

However, instead of hiding the tig interface and show the output along with "Press Enter to continue", it would be nice to show this in the status bar.  Is there any way to do this?

**Comment by jonas** [comment]
Fixed as of commit 4a3d90a
