### ISSUE TITLE
Lagging in huge project with many branch and commits 

### ISSUE THREAD

**Issue by yeungocanh** [jonas/tig#558]
I have a huge project with more than 40,000 commit and 200 branch.
And tig took 80s to init them and i have lagging that in waiting time.

How can i limit commit to track with tig ? 

Sorry for bad english

**Comment by jonas** [comment]
What version of Tig are you using?

**Comment by yeungocanh** [comment]
tig version 2.2.1-15-gcef17fc

**Comment by jonas** [comment]
@yeungocanh You can pass any argument that [git-log](https://git-scm.com/docs/git-log) supports to limit what tig shows. Some examples:

```sh
# Show 100 latest commits
tig -n 100

# Show commits for the last month
tig --since=1.month

# Show commits since version 10.0.0 and also show the boundary commit
tig tig --boundary v10.0.0..
```

**Comment by jonas** [comment]
In case you want to always limit to a certain number of commits you can then configure this in `~/.tigrc`:

```
set main-options               = -n 1000       # Show up to 1k commits
```
