### ISSUE TITLE
Irrelevant branches at the top of my main tig view

### ISSUE THREAD

**Issue by eran-** [jonas/tig#561]
I am using tig-2.2.1 with no ~/.tigrc and for some time now I'm having problems with my main tig view. For instance, I have a feature branch checked-out, but when I execute tig I see commits in release branch (that are even older than commits in my feature branch) at the top of the list, or even worse, I see others' feature branches that have nothing to do with my feature branch.

**Comment by jonas** [comment]
Closing as it turned out to be a shell alias containing `--all`
