### ISSUE TITLE
Diff, two or three columns

### ISSUE THREAD

**Issue by magicalbanana** [jonas/tig#564]
I'm new to tig and it's really awesome. This is a question and not a bug so feel free to close this if this is not the right place for this question.

How can I diff whilst viewing it in two columns? Especially when doing merge conflicts?

**Comment by jonas** [comment]
Tig doesn't support two or three column diffs.

- Two column diff view is tracked in #26
- Improved merge diff in #333 

Closing this as duplicate. Feel free to comment on the related tickets.
