### ISSUE TITLE
Feature Request: Display submodule commits for staged/unstaged changes

### ISSUE THREAD

**Issue by mhoff** [jonas/tig#569]
The `--submodule` feature wonderfully renders the diff for submodules like this:
```
 center_ball/src | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Submodule center_ball/src ef871ba..e364997:
  > Update snn_utils.
  > Replace package snn_utils with submodule.
  > Warn if nest.SetMaxBuffered is not available.
```

But when displaying staged or unstaged changes the output still looks as follows:
```
diff --git a/pattern_matching/src b/pattern_matching/src
index 3d58c84..2432564 160000
--- a/pattern_matching/src
+++ b/pattern_matching/src
@@ -1 +1 @@
-Subproject commit 3d58c848423dfa063e77ba05e72bb5e8db4dc945
+Subproject commit 2432564760a67bb7c4fdaa009808fe30b9b9db1d
```

I think it would be consistent (and very helpful) if `tig` would list the commit descriptions instead of showing the changed commit reference.

P.S. @jonas This is a great project. I use `tig` every day in my workflow. Thank you for your good work!

**Comment by jonas** [comment]
Thanks to @odnoletkov this should now be fixed. I rarely use submodules so haven't had a lot of motivation for fixing Tig in that respect.
