### ISSUE TITLE
[Feature request]: Options to display EOL type in diff

### ISSUE THREAD

**Issue by ocoka** [jonas/tig#573]
Sometimes it's important to see changes in end of line character, what from and to what.
For now I can't do this in **tig**, even if they shown in **git diff**
my **.gitconfig** contains
```
[core]
	#whitespace = cr-at-eol
	autocrlf = false
[color.diff]
	whitespace = red reverse
So they displays as **^M**
```

If I can do this by **diff-options**, it will be great
Or as a switch in **:options**

As I can understand **tig** ignores color's and line ending completely for now, since it has it's own highlight logic

**Comment by jonas** [comment]
Closing as duplicate of #552
