### ISSUE TITLE
[Feature request]: Need a way to display current values of internal variables (commit, file, etc...)

### ISSUE THREAD

**Issue by ocoka** [jonas/tig#574]
It can be very convinient to see the current state of **tig** internal state variables then implementing custom command, and to understand when i can invoke it

**Comment by Daghall** [comment]
Is `:!echo %(commit), %(file)` good enough?

If you want a more comprehensive "var dump" you could make a custom command that prints them an in a pretty way. 😄

**Comment by ocoka** [comment]
Thanks) As I remember, really it's been a while, I want to do that when I do not know the name of variable )))

**Comment by Daghall** [comment]
All variables should be found [in the manual](https://github.com/jonas/tig/blob/master/doc/manual.adoc#browsing-state-and-user-defined-commands).

You can tab-complete names if you write a partial name `:echo %(<tab>`.

I made a custom command that prints every variable in the manual, except the `*args`:
```
bind generic x !sh -c "printf 'head = %(head)\\ncommit = %(commit)\\nblob = %(blob) \\nbranch = %(branch) \\nremote = %(remote) \\ntag = %(tag) \\nrefname = %(refname) \\nstash = %(stash) \\ndirectory = %(directory) \\nfile = %(file) \\nlineno = %(lineno) \\nlineno_old = %(lineno_old) \\nref = %(ref)\\ntext = %(text) \\nrepo:head = %(repo:head) \\nrepo:head-id = %(repo:head-id) \\nrepo:remote = %(repo:remote) \\nrepo:cdup = %(repo:cdup) \\nrepo:prefix = %(repo:prefix) \\nrepo:git-dir = %(repo:git-dir) \\nrepo:worktree = %(repo:worktree) \\nrepo:is-inside-work-tree = %(repo:is-inside-work-tree)'"
```

It's not pretty, but it seems to work. 😅

**Comment by ocoka** [comment]
Amazing, thx :smile: Think we can close that issue as resolved
