### ISSUE TITLE
tig is going in stdin mode when is stared from vim

### ISSUE THREAD

**Issue by svett** [jonas/tig#576]
Recently I was adopting `tig` in my vimfiles. However, if you run `:!tig --all` from vim command line, `tig` is started in pager mode.

**Comment by jonas** [comment]
I am not able to reproduce this. What version of Tig? Would also be helpful to know the OS and terminal.

**Comment by svett** [comment]
@jonas I cannot reproduce the issue anymore. I am closing the issue.
