### ISSUE TITLE
`set mailmap = true` is not read from config file

### ISSUE THREAD

**Issue by Ram-Z** [jonas/tig#578]
If I put `set mailmap = yes` in the config file, the option still does not seem to be set when tig is run. Subsequently running `:set mailmap = yes` works though.

**Comment by jonas** [comment]
Which view in Tig are you seeing this? `main` (with graph), `diff` or `log`?

**Comment by Ram-Z** [comment]
I don't seem to be able to reproduce this anymore. Closing.

Thanks

**Comment by jonas** [comment]
OK, thanks for testing.
