### ISSUE TITLE
request feature to use git diff tool to render diff

### ISSUE THREAD

**Issue by stephencheng** [jonas/tig#586]
in log or diff view, if cursor is at a file name, then allow user to press one key to trigger: git difftool to render the side by side git differences, and allow user to customise the diff tool or use default one configured in gitconfig file

**Comment by jonas** [comment]
This is definitely possible using a keybinding. You can put something like the following in your `~/.tigrc` file:

    bind diff D !git difftool %(commit) -- %(file)
    bind log D !git difftool %(commit) -- %(file)

**Comment by jonas** [comment]
Please use the suggested keybinding.
