### ISSUE TITLE
Auto update diff view while navigate in main view

### ISSUE THREAD

**Issue by mrleolink** [jonas/tig#588]
So I have this scenario with tig:

Open tig
-> press enter on an arbitrary commit
-> now I have main view on the left and diff view on the right
-> press tab to move focus back to main view
-> use j k to navigate up between commits in main view, but diff view doesn't get updated accordingly

Is there any ways to make diff view update accordingly when navigate in main view in above scenario?

**Comment by mrleolink** [comment]
ah, never mind
I figured it out, I can use <C-N> and <C-P> to do that :)

**Comment by pylipp** [comment]
Can you describe how you solved this issue?

**Comment by mrleolink** [comment]
@pylipp 

> Open tig
> -> press enter on an arbitrary commit
> -> now I have main view on the left and diff view on the right

-> Now don't press tab, instead just use `Ctrl-N` and `Ctrl-P` to navigate up and down, the diff view on the right will be updated accordingly

**Comment by pylipp** [comment]
Thanks! Can you tell me the version of tig you're using? Just noticed that I'm on 2.2

**Comment by mrleolink** [comment]
@pylipp 
`next` and `previous` I think
You can see them here: https://github.com/jonas/tig/blob/0684b8cb70fe01292d50d15c377fed6f29c9fcd1/tigrc#L215
