### ISSUE TITLE
Cannot always revert a chunk

### ISSUE THREAD

**Issue by camalolo** [jonas/tig#590]
Hello, sometimes I cannot revert a chunk.

-> run tig in my repo
-> press S to go to stage view
-> chose a file I want to do a partial revert on
-> split a chunk with \
-> press ! to revert the current new smaller chunk
-> tig does something, then the view resets to what it was before the attempted revert, nothing changed on the disk

My ~/.tigrc :

set vertical-split = false
set split-view-height = 80%
set ignore-space = all

tig version 2.0.2
git version 2.7.4

PS : Can I log all the git commands tig runs and maybe see the error output ?

**Comment by camalolo** [comment]
![peek 2017-04-20 17-35](https://cloud.githubusercontent.com/assets/331741/25224076/e48ae926-25ef-11e7-9c9f-eb3e3cdd83f4.gif)

**Comment by jonas** [comment]
Yes, you can get the trace of git commands by running:

    TIG_TRACE=trace-file tig

**Comment by jonas** [comment]
Took a closer look and this is indeed a limitation of how the stage view works. `set ignore-space = all` means that Tig cannot provide a meaningful diff to Git to revert the chunk. I'll try to come up with a way to refuse to work on the chunk level when `ignore-space` is != `no`.

**Comment by camalolo** [comment]
Thanks for your good work !
