### ISSUE TITLE
Untracked files: (not shown)

### ISSUE THREAD

**Issue by achikin** [jonas/tig#595]
I think I pressed something unexpected, or maybe it's the result of an update, but now I can't see untracked files in tig, instead it shows this:
```
Untracked files:
  (not shown)
```
How can I set up tig so it shows untracked files again?

**Comment by achikin** [comment]
I do remember that tig warned me about some parameter name change in some file like
`status-untracked-dirs` should be renamed, but I can't find the exact option name.

**Comment by achikin** [comment]
Reading through the source code I've found out that you've also added `set status-show-untracked-files = yes` config variable, which was missing in my tigrc. Untracked files are back as soon as I've added it to my tigrc.

**Comment by jonas** [comment]
Thanks for confirming.

**Comment by nemoDreamer** [comment]
@jonas Wouldn't `yes` be the default if it's not in our `~/.tigrc`?

**Comment by jonas** [comment]
@nemoDreamer Yes, it would be the default. The problem is that Tig won't read the internal defaults when a system tigrc exists. This permits full control of what options are read but breaks if a distribution doesn't update the system tigrc, which was the case for Homebrew.

**Comment by nemoDreamer** [comment]
Ah, makes sense, thanks!!
I guess I could pull down the system tigrc from this repo and overwrite mine. Shame Homebrew doesn't do that 😭

**Comment by jonas** [comment]
My advice is to remove the system tigrc (`/usr/local/etc/tigrc`) so Tig uses the internal one.
