### ISSUE TITLE
tmux copy doesn't work well with vertically split `tig`

### ISSUE THREAD

**Issue by timotheecour** [jonas/tig#596]
Not sure whether this belongs more to tmux or tig so mentioning in both:

https://github.com/tmux/tmux/issues/946

tig creates a vertical split but within a tmux pane, is there a way for tmux to detect this?
What would be a workaround for vertical-split tig?

https://www.dropbox.com/s/ztxnt057r5q1kow/Screenshot%202017-05-24%2013.14.55.png?dl=0

**Comment by koutcher** [comment]
Nothing can be done in tig either.
