### ISSUE TITLE
tig status not showing untracked files

### ISSUE THREAD

**Issue by voska** [jonas/tig#598]
I recently upgraded tig to 2.2.2 and now when I run `tig status` my untracked files do not show up. 

It was throwing the following error:
```
tig warning: /usr/local/etc/tigrc:90: status-untracked-dirs has been renamed to status-show-untracked-dirs
tig warning: Errors while loading /usr/local/etc/tigrc.
```

I tried updating that config in `/usr/local/etc/tigrc`, and while the error stopped, my untracked files still did not show under `tig status`.

**Comment by jonas** [comment]
@devshane Thanks for the hint.

I am wondering how that option is missing. A new tigrc is installed when installing Tig.

**Comment by diwo** [comment]
After upgrading to 2.2.2 with brew:
```
tig warning: /usr/local/etc/tigrc:90: status-untracked-dirs has been renamed to status-show-untracked-dirs
tig warning: Errors while loading /usr/local/etc/tigrc.
```
```
$ brew info tig
tig: stable 2.2.2 (bottled), HEAD
Text interface for Git repositories
http://jonas.nitro.dk/tig/
/usr/local/Cellar/tig/2.2.2 (12 files, 461.2KB) *
  Poured from bottle on 2017-07-02 at 20:43:21
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tig.rb
==> Dependencies
Recommended: readline ✔
==> Options
--with-docs
        Build man pages using asciidoc and xmlto
--without-readline
        Build without readline support
--HEAD
        Install HEAD version
==> Caveats
A sample of the default configuration has been installed to:
  /usr/local/opt/tig/share/tig/examples/tigrc
to override the system-wide default configuration, copy the sample to:
  /usr/local/etc/tigrc

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
```

**Comment by diwo** [comment]
After running `brew uninstall tig`, the system-wide tigrc file still exists
```
$ tig
tig warning: /usr/local/etc/tigrc:90: status-untracked-dirs has been renamed to status-show-untracked-dirs
tig warning: Errors while loading /usr/local/etc/tigrc.

$ brew uninstall tig
Uninstalling /usr/local/Cellar/tig/2.2.2... (12 files, 461.2KB)

$ ls -lt /usr/local/etc/tigrc
-rw-r--r-- 1 dickson admin 14986 Aug 28  2014 /usr/local/etc/tigrc
```
I suspect it has to do with this commit:
https://github.com/Homebrew/homebrew-core/commit/5600463d68620d68c9745acc490af7f8a16a75cb

**Comment by jonas** [comment]
Yes, there is nothing I can do about this other than maybe documenting it. It is an upstream distribution/packaging problem. The way to fix (assuming no local edits) is `rm -f /usr/local/etc/tigrc`.

**Comment by jonas** [comment]
Added notes on how to fix this issue to http://jonas.github.io/tig/INSTALL.html

**Comment by Asday** [comment]
Upgraded `git` and had this problem, due to the newest version of `tig` in the ubuntu repositories being real old.  Removing that and installing the latest version as per the installation instructions fixed it with no other changes.
