### ISSUE TITLE
Content not listed in a directory with a hyphenated name (tree view)

### ISSUE THREAD

**Issue by loonies** [jonas/tig#602]
If a directory name starts with the leading hyphen, the directory
content is not listed. Same directory renamed to a non-hyphen name works
fine. This affects the _tree_ view.

Example directory names:

 - `-- foo bar`
 - `-foo`

tig version 2.2.2

**Comment by jonas** [comment]
Thanks for the report. I've added a fix and will try to get a release out next week.
