### ISSUE TITLE
Segfaulting on master

### ISSUE THREAD

**Issue by edi9999** [jonas/tig#663]
Hello,

I was using tig-2.2.1 before, and it never segfaulted.

Now on almost master : a628e9d1680d8e9a1ffeba60bd07db24f993bbf0, I see segfaults sometimes when I start tig. It happens immediately on startup, I don't even have the time to see the main view.

I cannot reproduce the bug however, it seems to happen quite randomly.

Do you know how I could give more information ? I have tried with gdb, but it never segfaults then.

**Comment by jonas** [comment]
Thank you for the report.

If you have time and it "semi-reliably" segfaults it would be very helpful if you could do a `git bisect`. Else I can try to add in some code to generate a stack trace to the terminal.

**Comment by edi9999** [comment]
It doesn't segfault with 2.2.2 (I'm on it since these 3 days)

**Comment by edi9999** [comment]
I have switched to master again because of the new `+` feature which I really appreciate. However it is segfaulting quite often.

Can you add the code to generate a stack trace to the terminal please ?

**Comment by jonas** [comment]
@edi9999 I just pushed a commit 8c0a7c0acc13c019517dc1d9f3c9bcb0cd3a08e3 which allows you to have stacktraces. However, you need to compile Tig with `make all-debug`. Hope that will help us get the info required to fix this issue.

**Comment by edi9999** [comment]
There was a crash after I installed it, however it doesn't show any useful info I think : 

```
Tig crashed!

Please report this issue along with all info printed below to

  https://github.com/jonas/tig/issues/new

Tig version: 2.2.2-160-g8c0a7c0-dirty

Aborted (core dumped)
```

**Comment by jonas** [comment]
Ah, can you try to build using this command then: `make all-debug CPPFLAGS=-DHAVE_EXECINFO_H`

**Comment by jonas** [comment]
Else start Tig via the debugger:

    > gdb ./src/tig
    gdb> run

When it segfaults run `bt` in the gdb shell to get the backtrace.

**Comment by edi9999** [comment]
It seems to be some race condition of some sort, I was never able to reproduce it with gdb, also, it seems to happen 5% of the time, so not so easy to reproduce.

It just did it again, with a stacktrace

```
Tig crashed!

Please report this issue along with all info printed below to

  https://github.com/jonas/tig/issues/new

Tig version: 2.2.2-160-g8c0a7c0-dirty

tig[0x40452d]
/lib64/libc.so.6(+0x366f0)[0x7f9fc3b5e6f0]
tig[0x434993]
tig[0x431cc8]
tig[0x42e0e1]
tig[0x41c79c]
tig[0x419bd0]
tig[0x415cde]
tig[0x41619a]
tig[0x40471d]
tig[0x4049cc]
/lib64/libc.so.6(__libc_start_main+0xea)[0x7f9fc3b484da]
tig[0x402dca]
Aborted (core dumped)
```

**Comment by jonas** [comment]
Without the symbol info exposed with`make all-debug` this is not useful. If you can find the core file and email it to me I can take a look at it.

**Comment by edi9999** [comment]
I couldn't find your email.
Here is the coredump : 

[core.tig.1000.f5e8e956caa34fb58397103889b2c24e.22447.1501753363000000.lz4.txt](https://github.com/jonas/tig/files/1197162/core.tig.1000.f5e8e956caa34fb58397103889b2c24e.22447.1501753363000000.lz4.txt)

I have added the .txt extension to be able to upload it to github, but the extension is lz4

**Comment by edi9999** [comment]
Any update ? It still segfaults quite often (10 times a day approximately)

**Comment by jonas** [comment]
Sorry, I didn't have time to investigate this yet.

**Comment by edi9999** [comment]
It is possible that I found a patch : 

```
diff --git a/src/graph-v2.c b/src/graph-v2.c
index ced6838..9b3dfc9 100644
--- a/src/graph-v2.c
+++ b/src/graph-v2.c
@@ -258,7 +258,9 @@ done_graph(struct graph *graph_ref)
 	struct graph_v2 *graph = graph_ref->private;
 
 	free(graph);
-	htab_empty(intern_string_htab);
+
+	if (intern_string_htab)
+		htab_empty(intern_string_htab);
 }
 
 #define graph_column_has_commit(col) ((col)->id)
```

**Comment by jonas** [comment]
That's great news. Thanks a lot for looking into this.

The problematic change was introduced in https://github.com/jonas/tig/commit/2932c9b7aa151d19e7d0f50e0f68ef664017f776 back in July.

**Comment by jonas** [comment]
BTW, care to make a PR?

**Comment by edi9999** [comment]
Yes, I will do the PR, I just wanted to test it for a while to see if it still segfaults or not

**Comment by edi9999** [comment]
Done #745 :-)
