### ISSUE TITLE
Feature request: Key sequences as binds

### ISSUE THREAD

**Issue by evaryont** [jonas/tig#67]
It would be awesome if you could add key sequence support. I imagine that you would add a new key bind type, perhaps something like this:

   # (in ~/.tigrc)
   bind generic g wait
   bind generic gd view-diff
   bind generic gt view-tree

My reasoning is to make tig's keybinds closer to my vim configuration's.

**Comment by vivien** [comment]
> There are still some bike shedding and improvements left to do before this can be merged:
> 
> * What should be the timeout for triggering "shorter" key combos, e.g. o vs og? (not implemented yet)

No timeout. If `og` exists, `o` cannot be bound. This is how Vim actually behaves and it feels simple and natural: pressing `g` prints the key in the status line and waits indefinitely for a next key. Pressing `Esc` cancels the key sequence, but pressing for instance `j` executes the `gj` sequence (unless a sequence starting with `gj` exists, for sure, e.g. Vim's `gUiw` sequence).

> * Should the current combo keys be shown in the status view? (they currently are)

IMO, Yes.

> * How should escaping work? Currently, Esc cancels the key combo unless it is the first key in the combo. This means that you cannot have combos like o<Esc>.

The current behavior is fine.

**Comment by evaryont** [comment]
> If og exists, o cannot be bound.

Slight correction, you can actually bind shorter key sequences. Vim has a timeout (I think 2 seconds by default) that it waits. If you have `o` & `og` bound, pressing `o` and waiting 2 seconds will then execute the mapping for `o`. Annoying and not recommended, but it does exist.

The behavior described is fine with me. Thanks for all of the work!

**Comment by vivien** [comment]
Thanks for the clarification @evaryont, I didn't know that behavior in Vim!

Indeed, key timeout is hell, it reminds me of using this crappy remote, where you end up on channel "333" when you initially wanted to jump to channel 3...
