### ISSUE TITLE
Differentiate staged/unstaged changes in blame view

### ISSUE THREAD

**Issue by ael-code** [jonas/tig#676]
In the blame view at the moment an uncommitted line is shown as:
```
<date>   Not Committed Yet   0000000
```

It would be nice to differentiate between staged/unstaged changes like in the main view
```
<date>   Staged change     0000000
<date>   Unstaged change   0000000
```

As additional benefits we will reduce by two chars the minimum size of the author coloumn:

`Not Committed Yet` (17) --> `Unstaged change` (15)

**Comment by koutcher** [comment]
This request should be directed to Git rather than Tig as this comes from `git blame` output.
