### ISSUE TITLE
`git diff-files` does not use %(diffargs)

### ISSUE THREAD

**Issue by abliss** [jonas/tig#681]
E.g. when viewing unstaged changes. Tested in version 2.2.1.

The specific arg I'm interested in setting is "--submodule=diff".

**Comment by abliss** [comment]
I just saw that this was fixed in 2.2.2. I'll upgrade. Thanks!

**Comment by jonas** [comment]
👍

**Comment by abliss** [comment]
Hm I take it back, I upgraded to 2.2.2 and it does not seem fixed.

**Comment by abliss** [comment]
` TIG_TRACE=/tmp/tig.txt TIG_DIFF_OPTS="--submodule=diff" tig`
The trace shows, for example:
```
git show --encoding=UTF-8 --pretty=fuller --root --patch-with-stat --show-notes --submodule=diff --no-color 5bcc96a31cb6d6090f89b4d47f447f1bffbd1f66 -- 
```
viewing commit diffs works great! But viewing unstaged changes shows:

```
git diff-files --encoding=UTF-8 --root --patch-with-stat -C -M -- 
```
