### ISSUE TITLE
Feature Request: option to hide merge commits

### ISSUE THREAD

**Issue by cerisier** [jonas/tig#687]
`git` has this options as `git log --no-merges`
If you have any guidance re your preferred way to implement, I'd be happy to provide a PR.

**Comment by jonas** [comment]
Tig already understands `--no-merges` however, I will add an improvement to not show the graph when it is passed to the main view.

**Comment by cerisier** [comment]
noice ! 
[bitmoji](https://render.bitstrips.com/v2/cpanel/10216503-287335745_4-s1-v1.png?transparent=1&palette=1&width=246)
