### ISSUE TITLE
tig tag feature request

### ISSUE THREAD

**Issue by kimegede** [jonas/tig#694]
*Feature request:* `tig tag` to list tags and see commit message.
If possible to see the commits for the given tag.

If the idea, isn't shot down - and if no one else, got time - I can even look at it myself.

**Comment by kimegede** [comment]
Maybe it's related to #509 ?

**Comment by jonas** [comment]
Yes, it is related, but #509 doesn't filter the `tig refs` view to tags or branches. It's simply an alias.

**Comment by Ferada** [comment]
I'm working on this, by implementing something base off of `tig refs`, allowing `tig refs --tags`, `tig refs --branches` and `tig refs --remotes` for now - does that make sense? `git-log` also has these, but additionally allows some filtering on the names which I'd consider a stretch goal at the moment.
