### ISSUE TITLE
UTF-8 line-graphics misaligned / not connecting?

### ISSUE THREAD

**Issue by nemoDreamer** [jonas/tig#711]
I'm running `tig` from a Homebrew install (v2.2.2) on a Mac, inside Terminal and iTerm.

<img width="364" alt="tig_utf-8_graph_line_bends" src="https://user-images.githubusercontent.com/9303/28831217-ea547ffc-76d0-11e7-8a32-168529948947.png">

I've tried the various UTF-8 settings in iTerm, various monospaced fonts, as well as the most used like Deja Vu Sans, Source Code Pro, Ubuntu Mono, Roboto, etc..

It seems like the characters for the vertical/horizontal bars are ASCII, and don't match up to the UTF-8 corner characters?

**Comment by jonas** [comment]
Could be that the there are better [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character). They worked well on an Ubuntu system when I initially introduced them, but less so in for example iTerm. Maybe the square graphics are better.

**Comment by nemoDreamer** [comment]
Oh curves is where it's at! But seems like the curves and the straights don't belong to the same "set"?

I'd love to help out, since `tig` is my favorite git tool!
I see the "make" instructions etc and will try to get myself set up, but do you have any contribution guidelines?

**Comment by nemoDreamer** [comment]
Great news, @jonas : looks like this was fixed in the latest release of iTerm!

Looks like this is what did it (iTerm v3.2.1.beta.2 changelog):

> - Fix a bug where the "dark background" or "retina and dark background" thin strokes setting caused thin strokes to be rendered when the background was light.

<img width="170" alt="tig__utf8_lines" src="https://user-images.githubusercontent.com/9303/30811681-e830513e-a1d6-11e7-9f80-f7ab31953d11.png">

**Note:** still appears "off" in OS X's "Terminal" app, but at least we know it wasn't a `tig` issue!

**Comment by jonas** [comment]
Just updated, and indeed it looks very nice.

Can we close this issue now?
