### ISSUE TITLE
What about using libyui? It provides TUI+GUI support

### ISSUE THREAD

**Issue by timofonic** [jonas/tig#739]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by jonas** [comment]
Interesting question. At this point this would be a lot of work and most of Tig's internal is heavily line oriented so not sure it will work well in a GUI. Also libyui is C++ and this project is using C.

**Comment by jonas** [comment]
Closing as GUI is out of scope.
