### ISSUE TITLE
etc/tigrc missing after brew reinstall tig

### ISSUE THREAD

**Issue by timotheecour** [jonas/tig#740]
following https://github.com/jonas/tig/issues/598 i did:
```
brew uninstall tig
rm $path/etc/tigrc
brew install tig
```
now $path/etc/tigrc isnt' reinstalled, no file there

**Comment by jonas** [comment]
See https://github.com/Homebrew/legacy-homebrew/issues/43958

Homebrew didn't update the system tigrc which caused problems. When you instotig you should see a message suggesting to copy the sample tigrc if you want to override settings at that level.
