### ISSUE TITLE
How to Change Default Colors?

### ISSUE THREAD

**Issue by nobozo** [jonas/tig#741]
**Never mind** I did more research and I found the answer to this question. The answer is that colors can be specified in the .tigrc file.

I'd delete this question if I could. Moderator - feel free to do so.

On my monitor the leftmost column showing the commit date is almost unreadable, due to the color. Is there a way to specify an alternative color?

**Comment by jonas** [comment]
Yes, configuration of colors are documented here https://github.com/jonas/tig/blob/master/doc/tigrc.5.adoc#color-command.

Glad you figured it out.
