### ISSUE TITLE
incorrect rendering in certain repos with names of varying length

### ISSUE THREAD

**Issue by MichaelAquilina** [jonas/tig#742]
I'm not entirely sure what situation causes this to happen, but I have experienced it within multiple repos:

![screenshot from 2017-09-12 11-08-14](https://user-images.githubusercontent.com/2650040/30320495-b8558410-97aa-11e7-96ec-0fd0d3614cfe.png)

This is particularly bad for large repos with lengths of varying names. I cannot post a screenshot for these scenarios because they are private git repos.

In any case, pressing "h" (help) and then "q" after fixes the rendering.

```
$ tig --version
tig version 2.2.2
```

**Comment by jonas** [comment]
@MichaelAquilina I didn't manage to reproduce the bug with this main view configuration
```
set main-view   = line-number:no,interval=5 date:default author:full id:yes commit-title:yes,overflow=no
```
I a clone of https://github.com/remind101/empire

Can you share your `main-view` setting and ideally also what terminal you are using and whether this runs inside tmux or some other "screen manager".

**Comment by MichaelAquilina** [comment]
I am using no screen manager. I have managed to reproduce the issue in [Tilix](https://github.com/gnunn1/tilix) and Gnome Terminal.

My `main-view` setting:
```
set main-view = date author id:yes,width=6 commit-title:graph=false,refs=true
```

My entire `~/.tigrc` https://github.com/MichaelAquilina/tumbleweed-ansible/blob/master/roles/cli/files/tigrc

I had the same issue with your `main-view` configuration

**Comment by m8mble** [comment]
Interesting. I'm also having these problems on tumbleweed. Might this be caused by our `git` version or some other `tig` dependency?

**Comment by MichaelAquilina** [comment]
I'm also running tumbleweed, so there might be some pattern here

**Comment by MichaelAquilina** [comment]
Just checked another terminal emulator (terminator) and experienced the same issue.

**Comment by m8mble** [comment]
How can I help narrowing this down? What dependency / environment should I vary in order to find what actually caused this bug.

**Comment by MichaelAquilina** [comment]
I'm starting to suspect this is an issue with VTE. I noticed `htop` misrendering text last time. I'm pretty sure gnome terminal, tilix and terminator all use vte

**Comment by m8mble** [comment]
I don't know about VTE. But I can confirm, that I could avoid this bug in `xterm`. 
Furthermore, rendering in my xterm seems to be slower. This is why I could observe, `tig` drawing the "main view" in two steps: First possibly misaligned, and secondly aligned based on the (initially cached) commit details (eg. author widths). So this bug actually is about leaving artifacts from step one when step two has been done.
How can we narrow this down? How to dis-/prove the VTE suspicion?

**Comment by m8mble** [comment]
I think this bug can be closed. I just updated a bunch of packages (for the reference: updates also introducing kernel `4.13.3-1`) and I don't have this problem any more. It might still be interesting to find the root cause, but certainly it's no bug in `tig`.

**Comment by MichaelAquilina** [comment]
I'll perform an upgrade now and see if I get the issue anymore to confirm.

**Comment by MichaelAquilina** [comment]
Upgrade fixed this so I think its safe to say this is fixed 👍

**Comment by jonas** [comment]
Thanks for testing
