### ISSUE TITLE
How do I specify options in .git/config?

### ISSUE THREAD

**Issue by systemovich** [jonas/tig#743]
I have the following in my .git/config:

    [tig]
        date-display = relative-compact
        author-display = no

Tig outputs "Unknown option name" for each of those. How should the options be written?

**Comment by jonas** [comment]
Examples are provided in https://jonas.github.io/tig/doc/tigrc.5.html for each type of option:

```
[tig]
	line-graphics = no
[tig "bind"]
	generic = C !git cherry-pick %(commit)
[tig "color"]
	cursor		= red	default underline
```

For the two options in question, they are "view settings" and you need to specify what view they apply on, for example:

```
[tig]
        main-view-date-display = relative-compact
        main-view-author-display = no
```

**Comment by jonas** [comment]
Closing this for now.
