### ISSUE TITLE
Does not display some Unicode characters

### ISSUE THREAD

**Issue by kalkin** [jonas/tig#747]
If you have a commit subject like this: `Blabla 🐙/asd foo`,  tig won't show anything after 'Blabla '. Strangely some unicode characters seem not to be a problem like i.e. `♥` or `☺`.

**Comment by lolo101** [comment]
git log : `d11b566 Loïc Broquet ...`
tig : `d11b566 LoM-CM-/c Broquet ...`
However, searching 'Loïc' matches that line.

**Comment by jonas** [comment]
Fixed by #682 and released in Tig version 2.3.0. Please upgrade.

<img width="424" alt="screen shot 2017-12-11 at 15 08 06" src="https://user-images.githubusercontent.com/8417/33851481-229e5c90-de85-11e7-92fa-0c1391456dd6.png">

**Comment by kalkin** [comment]
Thank you @jonas & @rolandwalker
