### ISSUE TITLE
The vertical line is overridden by CJK characters after changing commits

### ISSUE THREAD

**Issue by yan12125** [jonas/tig#748]
Like the following screenshot:
![image](https://user-images.githubusercontent.com/1937689/30754126-18c73a36-9ff4-11e7-8e31-056697eb67da.png)

## Steps to reproduce
1. Resize the terminal so that it has width 140
2. git clone https://github.com/lantw44/ceiba-dl
3. tig
4. ```:set vertical-split = yes```
5. Hit Enter to show diff for the latest commit
6. Hit arrow down to jump to the next commit

The mis-layout can be observed on at least xterm, konsole and xfce4-terminal

## System information
OS: Arch Linux x86_64
Packages:

ncurses 6.0+20170902-1
xfce4-terminal 0.8.6-1
vte3 0.48.3-1
konsole 17.08.1-1
xterm 330
tig-git 2.2.2.r190.gbd42c8b-1, which is compiled from commit bd42c8b

Fonts:
Dejavu Sans Mono Book 16pt on Konsole and xfce4-terminal
I guess noto-fonts is used for CJK characters
xterm uses its default font (?)

**Comment by koutcher** [comment]
Fixed by 38c54de739c9752d5107288db0d5a6ca48efdd31.
