### ISSUE TITLE
set line-graphics utf-8 gives out weird commit markers like M-b~T~B M-b~W~O 

### ISSUE THREAD

**Issue by sprajagopal** [jonas/tig#749]
Tried with versions: 
2.3.0,
 2.1.1, 
2.1
and this is how it looks:
![screenshot_2017-10-03_22-14-50](https://user-images.githubusercontent.com/6297136/31137425-e1590014-a888-11e7-9210-ad5114ff72f6.png)

Works fine in:
2.0.3

**Comment by Dgc2002** [comment]
I just updated from 2.2 to 2.3.0 and am having the same issue.

**Comment by jonas** [comment]
What terms are you using? Also are you linking against libncursesw?

**Comment by Dgc2002** [comment]
I've just tested over PuTTY, Terminator, and GNOME terminal and got the same results.  
  
I built tig in a vanilla way. `make prefix=/usr`, `sudo make install prefix=/usr`

**Comment by wuyihao14** [comment]
Even 2.0.3 has the same issue for me

**Comment by cben** [comment]
I built from master using simple `make` and had same issue.
ncursesw was the key!  I was linked to non-unicode curses:
```
$ ldd src/tig
	linux-vdso.so.1 (0x00007fff994fe000)
	libncurses.so.6 => /lib64/libncurses.so.6 (0x00007fb558e70000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fb558c44000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb558873000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb55866f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb559098000)
```
After rebuilding with:
```
$ make configure
$ ./configure 
...
checking for ncursesw via pkg-config... yes
checking for working ncursesw/curses.h... yes
checking for working ncursesw.h... no
checking for working ncurses.h... yes
...

$ make
```
I got linked to ncursesw:
```
$ ldd src/tig
	linux-vdso.so.1 (0x00007fff68dd5000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f709c10a000)
	libncursesw.so.6 => /lib64/libncursesw.so.6 (0x00007f709bed2000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f709bca6000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f709b8d5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f709b6d1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f709c356000)
```
and it works :tada:  Love the v2 graph in unicode!

(I'm on Fedora 26, ncursesw is part of `ncurses-devel` package)

**Comment by sprajagopal** [comment]
It actually does [say](https://gist.githubusercontent.com/sprajagopal/b8d8fef449a4bb0971d79c06100d595b/raw/f72f6f94bbb2dc8b8c9ee1c7ddfe639cc3b62b0a/gistfile1.txt)

> 
> configure: WARNING: The found ncurses library does not support wide-char.
> configure: WARNING: This means that tig will not correctly render UTF-8.
> 
I'm on Ubuntu 16.04. 
I tried:
`sudo apt-get install libncursesw5-dev
`
Now, I'm linked with ncursesw.h (ldd src/tig)
Installing with this now works! 
Thanks, @cben!
