### ISSUE TITLE
Focus current commit when starting tig (`tig --all`)

### ISSUE THREAD

**Issue by unode** [jonas/tig#755]
When using `tig --all` all commits and branches are displayed.
The longest branch (more commits) is usually the one selected since the first commit on the commit history usually belongs to this branch.

`tig`'s default behavior is to focus on the first commit. This can be confusing if the checked out branch is not the longest.

With that I'd like to request a feature, the ability to focus on the current commit when tig is launched.
This way, even if the commit history includes longer branches, tig would "scroll" the history to focus on the checked out commit (and branch).

**Comment by vitalybe** [comment]
That would be very useful. In fact, once tig does it, I think `--all` should be on by default.

**Comment by zarac** [comment]
Thumbs up for this! It'd be so useful.
