### ISSUE TITLE
Feature request: add a 'custom bindings' section to the help screen

### ISSUE THREAD

**Issue by snoblenet** [jonas/tig#756]
Sorry, I'd write a PR for this myself if I had any experience with C.

I'm hoping that the Help screen, below all the default bindings, can also start listing my custom bindings.

Would that be possible? Thanks.

Great tool by the way. I use it all the time.

**Comment by jonas** [comment]
The help view already lists “internal commands” and “external commands” for each view. That sounds like what you are asking for.

**Comment by snoblenet** [comment]
My mistake. The bind section in my `.tigrc` was misconfigured. Thanks.
