### ISSUE TITLE
Build binaries?

### ISSUE THREAD

**Issue by Alok** [jonas/tig#757]
Would it be possible to add binaries to the releases? I recently started a job where the sysadmin isn't all that friendly and I'm reduced to either downloading binaries or building everything, including fundamental stuff like the ncurses library, which is a pain.

**Comment by jonas** [comment]
Which system do you need binaries for? I think this sort of effort is better served by the community.

**Comment by Alok** [comment]
ubuntu 16.04,  x86_64

**Comment by andreasstieger** [comment]
And you talk to upstream rather than resolving professional issues in your organization?

**Comment by chros73** [comment]
I'm working on a small but powerful build script, I'll let you know when it's finished. (Although you have to build it for yourself.)

**Comment by jonas** [comment]
I will close this as I don't have the time to build binaries. If someone wants to set up a PPA then I'd be happy to add a reference in the installation guide.

**Comment by chros73** [comment]
@devs: I "finished" my small but powerful [build script](https://github.com/chros73/build-tig) (along with `tmux` and `mc` build script), take a look, maybe you also like it. It can be used for development as well, just drop in patches and modify the version number.
Maybe I'll update the readme later with more info.

Thank You, guys, for this amazing project!
