### ISSUE TITLE
date format: use *m* for minute and *M* for month (ISO-8601)

### ISSUE THREAD

**Issue by plgruener** [jonas/tig#760]
Using tig, what always bugs me is it uses (in reldate format) the letter **m** for month and **M** for minute, but it should be the other way around (capital letters for year,month,day, lowercase for hour,minute,second).
#759 fixes this.
I know this is somewhat of a breaking change, since users would have to change their tigrcs and custom date formats. But this would not be the first time the config format changes.

edit: I know the PR breaks the tests. If you'd like I can adjust the tests and documentation as well. If not, feel free to close the issue and PR.

**Comment by jonas** [comment]
Fixed via #759
