### ISSUE TITLE
tig does not show files inside subdir of worktree when $GIT_DIR is set

### ISSUE THREAD

**Issue by g-raud** [jonas/tig#763]
Using tig 2.2 or 2.3.0 the CWD is ignored to qualify relative paths if GIT_DIR is set; all paths must be given relative to the GIT_WORK_TREE it seems.  This is annoying, particularly with vcsh (that sets a GIT_DIR inside ~/.config with a GIT_WORK_TREE of ~/), and is not what git-log does.  Example:

```sh
cd ~
vcsh init test
vcsh test add .config/tig/tigrc
vcsh test commit -m 'tigrc'
vcsh test tig -- .config/tig/tigrc # shows the commit
vcsh test log -- .config/tig/tigrc # does not show anything
cd .config/
vcsh test tig -- tig/tigrc # fails (No revisions match the given arguments.) 
vcsh test log -- tig/tigrc # shows the commit
vcsh test tig -- .config/tig/tigrc # shows the commit
vcsh test log -- .config/tig/tigrc # does not show anything
```

**Comment by jonas** [comment]
Worktree support is lacking to the extend of even being broken.

I do not personally use worktrees so any contributions in the area would be much appreciated.

**Comment by jonas** [comment]
When running `tig` as a `git` alias, `git` will `chdir(GIT_WORK_TREE)` and pass the subdirectory `tig` was invoked in as `GIT_PREFIX`. So the fix is to `chdir(GIT_PREFIX)`.
