### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by s-chizhik** [jonas/tig#764]
Hi all. I've faced #330 issue with Cyrillic letters. In my terminal Cyrillic letters are not showing properly :(

`git log` output
![image](https://user-images.githubusercontent.com/5587936/33436279-44ec6b02-d5ed-11e7-95c2-00412fa0e0b8.png)

`tig` output
![image](https://user-images.githubusercontent.com/5587936/33436257-393d6018-d5ed-11e7-9716-9eb8ffec53ec.png)

Also, I guess directional symbols are not showing properly too.
![image](https://user-images.githubusercontent.com/5587936/33437337-46445976-d5f0-11e7-9f01-a545baaac056.png)

Because on my other PC it works fine:
![image](https://user-images.githubusercontent.com/5587936/33437462-b1d12994-d5f0-11e7-9c83-7a198cec2e6d.png)

My configuration

    $ tig --version
    tig version 2.3.0
    $ ncurses5-config --version
    6.0.20160213
    $ ldd /tmp/tig/src/tig
        linux-vdso.so.1 =>  (0x00007ffe0a064000)
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f5704e37000)
        libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f5704c08000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f57049de000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5704614000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5704410000)
        /lib64/ld-linux-x86-64.so.2 (0x000055a86b9c5000)

OS: Linux Mint 18.2 Sonya

Can I provide you any other info? Thanks in advance.

**Comment by jonas** [comment]
Regarding the directional symbols in the commit graph, can you try to enable UTF-8 symbols by putting this inside your `~/.tigrc`?

    set line-graphics = utf-8

Regarding the other issue, I am not sure what could cause it. You link with ncursesw. What about `i18n.commitencoding` and `gui.encoding`? Are they set? Have you configured the `LANG` environment variable to something specific?

**Comment by s-chizhik** [comment]
Strange things... I've just recompiled tig and all works fine, both Cyrillic font and line graphics. Sorry for the disturbing. I suppose we can close this issue.

**Comment by jonas** [comment]
Great to hear this is solved.
