### ISSUE TITLE
[Help wanted] Cannot paste anything from clipboard

### ISSUE THREAD

**Issue by pomozoff** [jonas/tig#767]
Guys, it looks stupid but I can't paste anything from the clipboard in command mode, only the first char is pasted. Vim works fine in the same mode.
Could you explain to me what I'm doing wrong?

**Comment by weichuliu** [comment]
+1 for getting the same issue.
I'm using macOS 10.12 and both Terminal/iTerm are having the same issue.

**Comment by corbie** [comment]
+1 here too, macOS 10.12 and both Terminal/iTerm as above.

**Comment by jonas** [comment]
Yes, easily reproducible with 2.3.0. Fixed in current `master` by #725 it seems.
I'll release a new version tonight or tomorrow.

**Comment by jonas** [comment]
Correction, I can reproduce with the `tig` 2.3.0 version provided by brew.

**Comment by jonas** [comment]
This one does not work:
```
> otool -L /usr/local/bin/tig
/usr/local/bin/tig:
        /usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

This one works:

```
/opt/tig@(tig-2.3.0) > otool -L ./src/tig
./src/tig:
        /usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

The difference is the ncurses version, and notably the use of ncursesw.
