### ISSUE TITLE
Special characters shown incorrectly

### ISSUE THREAD

**Issue by piotrekfus91** [jonas/tig#786]
Special characters (polish in my case) are not presented in a correct way. For example, instead of "Michał Dąbrowski" I can see `MichaM-E~B DM-D~Ebrowski`. Same thing for all screens (log, main, etc).

Version: 2.3.3

**Comment by Drahoslav7** [comment]
Same problem here.
Version: 2.4.1

**Comment by MarcSchmitzer** [comment]
Ok, figured it out: The "special characters" only appear to work if libncursesw is used. My locally-built version used libncurses because I didn't have the development headers for libncursesw installed. So installing libncursesw5-dev and rebuilding was enough to make it work.

**Comment by piotrekfus91** [comment]
Does not work on my machine. I have libncursesw5-dev installed, but still no diacritis. I use official version.

**Comment by MarcSchmitzer** [comment]
What do you mean by "official version"? I cannot see any binary downloads on the tig homepage.
If you don't build it yourself, installing the dev headers won't help.

**Comment by piotrekfus91** [comment]
Yeah, you're right. I forgot that it is distributed like that. Rebuilding tig helped me, thanks.
