### ISSUE TITLE
Unicode arrow truncates rest of diff line

### ISSUE THREAD

**Issue by Janiczek** [jonas/tig#793]
```
tig version 2.0.2
git version 2.7.4
io.elementary.terminal version 0.4.3
```

The character is `🡺`.

This is what `git diff` shows (the correct output):
![diff-git](https://user-images.githubusercontent.com/149425/37332575-61083fae-26a7-11e8-8423-964c21e40fc5.png)

And this is what `tig` shows (dropping the rest of the line):
![diff-tig](https://user-images.githubusercontent.com/149425/37332577-612d12f2-26a7-11e8-8b52-6ff026c37092.png)

**Comment by jonas** [comment]
Thanks for the report. Is tight compiled with ncursesw (the wide char version)?
It would also be good if you can try a newer version of Tig to see if the issue has been fixed. The Unicode handling has seen several improvement in recent versions.

**Comment by Janiczek** [comment]
Oh, right, I'm so many versions behind. (Ubuntu `xenial` ¯\\\_(ツ)\_/¯ )
I've tried to compile `2.3.3` myself and it works there. **Thanks for nudging me in the right direction!**

**Comment by jonas** [comment]
Great, glad you got it working.
