### ISSUE TITLE
Refresh mode not working

### ISSUE THREAD

**Issue by timotheecour** [jonas/tig#794]
originally reported in https://github.com/jonas/tig/issues/430#issuecomment-371284051 and asked to reopen a new issue instead of reopening https://github.com/jonas/tig/issues/430

/cc @jonas @HageMaster3108

Refresh mode doesn't work reliably at all. It seems to work for the 1st 2 or so edits, then doesn't refresh when a file is updated again.

tig --version
tig version 2.3.3

Distro: OS X 10.13.3

I tried both:
set refresh-mode = auto
and
set refresh-mode = periodic
set refresh-interval = 5

maybe it's a dup of #389 ? in any case, seems broken

NOTE that F5 works

**Comment by jasontibbitts** [comment]
I am also experiencing the problem.  Sometimes refresh works, sometimes it doesn't.  'R'  or F5 always seems to work.

I'm also running 2.3.3, but on Fedora.  (I'm one of the maintainers of the tig package in Fedora; we do not apply any patches or use any interesting configure options.)

**Comment by FranciscoBorges** [comment]
@jonas See step-by-step means to reproduce bug with `refresh-mode`.

It seems this feature doesn't work very well when multiple views need to be updated.

Options normally work when making a commit inside `status` view and returning to status (after the command finishes). But if I return to `[main]` after that, `[main]` will not have been updated.

Curiously when I used `periodic` it worked. **Sometimes.**

All periodic tests using:
```
set refresh-mode = periodic
set refresh-interval = 5
```

## When did it work?

### `periodic` Returning to the `[main]` view after a commit:

1. start tig (default view here is `[main]`).
1. `status` is **not clean**:  `Unstaged changes` on top
2. go to `[status]` view;
3. stage some changed file.
4. commit by means of `bind generic c !git commit`
5. return to `[main]`

**It works!**

### `periodic`: clean to unclean

1. start tig (default view here is `[main]`). 
2. `status` is **clean**.
2. Edit a file outside of tig.
2. wait a few seconds... `[main]` view is updated!

**It works!**

## When does it NOT work?

### `periodic` fail: clean; unclean; clean; unclean.

1. start tig (default view here is `[main]`). 
2. `status` is **clean**.
2. Edit a file outside of tig.
2. wait a few seconds... `[main]` view is updated!
2. I stage and commit the file inside tig.
2. Go back to `[main]` view.
2. Edit a file outside of tig **AGAIN**.
2. `[main]` view is never updated. `#SadTrombone`
2. I hit `F5` which triggers a refresh... 
2. `[main]` view now shows `Unstaged changes` on top
2. I enter `[status]`: it tells me there are no changes `Changes not staged for commit: (no files)` `#SadTrombone`
2. To see any changes in status I apparently need to hit `F5` inside the `[status]` view.  

### `after-command`

1. start tig with a dirty status.
2. go to `status` view.
2. stage file and commit file (`bind generic c !git commit`)
2. return to `status`: view is updated. It appears clean!
2. return to `main`: view is not updated. Last commit does not appear! `#FAIL`

I am running tig 2.3.3 on OSX 10.13.6.

**Comment by nstgc** [comment]
I have not known this feature to work. I've tried both auto and periodic, but neither work.

I also tried watch --color -n 60 "tig" but that. . .ended poorly (gibberish on terminal).

**Comment by matthew-nm** [comment]
I could have sworn I saw it work at some point, but it now doesn't seem to be working at all, either in "auto" or "periodic".

I am using `source /path/to/Dropbox/tigrc` in my `~/.tigrc` file, and the color and mouse settings I add work, so I know that method is fine. Even when I enter them in `~/.tigrc` directly, the refresh doesn't appear to function.

I am using the latest as of today (a few commits past tag 'tig-2.4.1' at commit `93ea97...`) on an Ubuntu 18.04.1 LTS machine.
