### ISSUE TITLE
tab completion is really slow

### ISSUE THREAD

**Issue by dwijnand** [jonas/tig#795]
in a clone of https://github.com/scala/scala run `tig blame src/library/scala/math/Order<TAB>` and (on my machine) it'll take 14 seconds to give you:

```
$ tig blame src/library/scala/math/Order
src/library/scala/math/Ordered.scala    src/library/scala/math/Ordering.scala
```

tig version 2.3.3
git version 2.15.1

**Comment by pzrq** [comment]
@dwijnand Great question. Could you run `$ time tig blame src/library/scala/math/Order` and copy/paste the output here? 

If you can think of any other way to debug, profile or otherwise get visibility into what is causing the slowness that would be great too.

**Comment by jonas** [comment]
The bash tab completion is still based on a very old copy of the git
completion. Could be part of the problem.

>

**Comment by dwijnand** [comment]
> Could you run `$ time tig blame src/library/scala/math/Order<TAB>` and copy/paste the output here?

you can't time the bash completion - it just outputs the same thing:

```bash
$ time tig blame src/library/scala/math/Order
src/library/scala/math/Ordered.scala    src/library/scala/math/Ordering.scala
```

**Comment by pzrq** [comment]
Then is this a tig issue or a bash issue or some interaction of the two?

**Comment by dwijnand** [comment]
it's an issue with tig's bash completion.

for comparison completing `blame src/library/scala/math/Order<TAB>` is less than a second for me.

**Comment by askedrelic** [comment]
I've noticed this as well on a git repo with 14K tags. I'm assuming tags are part of the autocomplete algorithm and that is what I assume really slows it down. I think it's more due to bash being slow at large amounts of data.

tig version 2.3.3
git version 2.16.3

**Comment by ingydotnet** [comment]
On a huge repo I use daily, `tig` Bash completion hangs for 2 minutes. If I type `tig ` and press tab, I'm screwed. Git completions on same repo are fast.

Here's a fun trick:
```
set -x; tig <tab><tab>
```
Try that on a big repo and sit back with some coffee and watch the show.

**Comment by rohieb** [comment]
The culprit is probably __tig_complete_file:

```
linux.git $ time __tig_complete_file 

real    0m29.363s
user    0m27.805s
sys     0m1.600s

linux.git $ time __git_complete_file

real    0m0.014s
user    0m0.003s
sys     0m0.008s
```

In the long run I would probably rewrite the tig completion so it uses the git completion for all git-related options. Most users should already have this installed, and it is faster in most cases, as well as better maintained :)

**Comment by rohieb** [comment]
> ```
> linux.git $ time __tig_complete_file 
> 
> real    0m29.363s
> user    0m27.805s
> sys     0m1.600s
> 
> linux.git $ time __git_complete_file
> 
> real    0m0.014s
> user    0m0.003s
> sys     0m0.008s
> ```

These times are reproducible btw, so no caching issues.

**Comment by benpaxton-hf** [comment]
the [loop in _tigcomp](https://github.com/jonas/tig/blob/ca205d32bc0c7677fbadfb0db943c2daa123908b/contrib/tig-completion.bash#L53-L59) is the problem; I replaced it locally with an equivalent but significantly faster `awk` script before finding this issue and the PR - my tests showed that for the specific repo I was having issues with, it was taking 15+ seconds, iterating approximately 9000 times and building a 327kB string; the `awk` script took ~0.01s and built an identical string.

#960 is probably the "right" solution here, though.

**Comment by dwijnand** [comment]
Wonderful to have this fixed!  Thank you, everyone involved.
