### ISSUE TITLE
tig on solaris 10

### ISSUE THREAD

**Issue by navidof** [jonas/tig#805]
I'm facing the following when trying to compile on solaris with gcc49:

src/io.c: In function 'open_trace':
src/io.c:252:13: error: 'LOCK_EX' undeclared (first use in this function)
   flock(fd, LOCK_EX);
             ^
src/io.c:252:13: note: each undeclared identifier is reported only once for each function it appears in
src/io.c:259:14: error: 'LOCK_UN' undeclared (first use in this function)
    flock(fd, LOCK_UN);
              ^
src/io.c: In function 'io_get_line':
src/io.c:527:4: warning: return makes integer from pointer without a cast
    return NULL;

My platform is the following:
bash$ cat /etc/release
                    Oracle Solaris 10 1/13 s10x_u11wos_24a X86
  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.
                            Assembled 17 January 2013

Is tig supported for this platform ?

**Comment by ThomasAdam** [comment]
Hi,

So this is a classic portability issue between `flock()` on Solaris and elsewhere.  Yep, you guessed it, Solaris is the odd one out here.  Good, eh?

We could use `fcntl()` here instead, but I'm unsure how useful that is. Maybe the right solution here is just to make `flock()` a no-op where it isn't detected.

**Comment by navidof** [comment]
I patched the code using the wrapper given here:
https://www.perkin.org.uk/posts/solaris-portability-flock.html

Seems to work so far, good enough for my needs I would say. Don't really mind to invest on a platform in the process of being deprecated anyway.

Thanks
