### ISSUE TITLE
Cant install tig on Windows 10 in Cygwin

### ISSUE THREAD

**Issue by lufthansa747** [jonas/tig#817]
I'm trying to install tig from source to cygwin. I have installed all the packages mentioned in the installation instructions. When I run `./configure` it finishes with the following error

```
configure: creating ./config.status

config.status: creating config.make

config.status: error: cannot find input file: `config.h.in'
```
This stops `make` and `make install` from working.

I'm not sure what the problem is, I cant find anyone else with the same issue and I've installed every package I can think of. 

Following installation instructions from tar ball works.

**Comment by jonas** [comment]
How did you generate `./configure`?
