### ISSUE TITLE
Perform scrolling in the active tab

### ISSUE THREAD

**Issue by novellizator** [jonas/tig#818]
So when I have my tig open with the main window on the left and the diff on the right and I use the laptop's touchbar to scroll, it always only scrolls the main panel no matter which panel is active - and that's quite annoying, when I want to scroll up and down within the diff and it changes the whole commit.

Same applies for arrows.

Could you please, _please_ fix that?

**Comment by novellizator** [comment]
So this fixed the issue in the .tigrc
```
bind generic <Up> move-up
bind generic <Down> move-down
```

**Comment by anbjork** [comment]
For anyone else stumbling over this, navigating with j and k rather than up and down has the behavior OP expects by default, if one prefers to not reconfigure. It's documented in the manual too
