### ISSUE TITLE
Feature request: see blame before this change

### ISSUE THREAD

**Issue by viraptor** [jonas/tig#820]
Maybe this is already possible and I'm missing it, but I often try to see the history of a specific line in a file. This means a loop of:

- git blame some_file
- find the line
- git blame some_file (ref_from_git_blame)^
- ... repeat

It would be great if I could go from the `tig blame some_file` view to the `{ref}^` blame view with a single key press. (where `{ref}` comes from the currently selected line)

**Comment by jonas** [comment]
This can be done with the `parent` action, which by default is bound to `,`.
