### ISSUE TITLE
Bind single quote to mapping

### ISSUE THREAD

**Issue by alok** [jonas/tig#821]
This doesn't seem possible.

I'm trying to do:
```
bind generic ' find-next
bind generic " find-prev
```

but get an error. Oddly, if I wrap those quotes in other quotes, like 

```
# spaces between quotes added for clarity
bind generic ' ' ' find-next
bind generic ' " ' find-prev
```

then it will work if I press the whole 3 key sequence. Maybe the parsing is wonky?

**Comment by jonas** [comment]
It's true that since keys can be quoted it is no longer possible to bind to quote characters. I've introduced two key mappings which can be used like this:

```
bind main <SingleQuote> !echo single
bind main <DoubleQuote> !echo double
```
