### ISSUE TITLE
bind <Ctrl-H> [1~ [4~can not work

### ISSUE THREAD

**Issue by fcying** [jonas/tig#822]
tig version: 2.3.3

I use xshell(xterm), press `<home> <end>` will send  `[1~` and `[4~`.

use this config,  `<home> <end>` can work in main view, but can not work in stage and diff view
`<ctrl-e>` can work in all view, but `<ctrl-h>` tips `Unknown key, press h for help`
```
bind generic [1~ move-first-line
bind generic [4~ move-last-line
bind generic <Ctrl-H> move-first-line
bind generic <Ctrl-E> move-last-line
```

type `h` I can see the bind is effect
![image](https://user-images.githubusercontent.com/106934/39737657-0b339f54-52b9-11e8-98aa-c27d6a73a216.png)

I try add stage and diff config, but not work also.
```
bind stage [1~ move-first-line
bind stage [4~ move-last-line
bind diff [1~ move-first-line
bind diff [4~ move-last-line
```

**Comment by ideal** [comment]
Could you try this?
```
bind generic <Esc>[1~ move-first-line
bind generic <Esc>[4~ move-last-line
```

**Comment by fcying** [comment]
@ideal  It can work, thanks very much ~
