### ISSUE TITLE
Possible null pointer dereference?

### ISSUE THREAD

**Issue by movie-travel-code** [jonas/tig#824]
Hi all,
I'm henry wong, from Qihoo 360 Codesafe Team. We found a **suspicious  null pointer dereference** at https://github.com/jonas/tig/blob/master/compat/hashtab.c#L732 and https://github.com/jonas/tig/blob/master/src/line.c#L209. 

1. `htab_find_slot_with_hash()` may return `NULL`, maybe `if (!slot || *slot == HTAB_EMPTY_ENTRY)` is more appropriate here.
```
slot = htab_find_slot_with_hash (htab, element, hash, NO_INSERT);
if (*slot == HTAB_EMPTY_ENTRY)
  return;
```

2. `find_line_rule()` may also return `NULL`, maybe should add a check before accessing the return value of `find_line_rule()`
```
struct line_rule *rule = find_line_rule(&query);
int default_bg = rule->info.bg;
```
Since I'm not familiar with `tig`, I think I should report this issue here to ask for your advice so as to improve `tig`.

Thanks in advance!

Cheers!
Henry Wong
Qihoo 360 Codesafe Team

**Comment by jonas** [comment]
Thanks, I've made a patch based on your analysis.
