### ISSUE TITLE
[enhancement req] Intuitively expecting up-down arrows to affect the focused view

### ISSUE THREAD

**Issue by asaf** [jonas/tig#833]
Hey,

In two views mode [staging | diff]

Focusing on right window by tab, then using up/down arrows (IMO) should affect the focused window and not the passive one.

Thanks for this awesome, bleeding fast tool!

**Comment by jonas** [comment]
This mappings is there to easy review: up/down will change commit, enter will open child view and subsequently scroll down in the focused view.

You can change the behavior by remapping the keys:

```
bind generic <Up> move-up
bind generic <Down> move-down
```

**Comment by asaf** [comment]
fair enough, closing!

**Comment by anbjork** [comment]
For anyone else stumbling over this, navigating with j and k rather than up and down has the behavior OP expects by default, if one prefers to not reconfigure. It's documented in the manual too
