### ISSUE TITLE
Should default to "line_graphics = utf-8" if supported

### ISSUE THREAD

**Issue by proski** [jonas/tig#834]
I've been using tig for years, yet I only discovered "line_graphics = utf-8" recently by finding references to it accidentally in the tig's own commit history. It's a beautiful feature, I wish I new of it earlier.

I believe "line_graphics = utf-8" should be default. If UTF-8 is unsupported, an ASCII approximation should be used. I see that tig uses `?` for graphics in the C locale - that's not a good approximation (I'm not sure if tig or ncurses does it).

Another approach would be to have a new option "line_graphics = auto" as the default. It would select the graphics based on the terminal and locale. "line_graphics = utf-8" would force the UTF-8 graphics.

**Comment by jonas** [comment]
I prefer to introduce an auto value.
