### ISSUE TITLE
A suspicious memory leak error occured in `tig/src/argv.c`.

### ISSUE THREAD

**Issue by 360CodeSafe** [jonas/tig#839]
This is 360 CodeSafe Team, we found a suspicious memory leak occured in `tig/src/argv.c`. See https://github.com/jonas/tig/blob/f49fc7c7fd05bc402a34def6fdb94c0f062f7df5/src/argv.c#L182, `strdup(env)` will allocate memory and assign the memory adderss to `env`, however there is no `free()` action on `env`. So memory leak will occur at the end of function `argv_from_env()`.

```
	if (env && *env)
		env = strdup(env);
	return !env || argv_from_string(argv, &argc, env);

```

Since I'm unfamiliar with `tig`, please forgive me if there is anything
wrong with my description.

Qihoo360 CodeSafe Team

**Comment by ideal** [comment]
Seems that need to be freed after call of `argv_from_string()`.

**Comment by jonas** [comment]
The method is used in one place and should not be freed. It would probably be better to just inline the code.

**Comment by 360CodeSafe** [comment]
Hmm, I see. Thanks you for your explanation, jonas, it seems that there will be no practical impact.
