### ISSUE TITLE
Edit/View notes

### ISSUE THREAD

**Issue by albasili** [jonas/tig#844]
I haven't found anything related to notes in the documentation, would it be possible to view and edit notes?

**Comment by jonas** [comment]
There's a show-notes setting for displaying notes associated with commits.
For editing notes you can create a keybinding which uses %(commit) to
reference the selected commit.

I hope that helps.

-- 
Jonas Fonseca

**Comment by albasili** [comment]
Thanks for the reply, is there a mark of some sort when there's a note associated to a commit?

**Comment by sprajagopal** [comment]
related: how to hide the refs/notes/commits from showing up when doing a `tig all`?

**Comment by koutcher** [comment]
Commit with notes are now highlighted in 2.5.0.
