### ISSUE TITLE
Will pay $500 USD for more practical documentation. 

### ISSUE THREAD

**Issue by cjhanks** [jonas/tig#852]
I love `tig`, it is the way I... review my commits, read code reviews, and understand my own convoluted history.

I have been programming Linux environment since at-least the last free RHEL distro.  Me, I understand SH/BASH/Vi/Emacs conventions... the kids with - power-shell, Python IDE, Visual Studios, Xcode, and many other Windows/MacOSX based environments do not know these.

These people are intelligent and valuable.

But all of the defaults tools to help them analyze the history of their repository are inferior, in both; distracting ill-conceived interfaces born of necessity, or un-helpful linear logic.  

So many of them are unaware how to read the history of code to extract meaning.  `tig`, in this respect is great.  And my interest was only reknewed when Greg Kroah-Hartman (@gregkh) explicitly stated so [1].

My progress, and the progress of my team would benefit from documentation catered to non-dinosaurs (absolutely all respect intended).  And for that, I will give you $500 dollars.

```
$> echo "You can contact me at; ..." | base64
WW91IGNhbiBjb250YWN0IG1lIGF0OyBpYW1AY2poYW5rcy5uYW1lCg==
```

[1] https://plus.google.com/+gregkroahhartman/posts/KXKWYN1HSGf

**Comment by cjhanks** [comment]
I am trying to donate money to an open source project, that's it.

**Comment by jonas** [comment]
Hi, great to hear that you are willing to donate money to the project. I'd like to know what your expectations are.

By "more practical documentation", do you mean tutorials on specific topics, cheat sheets or something else?

What specific topics are you interested in covering? 

How should the documentation be presented? Text? YouTube videos?

**Comment by cjhanks** [comment]
The donation is not contingent on any specific thing, you just need to tell me where to send it.  I have already received that amount of value from the tool.

The manual here: http://jonas.nitro.dk/tig/manual.html is very good for understanding the commands explicitly, but it presumes you understand Git.  

In my experience - most new developers are actually using the Git visualizer as a learning aid.  So, a couple tutorials which start from a lower presumed level of understanding would help.  

Some examples:
- Using the tool to interpret the history of a single file.
- Using the tool to understand rebase/merge conflicts.

That said, if you have hosting costs - you could also just spend it on that.  Thanks!

**Comment by jonas** [comment]
Closing as the conversation went cold.
