### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dscho** [jonas/tig#858]
New in v2.4.1 (was not there in v2.4.0):

```
2018-07-27T10:36:13.4602087Z src/graph-v2.c: In function 'colors_init':
2018-07-27T10:36:13.4604561Z src/graph-v2.c:217:3: error: unknown type name 'uint'; did you mean 'int'?
2018-07-27T10:36:13.4606435Z    uint size = 500;
2018-07-27T10:36:13.4607091Z    ^~~~
2018-07-27T10:36:13.4608026Z    int
```

Let me know if you need me to open a PR, or whether it is quicker for you to just fix it.

**Comment by chros73** [comment]
Hm, I just compiled v2.4.1 on CentOS 6.10 (gcc 4.4.7) and on Ubuntu 14.04 (gcc 4.8.4) without any issue (using this [build script](https://github.com/chros73/build-tig)).
What OS, distrib do you use?

**Comment by jonas** [comment]
The only change between the two versions is https://github.com/jonas/tig/commit/62d559a382af15bec3fe6fa5d02cbdb1999a5b6d
Strange

**Comment by dscho** [comment]
Hmpf.

@chros73 I am using the Git for Windows distribution 😛 

I don't have time right now, especially not to hunt down a bug that I only encountered today when I tried to upgrade the `tig` included in Git for Windows, but I will try to find some time (and not to forget about it).

**Comment by koutcher** [comment]
The uint should be replaced with size_t anyway...
