### ISSUE TITLE
Hide commits by regex in main view

### ISSUE THREAD

**Issue by dufferzafar** [jonas/tig#860]
In the main/default view of tig. I don't want some commits to ever show up (since they're mostly noise generated by automatic tools.)

Currently I'm using something like:

To hide messages containing terms:

`git log --oneline --grep=SVN_ --grep=GIT_ --grep=Merge --invert-grep | tig`

To hide by author name regex:

`git log --oneline --perl-regexp --author='^((?!l10n daemon script).*)$' | tig`

But this gives a view different than tig's default one.

It is essentially a pager.

**Comment by odnoletkov** [comment]
Just replace `git log` with `tig`

    tig --oneline --grep=SVN_ --grep=GIT_ --grep=Merge --invert-grep

This type of `tig` invocation shows the main view and passes all the options to the underlying `git log`

**Comment by dufferzafar** [comment]
Wow. That worked amazingly well.

Thanks a lot!

**Comment by jonas** [comment]
Great suggestion @odnoletkov

Closing as this seems to have been resolved.
