### ISSUE TITLE
`tig --first-parent -m` does not show diffs like `git log -p --first-parent -m`

### ISSUE THREAD

**Issue by ivan** [jonas/tig#861]
I use `git log -p --first-parent -m` to look at a repository that makes heavy use of merges, but of course, I'd much rather be using tig.  Unfortunately, tig doesn't show the diffs I expect, and I don't know if this is a bug or some unfortunate defaults that I have to work around.

For background, `git log`'s `-m` is:

```
-m
  This flag makes the merge commits show the full diff like regular commits;
  for each merge parent, a separate log entry and diff is generated. An exception
  is that only diff against the first parent is shown when --first-parent option
  is given; in that case, the output represents the changes the merge brought
  into the then-current branch.
```

Here's a repro case:

```
git clone https://github.com/NixOS/nixpkgs
cd nixpkgs
git checkout 117680b0e9f4472e6161427ac0814fc2c6f998ba
tig --first-parent -m
```
and press Enter on the commit.

For https://github.com/NixOS/nixpkgs/commit/117680b0e9f4472e6161427ac0814fc2c6f998ba, `tig --first-parent -m` shows a ~27662 line diff, while `git log -p --first-parent -m` shows the ~45 line diff I expect.

```
# tig --version
tig version 2.4.0
ncursesw version 6.1.20180127
readline version 6.3

# git --version
git version 2.18.0
```

**Comment by ivan** [comment]
I figured out that `git show` shows the longer diffs when using `git show -m` instead of `git show --first-parent -m`, and that tig is indeed executing `git show` without `--first-parent` when showing the commit:

```
git show --encoding=UTF-8 --pretty=fuller --root --patch-with-stat --show-notes -m --no-color 117680b0e9f4472e6161427ac0814fc2c6f998ba --
```

I don't know why `-m` makes it into the arguments but `--first-parent` doesn't, but as a workaround, I found:

```
TIG_DIFF_OPTS=--first-parent tig --first-parent -m
```

**Comment by jamescassell** [comment]
Would it be possible to add a keyboard shortcut to enable this mode from within tig?
