### ISSUE TITLE
HEAD is missing though commit-title-refs already turned on

### ISSUE THREAD

**Issue by ryenus** [jonas/tig#863]
I've turned on `commit-title-refs` in the main view, but still couldn't see `HEAD` being shown.

When using `tig --all`, it would be nice to be able to locate `HEAD`, well, by searching for `HEAD`, otherwise, one has to search for current branch or tag to find it, not so convenient. 

Thanks

**Comment by koutcher** [comment]
Even though `HEAD` is not shown, you can still use `:goto HEAD` to speed up the search.

**Comment by koutcher** [comment]
This is actually a feature and not a bug, HEAD is shown only in detached HEAD. Closing.
