### ISSUE TITLE
Bash completion doesn't switch to completing just files

### ISSUE THREAD

**Issue by jasonkarns** [jonas/tig#865]
When adding `--` and attempting to tab complete filenames, tab completion is still slow and/or fails.

This indicates that the completion script is not short circuiting once it recognizes the `--` option. If it were to short circuit and exit, then tab completion for anything after the `--` option should be just regular old path completion, which should be super fast.

Related to #540

**Comment by heller** [comment]
Typing `tig -- ` and pressing tab results in the expected quick file completion in my test just now.
macOS 10.14.3
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
tig version 2.4.1
ncurses version 5.7.20081102
readline version 8.0
