### ISSUE TITLE
Change foreground color for current line

### ISSUE THREAD

**Issue by huyvohcmc** [jonas/tig#878]
Somehow the text in the picture below is white, which is really hard to see. What are the options to turn them black?
![screen shot 2018-12-08 at 10 14 41 pm](https://user-images.githubusercontent.com/17645203/49687533-d7ac5000-fb36-11e8-9ed6-0f5a7c563f89.png)
My `ticrc` is clean and only contains binding settings. The picture is taken in iTerm2 with tender color scheme.

**Comment by meydjer** [comment]
Add the following to your `~/.tigrc`

```
color cursor      black green
color title-focus black blue
```
