### ISSUE TITLE
Add a command line parameter to launch tig in stage view

### ISSUE THREAD

**Issue by idvorkin** [jonas/tig#880]
Tig can be started in several views (stash, log, etc). However it can not launch directly into stage view. 

I currently work around by pressing s, but it would be great to add a ```tig stage``` command line parameter

**Comment by koutcher** [comment]
Have you tried `tig status` ?

**Comment by idvorkin** [comment]
Oops.  Perfect thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
