### ISSUE TITLE
Fails when branch has `=` character

### ISSUE THREAD

**Issue by ixti** [jonas/tig#884]
Steps to reproduce:

```
git checkout -b some@weird=branch-name
tig
```

**Comment by UJtriumphs** [comment]
it happens for me

**Comment by ixti** [comment]
In fact it still fails. I just forgot to properly describe failure :D

**Comment by ixti** [comment]
Here's how it looks:

https://asciinema.org/a/7IM4o1TTTLK2sU99crB3u3RkD
