### ISSUE TITLE
segmentation fault when trying to set an option in git config file

### ISSUE THREAD

**Issue by stevenyvr987** [jonas/tig#897]
In my git config file, if I set the date column of the refs view using the syntax
`refs-view-date = relative-compact`
and then execute `tig refs`, things work.

But when using the syntax
`refs-view = date:relative-compact`
I get a seg fault
`“tig refs” terminated by signal SIGSEGV (Address boundary error)`

**Comment by stevenyvr987** [comment]
```
$ tig --version 
tig version 2.4.1-7-g93ea970
ncursesw version 6.0.20160213
readline version 6.3
```

**Comment by koutcher** [comment]
The refs view is expecting the ref field. Try with `refs-view = date:relative-compact ref`

**Comment by stevenyvr987** [comment]
Thanks, it works. I wasn't fully understanding the `tigrc` man page for the set command.
I think `tig` shouldn't segfault the way it does; it should quit with an error message, 'invalid set command' or something similar.
