### ISSUE TITLE
If a column, like author, has very long width, graph and other columns can't be displayed in main view.

### ISSUE THREAD

**Issue by pponaldo** [jonas/tig#898]
In one of my repository, I got an issue that main view graph and other columns are not displayed. And I got the reason by checking old commits history. 

One author name was so long, so since next column of author column can't be displayed. This issue can be solved by setting maxwidth of main view as proper value like 20. 

But I think this one should be solved by providing default limitation of width or other ways for proper displaying.

**Comment by gerrywastaken** [comment]
You want the toggle display keys:

https://github.com/PaulChanHK/tig/blob/master/doc/manual.adoc#misc

> D | Toggle date display on/off/relative/relative-compact/custom
> A | Toggle author display on/off/abbreviated/email/email user name.
> G | Toggle revision graph visualization on/off.
> ~ | Toggle (line) graphics mode
> F | Toggle reference display on/off (tag and branch names).
> W | Toggle ignoring whitespace on/off for diffs
> X | Toggle commit ID display on/off

**Comment by lnksz** [comment]
@pponaldo didn't `A` resolve your issue? For me it definitely did the trick! If for you too, you could close this!

**Comment by MggMuggins** [comment]
The workaround works great! Wonder about setting `A` to abbreviated by default.
