### ISSUE TITLE
Variable to expand to branch name - local or remote

### ISSUE THREAD

**Issue by jpschewe** [jonas/tig#900]
I have this binding to fast forward branches
```
bind refs > !git merge --ff-only %(branch)
```

When I have a local branch selected this works just fine. However when I have a remote branch selected, it appears to drop the remote name from the "%(branch)". Reading the documentation it seems that "%(repo:remote)" will work sometimes, but not when I want to fast forward to a remote branch that isn't associated with the checked out branch.

Ideally I'd like to bind a key to fast forward the current branch to whatever branch name is currently selected, whether that is a local branch or a remote branch. Is this possible?

**Comment by koutcher** [comment]
Wouldn't `bind refs > !git merge --ff-only %(commit)` do the job ?

**Comment by jpschewe** [comment]
Thanks, I hadn't thought of that. The other binding that I'd like to use this with is a no-ff command. Using the commit id in the merge will populate the commit message with the commit id rather than the branch name though. Do you have a solution for that?

**Comment by koutcher** [comment]
You can use `%(remote)/%(branch)` for remote branches but, in the current state of Tig, I don't think you can handle both local and remote branches with the same binding.

**Comment by jpschewe** [comment]
Thus the feature request.
