### ISSUE TITLE
LFS support

### ISSUE THREAD

**Issue by Asday** [jonas/tig#913]
I'm looking into using git LFS for something I'm doing at the moment, (so I'm quite new to the concept), and I use `tig` constantly as my daily driver.  It handles everything except a couple things I find faster to type as `git <...>`.

By the looks of things, `tig` doesn't support LFS, or at least, I can't find any documentation regarding the use of the two together.  Does `tig` handle it all without me having to think?  Or does it not deal with it at all?

If there is integration, please document it.  (It would help out noobs like me).  If there is not integration, please consider adding it.

**Comment by kdbertel** [comment]
`tig` works fine with LFS. It does, however, look at the underlying reference files rather than the referenced files, but this shouldn't be much of an issue.

**Comment by orzechow** [comment]
With default Git settings LFS works well with tig :ok_hand:
I'd love to have a diff for locally cached LFS files though. (We work with large osm maps, which are basically XML files, so these are nicely diffable).
So, I tried setting `git config --global diff.lfs.textconv cat`.

This works fine on command line as well as in tig as long as the respective files are in the local LFS cache. If not though, git tries to download the LFS file first. In my case this leads to an authentication dialog, which works well on command line:
![Selection_003](https://user-images.githubusercontent.com/5220714/142451689-5920d9d5-66e3-4aa0-b87c-1546dea493c6.png)
but not in tig
![Selection_005](https://user-images.githubusercontent.com/5220714/142452331-e3627a70-4481-408b-8574-45d2c73a8e13.png)

 Tig shows part of the dialog, but is unresponsive. Any way to make this work?
 It would be great to either fully interact with this dialog or abort it (and show the default pointer based LFS diff).

I also tried writing a custom textconv script, but the download is triggered before the diff script is called (which makes sense). Same for the `diff.lfs.command` setting :thinking:

**Comment by koutcher** [comment]
Unfortunately there is no way you can enter credentials from Tig, `git` is not running in a pty, its output is just piped into the built-in pager. You can either use GIT_ASKPASS / core.askPass to configure  an external application for this or use cache helper and preload your credentials.

**Comment by orzechow** [comment]
Thanks for the hint. I'm uising using a cached credential helper, but get this dialog anyways (at least for the first call?). 
So, askPass might be a good option.
