### ISSUE TITLE
Feature request: Status view on a target sub-directory

### ISSUE THREAD

**Issue by JeffCarpenter** [jonas/tig#916]
I'd like to be able to run `tig status $SOMEDIR` and/or `tig $SOMEDIR` -> status view and see only the changes in that sub-directory (recursively, like `git status`).

My use case is I keep all of my own code in one repo for lower administrative burden and easier code sharing between projects.

**Comment by typebrook** [comment]
>easier code sharing between projects

Sounds like the use case of `git submodule`

**Comment by JeffCarpenter** [comment]
Doh.. this seems obvious in hindsight.
