### ISSUE TITLE
Christmas tree with libncurses6.1

### ISSUE THREAD

**Issue by hbrunie** [jonas/tig#921]
Hello,

I have download source code to install it on machine where libcurses is not available, I am no root, and admins won't install it. So I have downloaded libncurses6.1 and change the TIG Makefile to link with libncurses instead of libcurses.

Also I'm on Mac but ssh on distant linux machine.
The result is quite weird, I have dropped here a screen shot.
There are two images because it is .... blinking.

<img width="1733" alt="image" src="https://user-images.githubusercontent.com/5767146/56755797-2dc80b80-6745-11e9-8b86-aceadc8088c4.png">
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/5767146/56755826-3b7d9100-6745-11e9-8118-43eeadc804d3.png">

**Comment by koutcher** [comment]
There is no reason for Tig not to work properly in this configuration, provided that the TERM variable exported by SSH is not changed for some incompatible type during or after login.

You say that the linux machine does not have ncurses, I believe that it just does not have the -devel package. You could try to compile Tig with the same ncurses version as the one present on the machine (probably not 6.1) to ensure compatibility with the compiled terminfo present in /usr/share.
