### ISSUE TITLE
segfault when viewing commit after refs

### ISSUE THREAD

**Issue by nkaretnikov** [jonas/tig#922]
This is on macOS, installed via brew.

```
% tig --version                                                                                                                                               
tig version 2.4.1
ncurses version 5.7.20081102
readline version 8.0
```

Steps to reproduce:
tig ->
`r` ->
select ref and `Enter` ->
`Tab` to a different buffer ->
`Enter` on a commit ->
segfault.

**Comment by nkaretnikov** [comment]
(The way to work around this is to press `O` after `Tab` to maximize the buffer.)

**Comment by koutcher** [comment]
readline 8.0 support requires tig 2.5.0 (ea43f8b).
