### ISSUE TITLE
refresh-mode doesn't work

### ISSUE THREAD

**Issue by c02y** [jonas/tig#932]
~~~
set refresh-mode auto
~~~
or 
~~~
set refresh-mode = periodic
set refresh-interval = 5
~~~
in ~/.tigrc, either of them works, 

Simple test, I'm in status view in tig, `touch abc` in the repo outisde of tig, the status view never gets updated, I have to maunally refresh to tig. I didn't test other cases.

**Comment by c02y** [comment]
After installing the lastest tig from repo, 
~~~
set refresh-mode = periodic
set refresh-interval = 5
~~~
works as expected, but `set refresh-mode auto` still doesn't work, but what I really like to use it `set refresh-mode auto`.

Could this bug be fixed too?

**Comment by koutcher** [comment]
The hierarchy of modes is:
manual = tig doesn't do anything
auto = tig reflects the changes it gets to know by some other actions
periodic = tig checks regularly for changes

In the use case you describe, in auto mode, if you just perform `touch abc` and do nothing in tig you can't expect it to discover the change.

**Comment by c02y** [comment]
Oh, I guess `set refresh-mode = periodic` is better than.

**Comment by patrickelectric** [comment]
Is it possible to update tig with a shortcut ?

**Comment by koutcher** [comment]
With the default bindings, you can press `F5` or `R` to force a refresh.
