### ISSUE TITLE
How to display the diff side by side when writing commit message

### ISSUE THREAD

**Issue by c02y** [jonas/tig#933]
I use some bindings like this in my ~/.tigrc:
~~~
bind status c >git commit
~~~

So I call `c` to git commit, but when I'm editing the commit message, I cannot see the diffs of the commit, I have to open another pane(tmux) and view the diffs.

Is there a way that tig can display the diffs when I'm writing the commit message?

**Comment by koutcher** [comment]
tig won't be able to display the browsable diff in a pane and the commit command in the other one (there is no management of pty in tig) but you can achieve what you want with `commit --verbose`.

**Comment by c02y** [comment]
OK, it could be a workaround. thanks.
