### ISSUE TITLE
HEAD not displayed

### ISSUE THREAD

**Issue by wolf99** [jonas/tig#952]
`tig version 2.3.0` (latest version on Ubuntu 18.04 universe)

![image](https://user-images.githubusercontent.com/281700/63649081-2c2d4500-c731-11e9-8bb7-8b911f34e244.png)

branch `pythagorean-triplet` is checked out, but it is not marked as HEAD

![image](https://user-images.githubusercontent.com/281700/63649128-a4940600-c731-11e9-9f89-f26e729dec3a.png)

**Comment by koutcher** [comment]
This is actually a feature... HEAD is shown only when in detached HEAD (e.g. during a rebase) as in "normal" situation the name of the current branch is shown in bright color.

**Comment by wolf99** [comment]
Hmm, is there a setting to change that?
Or maybe one to change the order of the branches so that the checked out one is left-most (i.e. `pythagorean-triplet` and `resistor-color` branches would be swapped position in the screen grab in my original post) ?

**Comment by koutcher** [comment]
No setting for this. You can try to play with the `commit-order` setting.

**Comment by wolf99** [comment]
No luck on either :(
Might look at changing the color to make it more apparent.

**Comment by koutcher** [comment]
You can also have a look to the setting `reference-format` and add `[*head*]` to the line for example.
