### ISSUE TITLE
Feature request: incremental history loading

### ISSUE THREAD

**Issue by KAction** [jonas/tig#958]
On repositories of moderate size (10k+ commits) there is very noticable
delay with black screen before `tig` displays list of commits. I guess
(did not read the source) tig loads whole history into memory on
startup.

On contary, `git log -p | less` starts instantly on repository of any
size. Scrolling to bottom still takes long time, but usually I am
interested in recent history.

Is it feasible to make `tig` load history incrementally?

**Comment by koutcher** [comment]
It does already. The delay you observe is certainly due to the `--topo-order` argument passed to `git log`. On large repos, the delay is greatly improved by enabling Git commit graph:
```
git config core.commitGraph true
git config gc.writeCommitGraph true
git commit-graph write --reachable
```

**Comment by KAction** [comment]
Thank you, it actually significantly improved start-up time.
