### ISSUE TITLE
the `git push` manully binding for tig will ignore `credential.helper 'cache --timeout 86400'` in ~/.gitconfig

### ISSUE THREAD

**Issue by c02y** [jonas/tig#965]
I added comment at the end of https://github.com/jonas/tig/issues/199 but it got no replies, so I raise this new issue.

I use the following config in ~/.tigrc
~~~
bind generic    pu   !<git push
~~~

so I can just us `git push` inside tig as suggested in other issue page.

but it ask for password every time when I `pu` inside tig which is weird since I already set 
~~~
  [credential]
      helper = cache --timeout 86400
~~~
and I `git push` inside terminal, it works normally and doesn't ask for password every time.

so anyone one knows the reason?

---------
**UPDATE**
Sometimes it doesn't ask for password, weird.

**Comment by koutcher** [comment]
Either it is not happy because of the lack of tty or the daemon gets killed. If switching to SSH key is not an option, you can try to set credentialCache.ignoreSIGHUP to true or play with core.askPass.

**Comment by koutcher** [comment]
`git config --global credentialCache.ignoreSIGHUP true` solves the problem.
