### ISSUE TITLE
How to configure tig to use alternate screen inside tmux?

### ISSUE THREAD

**Issue by onelin789** [jonas/tig#974]
I'm using tig inside tmux. Every time I quit tig, its content would be left on the screen. 

For vim, I configured it to use alternate screen, so that when quitting vim, the content of vim would be cleared and the screen would display whatever was there before vim was opened. 

Is there a way to configure tig to use an alternate screen?

**Comment by koutcher** [comment]
Tig is normally using alternate screen. So does Vim... unless your TERM variable is not set properly. Inside tmux you should have TERM=screen.

**Comment by onelin789** [comment]
I checked, TERM is set to screen inside tmux.

There is something weird with my setup. My vim by default didn't use alternate screen. I had to add the following to my vimrc:

```
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\e[5 q\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\e[1 q\<Esc>\\"
else
    let &t_SI = "\e[5 q"
    let &t_EI = "\e[1 q"
endif
```

**Comment by koutcher** [comment]
Strange because t_SI and t_EI are not related at all with alternate screen (t_ti and t_te are). Have you tried with an empty .tmux.conf ?

**Comment by onelin789** [comment]
Oh, sorry, I posted the wrong part of my vimrc. The part that's related to alternate screen is:
```
set t_ti=^[[?1049h
 set t_te=^[[?1049l
```

**Comment by koutcher** [comment]
Ok, here you assign them manually to what they should get automatically from the terminfo database. What do you get if you do `infocmp | head -2` and `infocmp | grep -e smcup -e rmcup` ?

**Comment by onelin789** [comment]
Hmm, both of them returned `infocmp: symbol lookup error: infocmp: undefined symbol: _nc_disable_period`, both inside and outside tmux.

**Comment by koutcher** [comment]
Sounds like you will have to fix your ncurses package installation. It should hopefully solve both your vim and tig issues. Alternate screen is probably not the only thing not working properly.

**Comment by onelin789** [comment]
So it turned I have two infocmp installed in different paths, and the one from the first path didn't work. I used the one in the second path and it showed the following:

```
$ infocmp | head -2
xterm-256color|xterm with 256 colors,

$ infocmp | grep -e smcup -e rmcup
rin=\E[%p1%dT, rmacs=\E(B, rmam=\E[?7l, rmcup=\E[?1049l,
sgr0=\E(B\E[m, smacs=\E(0, smam=\E[?7h, smcup=\E[?1049h,
```

**Comment by koutcher** [comment]
What about from inside tmux ? And do vim and tig use the libncursesw.so and terminfo database from the second path ? You can use `ldd` to check the library.

**Comment by onelin789** [comment]
Ah, right. That's the results from running infocmp outside tmux. Here is the result running infocmp inside tmux:

```
$ infocmp | head -2
screen|VT 100/ANSI X3.64 virtual terminal,
```
The second command did not return anything.

I checked, both vim and tig use `/lib64/libncurses.so.5`. But I'm not sure how to check which terminfo database they're using.

**Comment by koutcher** [comment]
Your terminfo database is somehow incomplete. The terminfo database is usually located in `/usr/share/terminfo`. If you have another version coming with your working `infocmp`, you can use the environment variable TERMINFO to use it rather than the default one.

Otherwise you should be able to fix the problem locally for your current user by doing the following (use the `tic`command coming with your working `infocmp`):
```
curl -O https://invisible-island.net/datafiles/current/terminfo.src.gz
gunzip terminfo.src
tic -x -o "$HOME/.terminfo" -e screen terminfo.src
```

**Comment by onelin789** [comment]
Ahh. `export TERMINFO=/usr/share/terminfo` fixed the issue for me. 

Thank you for your patient and prompt help!
