### ISSUE TITLE
How do you "show origin of this line" ?

### ISSUE THREAD

**Issue by MartyLake** [jonas/tig#977]
Hello,

Just discovered tig in the release notes of git-for-windows, and I am amazed by the speed of your tool compared to my beloved-but-slow `gitk`. One feature I use a lot in `gitk` is "show origin of this line" (when you right click in a red diff line of  a commit). 

Is there anything equivalent in `tig` ?

Best,

**Comment by koutcher** [comment]
In diff view, move the cursor to the line of interest, press `b` then `Enter`.

**Comment by MartyLake** [comment]
It works ! Thank you very much @koutcher

**Comment by MartyLake** [comment]
Not sure if should open another issue as they are very close.

The use case is when I have a change I want to know to which commit I should fixup. I move the cursor to the removed line (red) and press b, it goes blame mode.

I would expect it to show a blame view of the file corresponding to the old state so I can read the commit-sha that I want to fixup to.

Instead, it shows a blame view of the file in the current state, and the removed line is not here anymore.

**Comment by koutcher** [comment]
I believe this should be fixed by c5b1f0c.

**Comment by MartyLake** [comment]
@koutcher It does, thanks for following up on this one !
