### ISSUE TITLE
Display only the specified range when blaming

### ISSUE THREAD

**Issue by jeenuv** [jonas/tig#978]
`git blame` supports `-L` option with which we can supply a range of lines to blame, and git outputs the blame for **only** those lines. This comes in handy when invoking from within an editor, say Vim. For example, to view the blame from lines 2000 to 2020, I could say `:!git blame -L2000,2020 -- %`.

Two issues with `tig`:

* `tig` does accept the same option. However, `tig` outputs **all** lines in the file. This means, for the example above, even though I'm interested in the 20 lines towards the bottom, `tig` shows the whole file, and I've to scroll 2000 lines for the view I'm interested in. Any chance this can supported?
* To `tig`, I've to specify it as `-L2000,2020`; it seems to be confused if I say `-L 2000,2020`, with white space after `-L`.

**Comment by Daghall** [comment]
This is a really old issue that recently got fixed, but for what it's worth, I used the `+<number>` parameter to `tig` to solve this problem:
```vim
nmap <silent> <Leader>l :silent :execute "!tig blame " . shellescape(expand("%")) . " +" . line(".") <CR>:redraw!<CR>

```
