### ISSUE TITLE
Vertical window separator renders as "x" in Putty, but the graph is OK

### ISSUE THREAD

**Issue by proski** [jonas/tig#981]
When run inside Putty, tig renders the vertical window separator in putty using `x` characters. However, the version graph uses correct vertical lines.

Observed with different fonts: Consolas, DejaVu Sans Mono, Fira Mono, Fixedsys, Inconsolata, Lucida Console, Lucida Sans Typewriter. Observed with putty 0.70 and 0.73. Tig 2.4.1 and the current git versions are affected:

```
$ /usr/bin/tig --version
tig version 2.4.1
ncursesw version 5.9.20140118
readline version 6.3
$ src/tig --version
tig version 2.5.0-2-gca0809d
ncursesw version 5.9.20140118
readline version 6.3
```

The system running Putty is Windows 10, the system running tig is Ubuntu 14.04.

The described behavior corresponds to `diff-view-line-graphics = utf-8`. If it's `ascii`, the vertical bar is rendered using `|`, but the graph becomes less pretty. For `default`, `x` is used for the vertical bar, and the graph looks even worse than in the `ascii` mode. The graph is rendered using letters that don't even look like lines.

```
 o make-builtin-config:
 Mqk Merge pull request
 x o Add default bindin
 x o Add option to star
 oqj Introduce reflog v
 o Fix ls-tree tree-ish
```

I suspect that the vertical window separator is rendered using the `default` mode even though the `utf-8` mode is in effect. Apparently, putty has an issue with `diff-view-line-graphics = default`.

I would consider this issue resolved if the window separator renders in the `utf-8` mode correctly.

![putty-tig](https://user-images.githubusercontent.com/1317472/72017008-ad393480-3219-11ea-9974-07d5342be6ff.png)

**Comment by proski** [comment]
It turns `opt_line_graphics` is incorrectly treated like boolean in two places. One is responsible for the vertical window separator, another for the separator after line numbers that are triggered by the `#` key.

Here's a quick and dirty fix that makes UTF-8 mode work like the ASCII mode:

```diff
diff --git a/src/display.c b/src/display.c
index a23d41a..028bcc9 100644
--- a/src/display.c
+++ b/src/display.c
@@ -187,7 +187,7 @@ static void
 redraw_display_separator(bool clear)
 {
        if (display_sep) {
-               chtype separator = opt_line_graphics ? ACS_VLINE : '|';
+               chtype separator = (opt_line_graphics == GRAPHIC_DEFAULT) ? ACS_VLINE : '|';

                if (clear)
                        wclear(display_sep);
diff --git a/src/draw.c b/src/draw.c
index e5b651f..92af79c 100644
--- a/src/draw.c
+++ b/src/draw.c
@@ -314,7 +314,7 @@ draw_lineno_custom(struct view *view, struct view_column *column, unsigned int l
        unsigned long digits3 = MIN(9,MAX(3,column->width));
        int max = MIN(VIEW_MAX_LEN(view), digits3);
        char *text = NULL;
-       chtype separator = opt_line_graphics ? ACS_VLINE : '|';
+       chtype separator = (opt_line_graphics == GRAPHIC_DEFAULT) ? ACS_VLINE : '|';
        struct line_number_options *opts = &column->opt.line_number;
        int interval = opts->interval > 0 ? opts->interval : 5;
```

The proper fix would need to use the UTF-8 vertical bar in the UTF-8 mode, but the code would need to use strings instead of single characters for the separators.

Also, using `TERM=putty` instead of `TERM=xterm` fixes the vertical bars, but I would prefer to fix the issue in tig.

The Linux version of Putty exhibits the issue just like the Windows version, so Windows is not needed to work on this issue.

**Comment by koutcher** [comment]
There is a known issue with PuTTY when trying to mix PuTTY, UTF-8 and ncurses. It was fixed in PuTTY 0.71, but you need to select option `Enable VT100 line drawing even in UTF-8 mode` in Window -> Translation. With earlier versions of PuTTY, try `export NCURSES_NO_UTF8_ACS=1` before running tig.

**Comment by proski** [comment]
@koutcher Thank you, that's explain exactly what's going on! That option fixes the ugly tree display in the `default` mode as well.
To make things work out-of-the-box, tig should stop using VT100 line drawing in UTF-8 mode.

**Comment by proski** [comment]
I believe I have a good fix for the issue. No workarounds should be necessary anymore. Can someone take a look at #983 please?
