### ISSUE TITLE
status view of git bare repository

### ISSUE THREAD

**Issue by vbauerster** [jonas/tig#987]
I have a git bare repository created with `git init --bare $HOME/.myconf`.
While invoking `tig` from this bare repository I'm able to view commit history, but not status view.
It says `The status view requires a working tree` and it's right, but how do I pass a working tree in that case?
With git it is `git --git-dir=$HOME/.myconf --work-tree=$HOME`.
Is it possible to tell `tig` where is a working tree somehow?

**Comment by koutcher** [comment]
Unfortunately `--work-tree` argument has not been implemented and the status view does not check the `GIT_WORK_TREE` environment variable. But tig has support for detached worktrees, you could easily convert your repository with the following commands:
```
git config core.bare false
git config core.worktree "$HOME"
```

**Comment by vbauerster** [comment]
I've applied those configs, but `tig` shows empty status page despite there are changes.

**Comment by koutcher** [comment]
You may need to issue a `git reset` first to initialize the index.

**Comment by vbauerster** [comment]
Nop, it's same blank status view after `git reset`.

**Comment by koutcher** [comment]
Strange, what does `git status` say ?

**Comment by vbauerster** [comment]
It shows my modified files.

**Comment by koutcher** [comment]
The worktree support was improved in tig 2.5.0, could it be the reason it doesn't work for you ?

**Comment by vbauerster** [comment]
Ok, here is `tig` version I use:
```
❯ tig --version
tig version 2.5.0
ncurses version 5.7.20081102
readline version 8.0
```
and config of git `detached` (used to be bare = true) repo:
```
❯ cat .myconf/config
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
        worktree = /Users/vbauer
[status]
        showUntrackedFiles = no
[submodule ".tmux/plugins/tpm"]
        active = true
        url = https://github.com/tmux-plugins/tpm
[submodule ".zprezto"]
        active = true
        url = https://github.com/sorin-ionescu/prezto
[remote "origin"]
        url = https://github.com/vbauerster/myconf
        fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by koutcher** [comment]
That was a tricky one. The fact that .myconf is inside the worktree without being .git somehow bothers tig. There was actually a simpler approach which works. Remove core.worktree and revert core.bare and try:
```
> GIT_DIR=/Users/vbauer/.myconf GIT_WORK_TREE=/Users/vbauer tig status
```

**Comment by vbauerster** [comment]
It worked that way. Thanks!
However option `showUntrackedFiles = no` isn't respected.

**Comment by koutcher** [comment]
You're welcome. For untracked files, check status-show-untracked-files in tigrc.

**Comment by vbauerster** [comment]
Is it possible to have `tigrc` per repository basis?

**Comment by koutcher** [comment]
Try `git config tig.status-show-untracked-files false`.

**Comment by vbauerster** [comment]
Perfect now!
@koutcher thank you very much for support.
I'm closing this one now.
