### ISSUE TITLE
Add more vim navigation shortcut

### ISSUE THREAD

**Issue by MartinDelille** [jonas/tig#992]
I'm very used to vim and I wondered if it would be possible to add some missing navigation shortcuts:

- `Ctrl + b`: move back one full screen
- `Ctrl + f`: move forward one full screen

**Comment by koutcher** [comment]
Vim-like bindings can be found in https://github.com/jonas/tig/blob/master/contrib/vim.tigrc.

**Comment by MartinDelille** [comment]
Awesome!
