### ISSUE TITLE
[BUG]: can't display difference between two branches where a branch contains .

### ISSUE THREAD

**Issue by danielb2** [jonas/tig#996]
```
$ git status -sb
## eslint.update

$ tig master..eslint.update
```

Expected result:
difference between the two branches

Actual result:
no output at all

NOTE:  since most often I will want to do a diff between the current branch and whatever other branch, it would be convenient if I didn't have to list the current branch at all:  `tig master..` or `tig ..master` or both.

**Comment by danielb2** [comment]
basically I just want to be able to do `git diff <branch>`

**Comment by koutcher** [comment]
`tig master..eslint.update`, `tig master..`, `tig ..master` all work fine for me (tig-2.5.0-14-g70ac221).

**Comment by danielb2** [comment]
derp. I needed to hit enter because I didn't see the one line at the top as something to click
