### ISSUE TITLE
New Feature Request: Marker next to commit

### ISSUE THREAD

**Issue by mihaigalos** [jonas/tig#997]
This Issue is a placeholder for Feature request to set a marker next to a commit.
Once this feature is in place, it can be extended to allow easy visualization when i.e. using `git bisect`.

I could help with the implementation, if this makes sense. Can you please evaluate and if positive, give me some tips on where to start? Thank you for this awesome `tig`!

The feature could look like this (rather uninterestingly copied from notepad++), but to prove the point :
![image](https://user-images.githubusercontent.com/16443090/77154425-f4566800-6a9b-11ea-9495-11fc44a0d79b.png)

**Comment by koutcher** [comment]
Have a look to the alternative proposed at the end of #915.

**Comment by mihaigalos** [comment]
OK, looks promising! :+1:
