### ISSUE TITLE
Add single line stashing/unstashing

### ISSUE THREAD

**Issue by oto-ledger** [jonas/tig#998]
After a while of daily using tig instead of remembering crazy git command lines, I've came to a conclusion that could save my day in terms of features.
Wouldn't it be possible to support single line stashing/unstashing as it is supported for single line staging/unstaging with the key binding '1'.

**Comment by koutcher** [comment]
Unlike staging, there is no interface proposed by git to manipulate the stash with patches other than the interactive command `git stash -p`.
